### PR TITLE
Fix IngestSegmentFirehoseFactory

### LINKED ISSUE #3608: IngestSegmentFirehoseFactory race between tasks
IngestSegmentFirehoseFactory uses a fixed task id `"reindex"` when creating the toolbox factory that it uses to get segments. This creates a race condition where two tasks could actually download the same segment at the same time into the same directory, and one will get clobbered and fail.

One situation where this can happen easily is if you're reindexing a datasource into _two_ datasources (maybe reducing to two different levels of grain). The tasks will proceed simultaneously, since there's no cross locking, but they'll be downloading the same segments for the input datasource.

One fix is having it actually use the real task id (which would need to get plumbed in). This has the advantage of putting the task files all together, and using the existing mechanisms for cleaning up task work directories.

### PR DESCRIPTION
**Pull request by onlychoice**
Fix #3608 and #3655 .

Pass the TaskToolbox of the task to the Firehose.

### CODE REVIEW

File: indexing-service/src/main/java/io/druid/indexing/firehose/IngestSegmentFirehoseFactory.java [hunk 1]
```diff
@@ -121,21 +122,29 @@ public DimFilter getDimensionsFilter()
...
   {
     log.info("Connecting firehose: dataSource[%s], interval[%s]", dataSource, interval);
-    // better way to achieve this is to pass toolbox to Firehose, The instance is initialized Lazily on connect method.
-    // Noop Task is just used to create the toolbox and list segments.
-    final TaskToolbox toolbox = injector.getInstance(TaskToolboxFactory.class).build(
-        new NoopTask("reingest", 0, 0, null, null, null)
-    );
+
+    if (taskToolbox == null) {
+      // better way to achieve this is to pass toolbox to Firehose, The instance is initialized Lazily on connect method.
```
Comment (leventov) [inline indexing-service/src/main/java/io/druid/indexing/firehose/IngestSegmentFirehoseFactory.java]: Now it happens, should this comment be changed?

Comment (onlychoice) [inline indexing-service/src/main/java/io/druid/indexing/firehose/IngestSegmentFirehoseFactory.java]: done

**Comment by gianm** [comment]
@leventov any other comments?
