### PR TITLE
Fix transient failure of ITUnionQueryTest

### LINKED ISSUE #4346: Transient failure of ITUnionQueryTest
Here is the travis link. https://travis-ci.org/druid-io/druid/jobs/238169889

### PR DESCRIPTION
**Pull request by jihoonson**
Fixes #4346. The problem seems like data sources are not ready when submitting test queries. I changed to wait until all data sources are ready for querying.

---
This change is [Reviewable](https://reviewable.io/reviews/druid-io/druid/4362)

### CODE REVIEW

File: integration-tests/src/main/java/io/druid/testing/utils/TestQueryHelper.java [hunk 1]
```diff
@@ -118,4 +123,27 @@ private String getBrokerURL()
...
+  @SuppressWarnings("unchecked")
+  public int countRows(String dataSource, String interval)
+  {
+    TimeseriesQuery query = Druids.newTimeseriesQueryBuilder()
+                                  .dataSource(dataSource)
+                                  .aggregators(
+                                      ImmutableList.<AggregatorFactory>of(
+                                          new LongSumAggregatorFactory("rows", "count")
+                                      )
+                                  ).granularity(Granularities.ALL)
```
Comment (leventov) [inline integration-tests/src/main/java/io/druid/testing/utils/TestQueryHelper.java]: I think it's more according to the style to move `.granularity(Granularities.ALL)` to the next line.

Comment (jihoonson) [inline integration-tests/src/main/java/io/druid/testing/utils/TestQueryHelper.java]: Ah, it seems better. Since this pr is already merged, I'll fix this later.
