### PR TITLE
Fix DefaultLimitSpec to respect sortByDimsFirst

### LINKED ISSUE #5378: DefaultLimitSpec doesn't respect sortByDimsFirst
The timestamp is always compared first in the ordering created by DefaultLimitSpec (https://github.com/druid-io/druid/blob/master/processing/src/main/java/io/druid/query/groupby/orderby/DefaultLimitSpec.java#L201-L253). This breaks the behavior `sortByDimsFirst`.

I'm fixing this bug, and wonder what is the correct behavior of `sortByDimsFirst`. If some metrics are specified as well as dimensions for ordering in limitSpec, should they be compared before comparing timestamp? or only dimensions should be compared before timestamp?

IMO, it looks to make sense to compare metrics as well as dimensions before timestamp if `sortByDimsFirst` is set to true, because `sortByDimsFirst` option is introduced to avoid sorting in each time bucket and thus get the result sorted by columns.

@himanshug what do you think?

### PR DESCRIPTION
**Pull request by jihoonson**
Fixes #5378.

---
This change is [Reviewable](https://reviewable.io/reviews/druid-io/druid/5385)

### CODE REVIEW

File: processing/src/main/java/io/druid/query/groupby/orderby/DefaultLimitSpec.java [hunk 1]
```diff
@@ -167,12 +167,17 @@ public boolean isLimited()
       }
     }
 
+    if (!sortingNeeded) {
+      // If granularity is ALL, sortByDimsFirst doesn't change the sorting order.
+      sortingNeeded = granularity.equals(Granularities.ALL) || sortByDimsFirst;
```
Comment (himanshug) [inline processing/src/main/java/io/druid/query/groupby/orderby/DefaultLimitSpec.java]: so if , granularity = ALL and sortByDimsFirst = false, then "sortingNeeded" gets set to true while in older versions it would've been false. I see the comment but still not sure why this change is necessary.

Comment (jihoonson) [reply processing/src/main/java/io/druid/query/groupby/orderby/DefaultLimitSpec.java]: Sorry, this is a bug. Fixed it and added a test.

**Comment by b-slim** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[processing/src/main/java/io/druid/query/groupby/orderby/LimitSpec.java, line 54 at r1](https://reviewable.io:443/reviews/druid-io/druid/5385#-L5URWzxlOQ-HzXRIQLP:-L5URWzxlOQ-HzXRIQLQ:bbrcxuh) ([raw file](https://github.com/druid-io/druid/blob/0105cdbc19828009d21de57a30ba55794a518d30/processing/src/main/java/io/druid/query/groupby/orderby/LimitSpec.java#L54)):*
> ```Java
>    * @param aggs       query aggregators
>    * @param postAggs   query postAggregators
>    *
> ```

How about adding the new Params instead of removing this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/druid-io/druid/5385)*

**Comment by b-slim** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/druid-io/druid/5385#-:-L5UTHjo2QtkgFa1ZYBw:bnfp4nl)*

**Comment by b-slim** [comment]
Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/druid-io/druid/5385)*

File: processing/src/main/java/io/druid/query/groupby/orderby/DefaultLimitSpec.java [hunk 2]
```diff
@@ -167,12 +167,17 @@ public boolean isLimited()
       }
     }
 
+    if (!sortingNeeded) {
+      // If granularity is ALL, sortByDimsFirst doesn't change the sorting order.
+      sortingNeeded = !granularity.equals(Granularities.ALL) && sortByDimsFirst;
```
Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/orderby/DefaultLimitSpec.java]: It looks like this will change some sortByDimsFirst query executions from streaming queries into queries that need to materialize results. Is this necessary in order to fix the bug?

Comment (jihoonson) [reply processing/src/main/java/io/druid/query/groupby/orderby/DefaultLimitSpec.java]: Yes, `sortByDimsFirst` was not considered before. This `if` clause is to prune more cases when sorting (and materializing) is not necessary.

**Comment by jihoonson** [comment]
@b-slim added.

**Comment by gianm** [comment]
LGTM, thanks @jihoonson.
