### PR TITLE
fix behaviour of middlemanagers around ZK disconnects , fixes #709

### LINKED ISSUE #709: Better behavior around middleManagers going temporarily offline
Currently middleManagers publish task statuses as ephemeral nodes in ZK, but they are not re-created upon connection loss, so the RTR can forget a worker is running tasks if that worker disconnects and reconnects to ZK. Maybe we could use an Announcer or PersistentEphemeralNode.

The RTR will also need sort of grace period before failing a task after the status announcement goes away, which it currently does immediately. That might pave the way for eventually giving middleManagers a way to resume tasks when they restart, which might be nice.

### PR DESCRIPTION
**Pull request by nishantmonu51**
At present there are multiple places from which the task status can get deleted which leads to issues where the state of middle manager and overlord gets out of sync when either the middle manager is rebooted. Also the state changes can be lost during leadership changes. 

This PR makes the overlord to be the *only* thing that deletes the status, and for it to *not* be an ephemeral node. 
The changes include - 
1) change task status *not* to be ephemeral nodes 
2) If a middlemanager is restarted it updates the task status for tasks running from previous run to FAILED. 
3) RemoteTaskRunner now waits for configurable grace period before failing a task when the worker is temporarily disconnected from ZK. 
4) RemoteTaskRunner ensures proper cleanup of task status nodes.

### CODE REVIEW

**Comment by nishantmonu51** [comment]
fixes #709

**Comment by drcrallen** [comment]
IMHO we need to rely only on ephemeral nodes in ZK. I went through a similar discussion with @cheddar  a few weeks ago related to storing QTL states in ZK and I'm in agreement with him that ZK should be completely droppable (meaning we shouldn't need to do regular backups of ZK to keep the cluster stable).

**Comment by nishantmonu51** [comment]
IIRC in QTL, you were trying to store the lookup tables in zookeeper, 
here we are storing the transient status of the tasks running on different nodes instead of permanent lookup tables. 

I initially tried using announcer or persistentEphermal node in which the worker can recreate the status node after ZK disconnection, but the issue there is that the communication of status is not one way the status are being announced by the MM and then finally removed by overlord. 
when using persistentEphermal nodes MM has no knowledge of whether the status is being read by the indexer or not and again recreates the status whenever the overlord removes the status. 

I had a discussion with @gianm on this and it came out it might make more sense for the overlord to be the **only** thing that deletes the status, and for it to *not* be an ephemeral node
so instead of detecting dead tasks through disappearance of an ephemeral status node, the overlord could detect it through disappearance of worker announcement node and overlord to do the cleanup after a grace period.

**Comment by nishantmonu51** [comment]
This PR addresses the failures with current way communication through Zookeeper nodes, 
Ideally in future we should move the task assignment and status announcements out of zookeeper, 
created a feature request here for moving the communication out of zookeeper -  https://github.com/druid-io/druid/issues/1420

File: indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java [hunk 1]
```diff
@@ -844,6 +858,48 @@ private void removeWorker(final Worker worker)
...
+  {
+    removedWorkerCleanups.put(
+        worker, exec.schedule(
+            new Runnable()
+            {
+              @Override
+              public void run()
+              {
+                log.info("Running scheduled cleanup for Worker[%s]", worker);
+                for (String assignedTask : tasksToFail) {
```
Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java]: In the presence of very spotty networking, the host could come and go. In such a case it would make sense to me to have a "last seen on" check somehow so that the task could be skipped on this round of purging if it was seen within 5 minutes.

File: indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunnerFactory.java [hunk 2]
```diff
@@ -46,7 +49,8 @@ public RemoteTaskRunnerFactory(
       final IndexerZkConfig zkPaths,
       final ObjectMapper jsonMapper,
       @Global final HttpClient httpClient,
-      final Supplier<WorkerBehaviorConfig> workerConfigRef
+      final Supplier<WorkerBehaviorConfig> workerConfigRef,
+      ScheduledExecutorFactory factory
```
Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunnerFactory.java]: Can this be annotated somehow so that other ScheduledExecutorFactories can be used in the future?

File: indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java (hunk 1 above)
Comment (nishantmonu51) [inline indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java]: the cleanup gets cancelled in addWorker() if the worker shows up within grace period, So in a spotty network the tasks will not fail.

File: indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java [hunk 3]
```diff
@@ -844,6 +858,48 @@ private void removeWorker(final Worker worker)
     }
   }
 
+  private void scheduleTasksCleanupForWorker(final String worker, final List<String> tasksToFail)
+  {
+    removedWorkerCleanups.put(
```
Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java]: If the worker is never seen again, then this map will not get rid of the values. Can we have a cleanup at the end of the listenable?

File: indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java [hunk 4]
```diff
@@ -654,6 +676,12 @@ private void announceTask(
     log.info("Worker[%s] reportin' for duty!", worker.getHost());
 
     try {
+      ScheduledFuture previousCleanup = removedWorkerCleanups.remove(worker.getHost());
+      if (previousCleanup != null) {
+        log.info("cancelling scheduled task cleanup for Worker[%s]", worker.getHost());
+        previousCleanup.cancel(false);
```
Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java]: suggest

```java
if(!previousCleanup(false)){
  try{
    previousCleanup.get();
  }
  catch(lots of exception types here){
    //probably log if not CancellationException
  }
}
```

Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java]: Or else you can have this thread and the previousCleanup both trying to modify resources at the same time.

File: indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java [hunk 5]
```diff
@@ -128,6 +132,10 @@
 
   private volatile boolean started = false;
 
+  private final ScheduledExecutorService exec;
```
Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java]: Can we make this a ListeningScheduledExecutorService?

File: indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java [hunk 6]
```diff
@@ -844,6 +858,48 @@ private void removeWorker(final Worker worker)
...
+        worker, exec.schedule(
+            new Runnable()
+            {
+              @Override
+              public void run()
+              {
+                log.info("Running scheduled cleanup for Worker[%s]", worker);
+                for (String assignedTask : tasksToFail) {
+                  String taskPath = JOINER.join(indexerZkConfig.getTasksPath(), worker, assignedTask);
+                  String statusPath = JOINER.join(indexerZkConfig.getStatusPath(), worker, assignedTask);
```
Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java]: Ultimately going ZkPaths instead of our own custom JOINER would be nice, but since this class uses JOINER everywhere, may as well keep with that for now.

File: indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java (hunk 3 above)
Comment (nishantmonu51) [inline indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java]: fixed and added check in test.

File: indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java (hunk 4 above)
Comment (nishantmonu51) [inline indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java]: fixed.

File: indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java (hunk 5 above)
Comment (nishantmonu51) [inline indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java]: dint get the benefit from making it listenable, do you propose to spilt the existing cleanup work into listeners ?

File: indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java [hunk 7]
```diff
@@ -654,6 +677,19 @@ private void announceTask(
     log.info("Worker[%s] reportin' for duty!", worker.getHost());
 
     try {
+      ScheduledFuture previousCleanup = removedWorkerCleanups.remove(worker.getHost());
+      if (previousCleanup != null) {
+        log.info("cancelling scheduled task cleanup for Worker[%s]", worker.getHost());
```
Comment (fjy) [inline indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java]: Cancelling
worker[]

minor punctation things

**Comment by fjy** [comment]
:+1: I'm in general agreement with the changes here. It would be nice to make tasks more restartable in the future. I think when we rework segments announcements to use a gossip protocol or something that doesn't involve ZK, the same logic can be used for tasks. For hadoop index tasks, a restart of the task can just mean starting things over. For a realtime index task, the task can behave the same way as a realtime node restarting. This of course, requires the realtime index task to read from Kafka. I think more discussions and proposals and required for those changes. Just some food for thought right now.

**Comment by nishantmonu51** [comment]
@gianm, @xvrl can you also have a look at the changes ?

File: indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java [hunk 8]
```diff
@@ -654,6 +677,19 @@ private void announceTask(
...
+        if (!previousCleanup.cancel(false)) {
+          try {
+            previousCleanup.get();
```
Comment (xvrl) [inline indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java]: is there a reason to even attempt to call `get()`? If we are unable to cancel the future the tasks will be cleaned up regardless

File: indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java [hunk 9]
```diff
@@ -146,6 +156,7 @@ public RemoteTaskRunner(
     this.workerPathCache = pathChildrenCacheFactory.make(cf, indexerZkConfig.getAnnouncementsPath());
     this.httpClient = httpClient;
     this.workerConfigRef = workerConfigRef;
+    this.exec = factory.create(1, "RemoteTaskRunner-Scheduled-Exec--%d");
```
Comment (xvrl) [inline indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java]: we probably don't need one executorservice per remotetaskrunner, one shared one should be enough?

File: indexing-service/src/main/java/io/druid/indexing/worker/WorkerTaskMonitor.java [hunk 10]
```diff
@@ -84,6 +84,19 @@ public WorkerTaskMonitor(
   public void start()
   {
     try {
+      // cleanup any old running task announcements which are invalid after restart
+      for (TaskAnnouncement announcement : workerCuratorCoordinator.getAnnouncements()){
```
Comment (xvrl) [inline indexing-service/src/main/java/io/druid/indexing/worker/WorkerTaskMonitor.java]: we probably need to wait for pathchildrencache to be initialized before we run this, otherwise we might not clean up everything.

File: indexing-service/src/main/java/io/druid/indexing/overlord/config/RemoteTaskRunnerConfig.java [hunk 11]
```diff
@@ -32,6 +32,10 @@
   private Period taskAssignmentTimeout = new Period("PT5M");
 
   @JsonProperty
+  @NotNull
+  private Period taskCleanupTimeout = new Period("PT5M");
```
Comment (xvrl) [inline indexing-service/src/main/java/io/druid/indexing/overlord/config/RemoteTaskRunnerConfig.java]: 5 minutes might be a bit short, maybe 15min in case things are taking a while to recover, just to be conservative.

File: indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java (hunk 8 above)
Comment (nishantmonu51) [inline indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java]: true, we can skip waiting for get(), fixed.

File: indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java (hunk 9 above)
Comment (nishantmonu51) [inline indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java]: fixed.

File: indexing-service/src/main/java/io/druid/indexing/worker/WorkerTaskMonitor.java (hunk 10 above)
Comment (nishantmonu51) [inline indexing-service/src/main/java/io/druid/indexing/worker/WorkerTaskMonitor.java]: the getAnnouncements() doesn't reads from the cache, so its fine to not wait for the cache to be initialized here.

File: indexing-service/src/main/java/io/druid/indexing/overlord/config/RemoteTaskRunnerConfig.java (hunk 11 above)
Comment (nishantmonu51) [inline indexing-service/src/main/java/io/druid/indexing/overlord/config/RemoteTaskRunnerConfig.java]: fixed.

File: indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java [hunk 12]
```diff
@@ -128,6 +134,13 @@
 
   private volatile boolean started = false;
 
+  private static final ScheduledExecutorService exec = ScheduledExecutors.fixed(
```
Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java]: Can we rename this cleanerExec or something a little more descriptive (in the thread name template as well)

Comment (xvrl) [inline indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java]: I would prefer if this executor was injected rather than static

**Comment by drcrallen** [comment]
At a high level, will this only work if there is only one worker per host?

**Comment by nishantmonu51** [comment]
yeah, the current RTR is structured around using worker.getHost() as a key for identifying a worker and assumes it will be unique for every worker.

**Comment by cheddar** [comment]
Just a clarification.  What do we expect to happen if ZK completely dies and has to be restarted without any of the old state?  Will things break irreparably?

**Comment by nishantmonu51** [comment]
In case of a complete ZK state cleanup, the overlord will not have knowledge of any tasks running on the workers, and it will end up assigning tasks to the workers and the workers will end up assigned more tasks than the capacity allocated for a while.

**Comment by drcrallen** [comment]
Since this in general makes things better, I'm removing myself as a blocker here

**Comment by cheddar** [comment]
@nishantmonu51 Ok, That seems reasonable.  One last question: What will happen if locks are in the metadata store, but the ZK is completely wiped.  Will the system recover on its own, or will it deadlock?

**Comment by nishantmonu51** [comment]
not sure about the behaviour of locks when the zookeeper is completely wiped, 
on a quick look into the code it seems that the overlord maintains a set of active tasks in metadata storage, and reads that to reconstruct the locks again, so it might be a problem, 
@gianm would have better idea on what will happen in such a scenario ?

**Comment by cheddar** [comment]
@nishantmonu51 I'm mostly interested in making sure that the changes you are introducing won't adversely affect what's there.  Like, will the permanency of the znodes cause thigns to become better, worse, or same?

**Comment by nishantmonu51** [comment]
It definitely makes things better in case of zk disconnections when nodes get disconnected due to network issues or load issues with zk. 
In case of complete zk state wipeout, things will be same as of today i believe.

**Comment by gianm** [comment]
@nishantmonu51, are you wondering what would happen in the current code? Currently the thing that manages the locks (the lockbox) and the thing that interacts with ZK (the RTR) are totally separate. The contract is that the RTR needs to resolve the futures it returned from "run" when it decides that a task is no longer running, and as long as it does that correctly, the lockbox won't contain any stale locks that might cause deadlocks.

**Comment by gianm** [comment]
I think the current behavior if ZK is wiped while the overlord and middle managers are down is that the overlord will load up the marked-as-running tasks and their locks from the metadata storage, then pass them all to the RTR, which would cause them to start running again (since the RTR won't see any of the markers in ZK that indicated this was done already). Then it should resolve them as usual once they finish.

**Comment by nishantmonu51** [comment]
yeah, i was wondering about the current code, as this PR makes changes to ensure that RTR and MM state remains in sync during ZK disconnects, but it can still get out of sync in case of total ZK cleanup.
 
@cheddar, to answer your question things wont be permanently broken and system will recover.

**Comment by cheddar** [comment]
Ok, if we believe that this PR won't make things worse, then great.

Fwiw, we recently had to restore our DB from a backup that had stale locks in it.  Those locks never actually got cleaned up until we manually went in and deleted all lock entries from the DB.  This did cause a bit of indexing deadlock for us.  So, the current behavior can be improved as well.  Given that this won't make that any worse and the system will continue to operate correctly if ZK is compeletely wiped out, I have no objections.
