### PR TITLE
An effort to fix transient error in BrokerServerViewTest

### LINKED ISSUE #1512: transient test failure in BrokerServerViewTest.testMultipleServerAddedRemovedSegment
In https://travis-ci.org/druid-io/druid/jobs/70802104

org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /druid/segments/locahost:0

	at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)

	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)

	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783)

	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:698)

	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:675)

	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107)

	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:671)

	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:453)

	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:443)

	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:423)

	at org.apache.curator.framework.imps.CreateBuilderImpl$4.forPath(CreateBuilderImpl.java:331)

	at org.apache.curator.framework.imps.CreateBuilderImpl$4.forPath(CreateBuilderImpl.java:267)

	at io.druid.client.BrokerServerViewTest.setupZNodeForServer(BrokerServerViewTest.java:382)

	at io.druid.client.BrokerServerViewTest.testMultipleServerAddedRemovedSegment(BrokerServerViewTest.java:183)d

### PR DESCRIPTION
**Pull request by guobingkun**
Fixes #1512. This is an effort to  fix the transient error in BrokerServerViewTest. 
Specifically, the transient error is
```
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.571 sec <<< FAILURE! - in io.druid.client.BrokerServerViewTest
testSingleServerAddedRemovedSegment(io.druid.client.BrokerServerViewTest)  Time elapsed: 1.24 sec  <<< ERROR!
org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /druid/segments/localhost:1234
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:727)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:703)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107)
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:699)
	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:477)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:467)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:447)
	at org.apache.curator.framework.imps.CreateBuilderImpl$4.forPath(CreateBuilderImpl.java:355)
	at org.apache.curator.framework.imps.CreateBuilderImpl$4.forPath(CreateBuilderImpl.java:291)
	at io.druid.client.BrokerServerViewTest.setupZNodeForServer(BrokerServerViewTest.java:383)
	at io.druid.client.BrokerServerViewTest.testSingleServerAddedRemovedSegment(BrokerServerViewTest.java:112)
```

### CODE REVIEW

**Comment by fjy** [comment]
:+1: after travis

File: server/src/test/java/io/druid/client/BrokerServerViewTest.java [hunk 1]
```diff
@@ -371,15 +371,24 @@ public CallbackAction segmentViewInitialized()
 
   private void setupZNodeForServer(DruidServer server) throws Exception
   {
+    final String zNodePathAnnounce = ZKPaths.makePath(announcementsPath, server.getHost());
+    final String zNodePathSegment = ZKPaths.makePath(inventoryPath, server.getHost());
+
+    if (curator.checkExists().forPath(zNodePathAnnounce) != null) {
```
Comment (xvrl) [inline server/src/test/java/io/druid/client/BrokerServerViewTest.java]: do you mind adding some comments to explain why those are necessary?

**Comment by xvrl** [comment]
@fjy why did we merge? I had some comments

File: server/src/test/java/io/druid/client/BrokerServerViewTest.java (hunk 1 above)
Comment (guobingkun) [inline server/src/test/java/io/druid/client/BrokerServerViewTest.java]: @xvrl sure, will do.

**Comment by guobingkun** [comment]
@xvrl I can send another PR for the comment. Basically, it just do an explicit check whether the zNodes we are about to create exist or not, if exist, then delete them to make sure we have a clean state.

**Comment by guobingkun** [comment]
Sent #2074
