### PR TITLE
HttpServerInventoryView: fixed startup wait time and more informative logging

### LINKED ISSUE #5331: HttpServerInventoryView: startup delayed unexpectedly
I just tried the http based segment view stuff today, and noticed that my broker took a long time to start up. It seems to be related to timing out waiting for servers to initialize. However the initialization seems fine, in that when I query `/druid-internal/v1/httpServerInventoryView` after the broker is done starting, the server "ip-172-31-0-22.ec2.internal:8303" does appear in the list and looks good:

```
  "ip-172-31-0-22.ec2.internal:8303": {
    "notSyncedForSecs": 5,
    "notSuccessfullySyncedFor": 5,
    "consecutiveFailedAttemptCount": 0,
    "started": true
  }
```

There are two different issues here, I think (we could split them but I decided it was simpler to put them in one github issue for now…)

1. There were some problems contacting this server at first (connection refused), but you can see from the logs that these errors stopped getting logged many minutes before the initialization timeout. There wasn't any log message saying when this server first synced, but I guess it did sync since it shows up ok in the debug info. I wonder if something is wrong with the latch that is used to check for initialization?

2. There is a loop in `serverInventoryInitialized` where `server.awaitInitialization()` is called for each server in a row. That means it will wait the full timeout (default 3 minutes) for each timing-out server. In my case, two different servers timed out so the broker startup took over 6 minutes. I think it'd be better for there to be an overall initialization, since with the current mechanism, in a big cluster the effective timeout could be huge.

```
2018-02-02T10:09:46,116 INFO [CuratorDruidNodeDiscoveryProvider-ListenerExecutor] io.druid.client.HttpServerInventoryView - Server[ip-172-31-0-22.ec2.internal:8303] appeared.
2018-02-02T10:09:46,116 INFO [CuratorDruidNodeDiscoveryProvider-ListenerExecutor] io.druid.server.coordination.ChangeRequestHttpSyncer - Starting ChangeRequestHttpSyncer[https://ip-172-31-0-22.ec2.internal:8303/_1517566186116].
2018-02-02T10:09:46,118 INFO [HttpServerInventoryView-3] io.druid.server.coordination.ChangeRequestHttpSyncer - Temporary Failure. failed to get sync response from [https://ip-172-31-0-22.ec2.internal:8303/_1517566186116]. Return code [0], Reason: [null]
2018-02-02T10:09:46,118 INFO [HttpServerInventoryView-3] io.druid.server.coordination.ChangeRequestHttpSyncer - Scheduling next syncup in [1349] millis for server[https://ip-172-31-0-22.ec2.internal:8303/_1517566186116].
2018-02-02T10:09:47,468 INFO [HttpServerInventoryView-2] io.druid.server.coordination.ChangeRequestHttpSyncer - Temporary Failure. failed to get sync response from [https://ip-172-31-0-22.ec2.internal:8303/_1517566186116]. Return code [0], Reason: [null]
2018-02-02T10:09:47,468 INFO [HttpServerInventoryView-2] io.druid.server.coordination.ChangeRequestHttpSyncer - Scheduling next syncup in [2198] millis for server[https://ip-172-31-0-22.ec2.internal:8303/_1517566186116].
2018-02-02T10:09:49,668 INFO [HttpServerInventoryView-0] io.druid.server.coordination.ChangeRequestHttpSyncer - Temporary Failure. failed to get sync response from [https://ip-172-31-0-22.ec2.internal:8303/_1517566186116]. Return code [0], Reason: [null]
2018-02-02T10:09:49,668 INFO [HttpServerInventoryView-0] io.druid.server.coordination.ChangeRequestHttpSyncer - Scheduling next syncup in [3055] millis for server[https://ip-172-31-0-22.ec2.internal:8303/_1517566186116].
2018-02-02T10:09:52,725 INFO [HttpServerInventoryView-2] io.druid.server.coordination.ChangeRequestHttpSyncer - Temporary Failure. failed to get sync response from [https://ip-172-31-0-22.ec2.internal:8303/_1517566186116]. Return code [0], Reason: [null]
2018-02-02T10:09:52,725 INFO [HttpServerInventoryView-2] io.druid.server.coordination.ChangeRequestHttpSyncer - Scheduling next syncup in [8645] millis for server[https://ip-172-31-0-22.ec2.internal:8303/_1517566186116].
2018-02-02T10:16:56,250 WARN [HttpServerInventoryView-1] io.druid.client.HttpServerInventoryView - Await initialization timed out for server [ip-172-31-0-22.ec2.internal:8303].
```

### PR DESCRIPTION
**Pull request by himanshug**
Fixes #5331 

@gianm this patch addresses both points discussed in https://github.com/druid-io/druid/issues/5331#issuecomment-362698337 .

Regarding,
> The adjustment to have an overall timeout of (serverTimeout + 30 seconds) sounds good. Or even just serverTimeout -- not sure that we need the extra 30s.

this patch adds a fixed upper bounded wait of `config.getServerTimeout() + 2 * ChangeRequestHttpSyncer.HTTP_TIMEOUT_EXTRA_MS` which gives each server at least one full HTTP request timeout and 5 sec buffer .

Also, made "debug-info" a bit more clearer.

### CODE REVIEW

File: server/src/main/java/io/druid/client/HttpServerInventoryView.java [hunk 1]
```diff
@@ -328,8 +331,42 @@ public void run()
...
     for (DruidServerHolder server : servers.values()) {
-      server.awaitInitialization();
+      if (!server.isSyncedSuccessfullyAtleastOnce()) {
+        uninitializedServers.add(server);
+      }
+    }
+
+    while (!uninitializedServers.isEmpty() && ((System.currentTimeMillis() - start) < serverSyncWaitTimeout)) {
+      try {
+        Thread.sleep(5000);
```
Comment (jon-wei) [inline server/src/main/java/io/druid/client/HttpServerInventoryView.java]: nit: use a constant for 5000?

Comment (himanshug) [reply server/src/main/java/io/druid/client/HttpServerInventoryView.java]: this place would be the only user of that variable. Given the context it is self explanatory so let us keep it hard coded.
