### PR TITLE
Single auth check for authorized resource filtering

### LINKED ISSUE #4813: Problem with GET on /druid/indexer/v1/supervisor
```
2017-09-16T17:10:52,782 WARN [qtp883035926-144] org.eclipse.jetty.servlet.ServletHandler - /druid/indexer/v1/supervisor
io.druid.java.util.common.ISE: Request already had authorization check.
        at io.druid.server.security.AuthorizationUtils.authorizeAllResourceActions(AuthorizationUtils.java:135) ~[druid-server-0.11.0-1505579318-d980451-48.jar:0.11.0-1505579318-d980451-48]
        at io.druid.indexing.overlord.supervisor.SupervisorResource$2.apply(SupervisorResource.java:127) ~[druid-indexing-service-0.11.0-1505579318-d980451-48.jar:0.11.0-1505579318-d980451-48]
        at io.druid.indexing.overlord.supervisor.SupervisorResource$2.apply(SupervisorResource.java:118) ~[druid-indexing-service-0.11.0-1505579318-d980451-48.jar:0.11.0-1505579318-d980451-48]
        at io.druid.indexing.overlord.supervisor.SupervisorResource.asLeaderWithSupervisorManager(SupervisorResource.java:334) ~[druid-indexing-service-0.11.0-1505579318-d980451-48.jar:0.11.0-1505579318-d980451-48]
        at io.druid.indexing.overlord.supervisor.SupervisorResource.specGetAll(SupervisorResource.java:116) ~[druid-indexing-service-0.11.0-1505579318-d980451-48.jar:0.11.0-1505579318-d980451-48]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
```

Following exception gets thrown while getting information for multiple supervisors from the endpoint `/druid/indexer/v1/supervisor`. If there are multiple supervisors then `AuthorizationUtils.authorizeAllResourceActions` will be called for them in loop [here](https://github.com/druid-io/druid/blob/master/indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorResource.java#L124), when the method is called first time for first supervisor then it will set the `request` attribute `AuthConfig.DRUID_AUTHORIZATION_CHECKED` [here](https://github.com/druid-io/druid/blob/master/server/src/main/java/io/druid/server/security/AuthorizationUtils.java#L151) and therefore from next call for remaining supervisors, above mentioned exception will be thrown.

@jon-wei Can you please check ?

### PR DESCRIPTION
**Pull request by jon-wei**
Fixes #4813 

Changes the AuthorizationUtils.filterAuthorizedResources() method and SupervisorResource to prevent multiple authorization checks being performed on requests (See https://github.com/druid-io/druid/pull/4816#pullrequestreview-63229983 for context).

### CODE REVIEW

**Comment by jon-wei** [comment]
@nishantmonu51 

Hm, I don't know how to setup tests like SupervisorResourceTest with the servlet filters that would be used in a real environment (like PreResponseAuthorizationCheckFilter), any ideas there?

File: server/src/main/java/io/druid/server/security/AuthorizationUtils.java [hunk 1]
```diff
@@ -153,25 +151,40 @@ public static Access authorizeAllResourceActions(
...
    */
-  public static <ResType> List<ResType> filterAuthorizedResources(
+  public static <ResType> void filterAuthorizedResources(
       final HttpServletRequest request,
       final Collection<ResType> resources,
-      final Function<? super ResType, ResourceAction> resourceActionGenerator,
-      final AuthorizerMapper authorizerMapper
+      final Function<? super ResType, Iterable<ResourceAction>> resourceActionGenerator,
+      final AuthorizerMapper authorizerMapper,
+      final Collection<? super ResType> filteredResources
```
Comment (gianm) [inline server/src/main/java/io/druid/server/security/AuthorizationUtils.java]: What's the reason for having an out-parameter instead of returning a `Collection<ResType>` or `Iterable<ResType>`? I'm wondering since out-params are harder to comprehend than return values.

I'm thinking that many callers would want to directly use a returned filteredResources, and for the callers that don't, they could do:

```java
Iterables.addAll(filteredResources, filterAuthorizedResources(...))`
```

File: indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorResource.java [hunk 2]
```diff
@@ -337,4 +310,44 @@ private Response asLeaderWithSupervisorManager(Function<SupervisorManager, Respo
...
+  private Set<String> filterAuthorizedSupervisorIds(
+      final HttpServletRequest req,
+      SupervisorManager manager,
+      Collection<String> supervisorIds
+  )
+  {
+    final Set<String> authorizedSupervisorIds = Sets.newHashSet();
+
+    // If there were no supervisorIds, go ahead and authorize the request.
+    if (supervisorIds.size() == 0) {
```
Comment (gianm) [inline indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorResource.java]: Is it necessary to have a separate branch for this case? Shouldn't filterAuthorizedResources on an empty list do the same thing?

File: server/src/main/java/io/druid/server/security/AuthorizationUtils.java (hunk 1 above)
Comment (jon-wei) [reply server/src/main/java/io/druid/server/security/AuthorizationUtils.java]: I have the out-parameter so that the caller can control the type of the Collection that gets the filtered values. 

I implemented that way after seeing that SupervisorResource uses Sets for storing supervisor ids, maybe a future caller really cares about using a Set to avoid duplicates, and I thought it'd be better to have the caller pass in the output collection to avoid having to create extra lists and copy them over into other structures.

File: indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorResource.java (hunk 2 above)
Comment (jon-wei) [reply indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorResource.java]: It's not, I had it there just to avoid creating the resource generating function if there were on supervisorIds, removed this

File: server/src/main/java/io/druid/server/security/AuthorizationUtils.java (hunk 1 above)
Comment (gianm) [reply server/src/main/java/io/druid/server/security/AuthorizationUtils.java]: In that case, I think it's best for filterAuthorizedResources to return an `Iterable< ResType>` (and maybe accept one as well, instead of the Collection it accepts now). There won't be any need to create useless collections since the caller can iterate the iterable and directly insert it into the target collection, using `Iterables.addAll`.

Comment (jon-wei) [reply server/src/main/java/io/druid/server/security/AuthorizationUtils.java]: alright, changed filtereAuthorizedResources to return Iterable

File: indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorResource.java [hunk 3]
```diff
@@ -239,27 +216,22 @@ public Response specGetAllHistory(@Context final HttpServletRequest req)
...
-                manager.getSupervisorHistory(),
+            final Map<String, List<VersionedSupervisorSpec>> supervisorHistory = manager.getSupervisorHistory();
+
+            final Set<String> authorizedSupervisorIds = filterAuthorizedSupervisorIds(
+                req,
+                manager,
+                supervisorHistory.keySet()
+            );
+
+            final Map<String, List<VersionedSupervisorSpec>> authorizedSupervisorHistory = Maps.filterKeys(
```
Comment (leventov) [inline indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorResource.java]: This object is unused. Something is wrong with this code.

Comment (gianm) [reply indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorResource.java]: Thanks for noticing. https://github.com/druid-io/druid/pull/5459 fixes it.

Comment (jon-wei) [reply indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorResource.java]: thanks for the catching that, opened a fix at #5460
