### PR TITLE
in segment metadata query return actual complex data type name 

### LINKED ISSUE #1365: As a Druid user I would like to be able to distinguish between hyperLogLog and aproxHistogram
When running a segmentMetadata query I get the following results back:

```
      "revenue_hist": {
        "type": "STRING",
        "size": -1,
        "cardinality": null,
        "errorMessage": "error:noSizeFn"
      },
      ...
      "unique_visitors": {
        "type": "STRING",
        "size": -1,
        "cardinality": null,
        "errorMessage": "error:noSizeFn"
      },
```

One of those columns is a hyperLogLog and the other an aproxHistogram (guess which is which).
By checking the `errorMessage == "error:noSizeFn"` (which seems to be unique to hyperLogLog and aproxHistogram columns) I can determine that both of those columns are ether hyperLogLog or aproxHistogram. I would like there to be a way to actually tell them apart without making another query.

In general it would be great to be able to see the aggregate function that rolled up the metrics.

### PR DESCRIPTION
**Pull request by himanshug**
and dont fail if size information is not available (do best effort to return whatever information is available)

Fixes #1365

### CODE REVIEW

**Comment by nishantmonu51** [comment]
Travis CI failing on SegmentMetadataQueryTest

**Comment by himanshug** [comment]
duh, .. should've run the build

**Comment by himanshug** [comment]
maybe it is not ideal to return size=0 when its unknown as we end up reporting incorrect total size then.
instead, implement ComplexMetricsSerde.inputSizeFn() correctly for various complex aggregators.

**Comment by drcrallen** [comment]
can we make size a `Long` then so that when it returns it will be blank upon `null`? Having a 0 size is misleading.

**Comment by drcrallen** [comment]
@cheddar : this is your original code, is it required to be `long` instead of `Long` for size?

**Comment by drcrallen** [comment]
nvmnd, I answered my own question. `io.druid.query.metadata.metadata.ColumnAnalysis#fold` would need changed also

**Comment by drcrallen** [comment]
and `io.druid.query.metadata.SegmentMetadataQueryRunnerFactory#createRunner`

**Comment by himanshug** [comment]
@drcrallen  I believe you're agreeing towards not giving size information if its not available, with the understanding that totalSize reported will be smaller than actual.

**Comment by drcrallen** [comment]
@himanshug Yes. And we should update the docs as such.

**Comment by drcrallen** [comment]
With the improved compression we have, I'm not even sure if this size functionality reports what its supposed to.

**Comment by drcrallen** [comment]
Ok, http://druid.io/docs/latest/SegmentMetadataQuery.html indicates `Estimated byte size for the segment columns in TSV format` Rather than "on disk size" so I think we're ok.

**Comment by xvrl** [comment]
@drcrallen @himanshug If we think of the size value as a metric, then I think it's ok to default it to zero.
Druid metrics will default to zero if there is no data for a given row, so it would be consistent with what we do for regular Druid data.

**Comment by drcrallen** [comment]
With @xvrl 's argument regarding matching metric behavior I agree this is a reasonable solution.

File: processing/src/main/java/io/druid/query/metadata/SegmentAnalyzer.java [hunk 1]
```diff
@@ -152,6 +152,6 @@ public ColumnAnalysis analyzeComplexColumn(Column column)
       size += inputSizeFn.apply(complexColumn.getRowValue(i));
     }
 
-    return new ColumnAnalysis(capabilities.getType().name(), size, null, null);
+    return new ColumnAnalysis(typeName, size, null, null);
```
Comment (drcrallen) [inline processing/src/main/java/io/druid/query/metadata/SegmentAnalyzer.java]: Did this need to change as well? or was this a "hey, why don't I fix this while I'm here" kind of thing?

Comment (himanshug) [inline processing/src/main/java/io/druid/query/metadata/SegmentAnalyzer.java]: yes this is required so that it says "hyperUnique" instead of "COMPLEX"  in case of complex aggregations. that is what the issue being solved really wants.

**Comment by himanshug** [comment]
@xvrl @drcrallen ok, it seems defaulting size to 0 is ok, let me update the docs then.

File: processing/src/main/java/io/druid/query/metadata/SegmentAnalyzer.java (hunk 1 above)
Comment (drcrallen) [inline processing/src/main/java/io/druid/query/metadata/SegmentAnalyzer.java]: Gotcha! thanks

**Comment by himanshug** [comment]
@xvrl ready to merge.
