### PR TITLE
DruidLeaderClient: Throw IOException on retryable errors.

### LINKED ISSUE #4911: [0.11] ISE in DruidLeaderClient foils RTAC retries
RemoteTaskActionClient is built to retry any IOExceptions or ChannelExceptions, but consider other exceptions as fatal and give up. Generally, this will bubble up and fail the task as well.

DruidLeaderClient (introduced in 0.11.0) will however throw ISE for some things that should be IOExceptions, such as `ISE("Couldn't find any servers.")` in `pickOneHost()`. It causes tasks to fail when a leader briefly goes offline, when they really should just retry.

### PR DESCRIPTION
**Pull request by gianm**
Fixes #4911.

### CODE REVIEW

**Comment by himanshug** [comment]
i was doing it but you're too quick :)

**Comment by himanshug** [comment]
can you add `ChannelException` to catch list at https://github.com/druid-io/druid/blob/master/server/src/main/java/io/druid/discovery/DruidLeaderClient.java#L131 too ?

**Comment by himanshug** [comment]
also, please change https://github.com/druid-io/druid/blob/master/server/src/main/java/io/druid/discovery/DruidLeaderClient.java#L58 `MAX_RETRIES` to `5` so that it tries to follow 4 redirects just in case before giving up.

File: server/src/main/java/io/druid/discovery/DruidLeaderClient.java [hunk 1]
```diff
@@ -221,14 +232,21 @@ public String findCurrentLeader()
...
+  private String getCurrentKnownLeader(final boolean cached) throws IOException
   {
-    return currentKnownLeader.accumulateAndGet(
+    final String leader = currentKnownLeader.accumulateAndGet(
         null,
         (current, given) -> current == null || !cached ? pickOneHost() : current
     );
+
+    if (leader == null) {
+      throw new IOE("No known leader");
```
Comment (himanshug) [inline server/src/main/java/io/druid/discovery/DruidLeaderClient.java]: "No known server" . `pickOneHost()` is only supposed to find a server not necessarily leader... it is finding leader now only because of we're keeping ServerDiscoverySelector for backward compatibility. that would be removed in next release and then it would only rely upon the list of available overlord/coordinator servers in `internal-discovery`

Comment (gianm) [reply server/src/main/java/io/druid/discovery/DruidLeaderClient.java]: Ah, okay, changed it.

**Comment by gianm** [comment]
@himanshug I made the changes you suggested, and also added unwrapping of ChannelExceptions and IOExceptions (moved that from RTAC to DLC).

**Comment by himanshug** [comment]
@gianm thanks
