### PR TITLE
Fix Query metrics for query timeout

### LINKED ISSUE #2070: Query Resource does not emit query/time for failed/timeout queries
QueryResource does not emit any request/time for queries which timeout or fail. 
This leads to druid metrics show better query times than what the user actually sees and needs to be fixed.

### PR DESCRIPTION
**Pull request by nishantmonu51**
This PR has these changes - 
1) Adds query/time to request log metrics emitted for timed-out/interrupted. Fixes #2070 
2) Adds a new flag success to query/time metrics and emit query/time for timed-out/interrupted queries also. 
2) Fixes the success flag for metrics emitted by router. Add a check for the status of response.

### CODE REVIEW

**Comment by fjy** [comment]
@nishantmonu51 can you pull from master to fix the transient failures?

File: server/src/main/java/io/druid/server/AsyncQueryForwardingServlet.java [hunk 1]
```diff
@@ -321,7 +321,7 @@ public void onComplete(Result result)
                         "query/time",
                         requestTime,
                         "success",
-                        result.isSucceeded()
+                        result.isSucceeded() && result.getResponse().getStatus() == 200
```
Comment (himanshug) [inline server/src/main/java/io/druid/server/AsyncQueryForwardingServlet.java]: why this changed? also can you use some existing static variable from http libs instead of 200?

**Comment by himanshug** [comment]
you probably need to rebase against master due to https://github.com/druid-io/druid/pull/2150 , I'm surprised that this is not showing a merge conflict.

File: server/src/main/java/io/druid/server/AsyncQueryForwardingServlet.java (hunk 1 above)
Comment (nishantmonu51) [inline server/src/main/java/io/druid/server/AsyncQueryForwardingServlet.java]: It was a bug, isSucceeded only returns false when there is an error in processing the async request, in case of timeouts the broker returns a successful response with status set to INTERNAL_SERVER_ERROR i.e 500. 

have modified to use static variable.

**Comment by nishantmonu51** [comment]
rebased, dint got any merge conflicts.

**Comment by fjy** [comment]
:+1:
