### PR TITLE
fix misleading error log due to race in RTR and concurrency test

### LINKED ISSUE #2842: NPE in RTR with multiple threads for task assignment
Multiple threads in task assignment causes NPE. 
Seems to have been introduced by https://github.com/druid-io/druid/pull/2521
```
2016-04-15T09:56:11,335 ERROR [rtr-pending-tasks-runner-2] io.druid.indexing.overlord.RemoteTaskRunner - Exception while trying to assign task: {class=io.druid.indexing.overlord.RemoteTask
Runner, exceptionType=class java.lang.NullPointerException, exceptionMessage=task, taskId=<TASKID>}
java.lang.NullPointerException: task
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[druid-selfcontained-7aaf2b3.jar:7aaf2b3]
        at io.druid.indexing.overlord.RemoteTaskRunner.tryAssignTask(RemoteTaskRunner.java:638) ~[druid-selfcontained-7aaf2b3.jar:7aaf2b3]
        at io.druid.indexing.overlord.RemoteTaskRunner.access$1400(RemoteTaskRunner.java:116) ~[druid-selfcontained-7aaf2b3.jar:7aaf2b3]
        at io.druid.indexing.overlord.RemoteTaskRunner$3.call(RemoteTaskRunner.java:568) [druid-selfcontained-7aaf2b3.jar:7aaf2b3]
        at io.druid.indexing.overlord.RemoteTaskRunner$3.call(RemoteTaskRunner.java:556) [druid-selfcontained-7aaf2b3.jar:7aaf2b3]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
2016-04-15T09:56:11,336 ERROR [rtr-pending-tasks-runner-2] io.druid.indexing.overlord.RemoteTaskRunner - Exception in running pending tasks: {class=io.druid.indexing.overlord.RemoteTaskRun
ner, exceptionType=class java.lang.NullPointerException, exceptionMessage=taskRunnerWorkItem}
java.lang.NullPointerException: taskRunnerWorkItem
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[druid-selfcontained-7aaf2b3.jar:7aaf2b3]
        at io.druid.indexing.overlord.RemoteTaskRunner.taskComplete(RemoteTaskRunner.java:1048) ~[druid-selfcontained-7aaf2b3.jar:7aaf2b3]
        at io.druid.indexing.overlord.RemoteTaskRunner.access$1500(RemoteTaskRunner.java:116) ~[druid-selfcontained-7aaf2b3.jar:7aaf2b3]
        at io.druid.indexing.overlord.RemoteTaskRunner$3.call(RemoteTaskRunner.java:577) [druid-selfcontained-7aaf2b3.jar:7aaf2b3]
        at io.druid.indexing.overlord.RemoteTaskRunner$3.call(RemoteTaskRunner.java:556) [druid-selfcontained-7aaf2b3.jar:7aaf2b3]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
```

### PR DESCRIPTION
**Pull request by himanshug**
fixes #2842 

also refactored RemoteTaskRunnerTest.java a little to write new concurrency test

### CODE REVIEW

File: indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java [hunk 1]
```diff
@@ -697,22 +704,38 @@ public ImmutableWorkerInfo transformEntry(
...
       }
       finally {
         if (assignedWorker != null) {
           workersWithUnacknowledgedTask.remove(assignedWorker.getWorker().getHost());
-          // note that this is essential as a task might not get a worker because a worker was assigned another task.
-          // so this will ensure that other pending tasks are tried for assignment again.
+        }
+
+        if(immutableZkWorker.isPresent()) {
+          //if this task lost the race to run the task then there might be another worker available to try on.
```
Comment (nishantmonu51) [inline indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java]: should it be if this worker lost the race to run the task ?

File: indexing-service/src/test/java/io/druid/indexing/overlord/RemoteTaskRunnerRunPendingTasksConcurrencyTest.java [hunk 2]
```diff
@@ -0,0 +1,150 @@
...
+  {
+    if (remoteTaskRunner != null) {
+      remoteTaskRunner.stop();
+    }
+    rtrTestUtils.tearDown();
+  }
+
+  // This task reproduces the races described in https://github.com/druid-io/druid/issues/2842
+  @Test(timeout = 90_000)
+  public void testConcurrency() throws Exception
```
Comment (nishantmonu51) [inline indexing-service/src/test/java/io/druid/indexing/overlord/RemoteTaskRunnerRunPendingTasksConcurrencyTest.java]: how much time does this test takes to complete ?
there are thread.sleep in this test, is there any way we can use barriers or latches instead of sleep ?

File: indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java (hunk 1 above)
Comment (himanshug) [inline indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java]: changed to `if this attempt lost the...`

File: indexing-service/src/test/java/io/druid/indexing/overlord/RemoteTaskRunnerRunPendingTasksConcurrencyTest.java (hunk 2 above)
Comment (himanshug) [inline indexing-service/src/test/java/io/druid/indexing/overlord/RemoteTaskRunnerRunPendingTasksConcurrencyTest.java]: it takes anywhere from 1500ms to 2500 ms
changed test level timeout to more traditional 60k.

in this case most of the things are encapsulated by RTR and very hard to deterministically test those races and harder to do so with latches.

**Comment by nishantmonu51** [comment]
👍

**Comment by fjy** [comment]
👍
