### PR TITLE
Ensure unique names for aggregators / post-aggregators + optimize groupBy post-aggregators

### LINKED ISSUE #1045: GroupBy with complex metrics fails if there is a post-aggregator with the same name
See #1044 for unit tests catching this bug.

### PR DESCRIPTION
**Pull request by xvrl**
- Ensure names for aggregators and post-aggregators are unique
- Fixes #1045 by not allowing the same name for both post-aggregators and aggregators
- Optimizes post-aggregator calculation for groupBy

### CODE REVIEW

**Comment by drcrallen** [comment]
Fixes #1045 via https://github.com/metamx/druid/commit/60e065db5be152c1f6674322e3e032df16018341

**Comment by nishantmonu51** [comment]
+1

**Comment by drcrallen** [comment]
@xvrl : can this be a 0.7.1 fix?

**Comment by xvrl** [comment]
yup, added it to 0.7.1

**Comment by fjy** [comment]
Can I propose a simpler fix of just throwing a meaningful exception when agg/postagg match?

**Comment by drcrallen** [comment]
@fjy : That is possible, but be aware that the current proposed fix overwrites the prior values with new ones. This means that if someone has complex aggregations and some other post-aggregations, the post aggs will overwrite the aggregators in the results set, this saves on ser/de when sending back to the client.

**Comment by fjy** [comment]
@cheddar @himanshug @xvrl Any thoughts on this one? In particular with my last set of comments.

**Comment by himanshug** [comment]
I think I agree with @fjy in keeping it simple and just not allowing aggregator and post-aggregator of same names. Semantics are then simpler to understand/explain.

@drcrallen savings on serde, if required, can be attained by fixing #688

**Comment by drcrallen** [comment]
@cheddar  / @fjy  / @himanshug / @xvrl 
This changes behavior of the query engine and could break existing queries, but now implements the behavior as suggested by @fjy  / @himanshug

File: extensions/histogram/src/test/java/io/druid/query/aggregation/histogram/ApproximateHistogramGroupByQueryTest.java [hunk 1]
```diff
@@ -214,4 +214,64 @@ public void testGroupByWithApproximateHistogramAgg()
     Iterable<Row> results = GroupByQueryRunnerTestHelper.runQuery(factory, runner, query);
     TestHelper.assertExpectedObjects(expectedResults, results, "approx-histo");
   }
+
+  @Test(expected = java.lang.IllegalArgumentException.class)
```
Comment (himanshug) [inline extensions/histogram/src/test/java/io/druid/query/aggregation/histogram/ApproximateHistogramGroupByQueryTest.java]: minor nit,  but java.lang isn't really required.

**Comment by himanshug** [comment]
LGTM besides the minor comment.

File: extensions/histogram/src/test/java/io/druid/query/aggregation/histogram/ApproximateHistogramGroupByQueryTest.java (hunk 1 above)
Comment (drcrallen) [inline extensions/histogram/src/test/java/io/druid/query/aggregation/histogram/ApproximateHistogramGroupByQueryTest.java]: Fixed, and in 1 other spot.

**Comment by drcrallen** [comment]
To be clear, the "fix" for the issue is still in the PR, so the underlying logic *can* support group by queries where the aggregate and post aggregate are named the same but now they simply refuse to.

File: processing/src/main/java/io/druid/query/Queries.java [hunk 2]
```diff
@@ -64,6 +68,40 @@ public String apply(AggregatorFactory input)
         );
         combinedAggNames.add(postAgg.getName());
       }
+
+      final Collection<String> aggAndPostAgg = Sets.intersection(
+          Sets.<String>newHashSet(
```
Comment (xvrl) [inline processing/src/main/java/io/druid/query/Queries.java]: isn't this the same as combinedAggNames?

Comment (xvrl) [inline processing/src/main/java/io/druid/query/Queries.java]: the initial value I mean

File: processing/src/main/java/io/druid/query/Queries.java [hunk 3]
```diff
@@ -64,6 +68,40 @@ public String apply(AggregatorFactory input)
         );
         combinedAggNames.add(postAgg.getName());
```
Comment (xvrl) [inline processing/src/main/java/io/druid/query/Queries.java]: why not do the check for post-aggregators naming here, before adding it to combinedAggNames?

Comment (drcrallen) [inline processing/src/main/java/io/druid/query/Queries.java]: Modified it a bit. I can actually do the check as a feature of `Set.add` (see code)

File: processing/src/main/java/io/druid/query/Queries.java (hunk 2 above)
Comment (drcrallen) [inline processing/src/main/java/io/druid/query/Queries.java]: Yes, I had originally taken this as a separate group of code to separate functionality, but it actually doesn't look too bad when I put them in the same logic area.

**Comment by drcrallen** [comment]
Modified this a little to also do the same check for aggregators (that aggregator names must be unique)

File: processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java [hunk 4]
```diff
@@ -231,6 +263,45 @@ private IncrementalIndex makeIncrementalIndex(GroupByQuery query, Sequence<Row>
...
+      @Override
+      public Row apply(Row input)
+      {
+        if (!(input instanceof MapBasedRow)) {
+          return input;
+        }
+        final MapBasedRow inputRow = (MapBasedRow) input;
+        final Map<String, Object> values = Maps.newHashMap(inputRow.getEvent());
+        for (AggregatorFactory agg : query.getAggregatorSpecs()) {
+          if (postNames.contains(agg.getName())) {
```
Comment (xvrl) [inline processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java]: we can remove this since we don't allow same names.

File: processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java [hunk 5]
```diff
@@ -231,6 +263,45 @@ private IncrementalIndex makeIncrementalIndex(GroupByQuery query, Sequence<Row>
...
+            }
+        )
+    );
+    return new Function<Row, Row>()
+    {
+      @Nullable
+      @Override
+      public Row apply(Row input)
+      {
+        if (!(input instanceof MapBasedRow)) {
```
Comment (xvrl) [inline processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java]: do we need to compute post-aggregators for Row other than MapBasedRow?

File: processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java [hunk 6]
```diff
@@ -168,7 +179,28 @@ public GroupByQueryQueryToolChest(
...
+          query, runner.run(
+              new GroupByQuery(
+                  query.getDataSource(),
+                  query.getQuerySegmentSpec(),
+                  query.getDimFilter(),
+                  query.getGranularity(),
+                  query.getDimensions(),
+                  query.getAggregatorSpecs(),
+                  // Don't do post aggs until the end of this method. ISSUE #1045
+                  ImmutableList.<PostAggregator>of(),
```
Comment (xvrl) [inline processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java]: this comment is probably misleading now, since this is more of an optimization rather than fixing a bug now.

File: processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java (hunk 5 above)
Comment (drcrallen) [inline processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java]: Good question, the default behavior is to use the preComputeManipulatorFn, which also only computes for MapBasedRow. I couldn't tell you why that is. This function is a copy of the pre function

File: processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java (hunk 6 above)
Comment (drcrallen) [inline processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java]: Fixed

File: processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java (hunk 4 above)
Comment (drcrallen) [inline processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java]: Defaulted to pre-PR behavior for this.

File: processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java (hunk 5 above)
Comment (drcrallen) [inline processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java]: Went back to pre-PR behavior for this.

File: processing/src/test/java/io/druid/query/groupby/GroupByQueryRunnerTest.java [hunk 7]
```diff
@@ -1152,6 +1191,62 @@ public void testGroupByWithOrderLimit4()
   }
 
   @Test
+  public void testPostAggHavingSpec()
```
Comment (xvrl) [inline processing/src/test/java/io/druid/query/groupby/GroupByQueryRunnerTest.java]: this only tests post-aggregators in the context of merging results.
Can we add a separate one that does it without merging, i.e. that checks the results of GroupByQueryRunnerTestHelper.runQuery directly?

Comment (drcrallen) [inline processing/src/test/java/io/druid/query/groupby/GroupByQueryRunnerTest.java]: Added
