### PR TITLE
fix #1727 - Union bySegment queries fix

### LINKED ISSUE #1727: Union bySegment queries can get confused about which descriptors to use
When historicals get a union query with multiple datasources, they can get confused and scan segments other than the ones the broker intended. This is because they use ```UnionTimeLineLookup.findEntry(interval, version)``` to resolve the descriptors into Segments, but it's possible for segments in different datasources to have the same interval and version. This is actually always going to happen if the datasources were ingested with standalone realtime, since the version is fixed to the start of the hour.

This shows a couple of union queries where one segment is scanned twice and one is not scanned at all (which one is scanned depends on the order of the datasources; see union.json vs union2.json): https://gist.github.com/gianm/fc3a1eba0dbafbf87720

### PR DESCRIPTION
**Pull request by nishantmonu51**
Fixes https://github.com/druid-io/druid/issues/1727
revert to doing merging for results for union queries on broker.
Historical node will throw Unsupported Exception for Union Queries sent directly to it.

### CODE REVIEW

**Comment by xvrl** [comment]
@nishantmonu51 I think you mean to say fix #1727, not 1721

**Comment by nishantmonu51** [comment]
Ah, updated the commit message and PR description to have correct message.

**Comment by drcrallen** [comment]
weird failure on that one:

```AnnouncerTest.testSessionKilled:157 expected null, but was:<10,10,1442324913450,1442324913450,0,0,0,94524205367558145,25,0,10>```

File: integration-tests/src/main/java/io/druid/testing/clients/EventReceiverFirehoseTestClient.java [hunk 1]
```diff
@@ -150,12 +151,12 @@ public int postEventsFromFile(String file)
                            ? MediaType.APPLICATION_JSON
                            : SmileMediaTypes.APPLICATION_JACKSON_SMILE;
         totalEventsPosted += postEvents(events, mapper, mediaType);
-        ;
+        expectedEvents += events.size();
```
Comment (gianm) [inline integration-tests/src/main/java/io/druid/testing/clients/EventReceiverFirehoseTestClient.java]: Is this related to the rest of the PR?

Comment (nishantmonu51) [inline integration-tests/src/main/java/io/druid/testing/clients/EventReceiverFirehoseTestClient.java]: not related to this PR, it was an integration-test issue, that popped up when i tried to run integration-tests. will separate test fix in a separate PR.

**Comment by gianm** [comment]
Looks good although is it possible to add a regression test?

**Comment by nishantmonu51** [comment]
@gianm cant add test for the exact same bug since it was in the code path that is now removed. 
Added test fr UnionQuery runner that verifies its functionality.

**Comment by xvrl** [comment]
@nishantmonu51 looks like one of the unit test is actually failing

**Comment by nishantmonu51** [comment]
Ah, i screwed up while squashing commits for a renamed file, should be fixed now.

**Comment by fjy** [comment]
:+1:

**Comment by drcrallen** [comment]
In a world where I have only one broker and one historical, the desired behavior is that if I submit a query to the broker I get the same result as if I submit it to the historical. Does this break that behavior?

**Comment by nishantmonu51** [comment]
After this change, historical nodes will not be aware of how to run union queries. 
you will need to send the query to broker always. 
there are alternative approaches where we can make this working for historical nodes too. (discussed here - https://github.com/druid-io/druid/issues/1727)

**Comment by drcrallen** [comment]
Can you update the docs for http://druid.io/docs/latest/querying/datasource.html to indicate the limitations of the Union Query being issued against a broker?

**Comment by cheddar** [comment]
We talked about this in the dev sync and while it is unfortunate that historicals won't know about the Union query, it is probably the least of evils at this point in time, so I'm :+1: on that aspect (haven't actually verified the code)

Can we update this PR to have a more meaningful name though? ;)

**Comment by nishantmonu51** [comment]
updated the docs and the PR name.

**Comment by drcrallen** [comment]
Encountered error during rollout internally related to historicals getting union queries. Investigating more, but this might require BROKERs to be updated before HISTORICALs for 0.8.2
