### PR TITLE
groupBy nested query using v2 strategy

### LINKED ISSUE #3239: Nested groupBy query fails when outer query has aggregator with dimension field
Javascript and Cardinality aggregators allows dimensions as fieldNames. Exceptions are thrown when these aggregators are used in outer queries with dimensions fields in fieldNames.

Javascript query:
```
{
  "queryType" : "groupBy",
  "dataSource" : {
    "type": "query",
    "query": {
      "queryType": "groupBy",
      "dataSource" : "wikiticker",
      "intervals" : ["2015-09-12T00:00:00.000/2015-09-12T08:00:00.000"],
      "granularity" : "hour",
      "dimensions" : ["isAnonymous", "countryName"],
      "aggregations": [{ "type": "longSum", "name": "count", "fieldName": "count" }]
    }
  },
  "intervals" : ["2015-09-12T00:00:00.000/2015-09-12T08:00:00.000"],
  "granularity" : "hour",
  "dimensions" : ["isAnonymous"],
  "aggregations" : [
    {
      "type" : "javascript",
      "name": "outerjs",
      "fieldNames": ["count", "countryName"],
      "fnAggregate" : "function(current, index, dim){if (dim != null) {return current + index + dim.length;} else {return current + index;}}",
      "fnCombine"   : "function(partialA, partialB) { return partialA + partialB; }",
      "fnReset"     : "function()                   { return 0; }"
    }
  ]
}
```
Exception
```
com.metamx.common.parsers.ParseException: Unable to parse value[Pakistan] as float in column: countryName
	at io.druid.segment.incremental.IncrementalIndex.getRowDimensionAsComparables(IncrementalIndex.java:544) ~[druid-processing-0.9.2-SNAPSHOT.jar:0.9.2-SNAPSHOT]
	at io.druid.segment.incremental.IncrementalIndex.toTimeAndDims(IncrementalIndex.java:615) ~[druid-processing-0.9.2-SNAPSHOT.jar:0.9.2-SNAPSHOT]
	at io.druid.segment.incremental.IncrementalIndex.add(IncrementalIndex.java:567) ~[druid-processing-0.9.2-SNAPSHOT.jar:0.9.2-SNAPSHOT]

```
Cardinality query:
```
{
  "queryType" : "groupBy",
  "dataSource" : {
    "type": "query",
    "query": {
      "queryType": "groupBy",
      "dataSource" : "wikiticker",
      "intervals" : ["2015-09-12T00:00:00.000/2015-09-12T08:00:00.000"],
      "granularity" : "hour",
      "dimensions" : ["isAnonymous", "countryName"],
      "aggregations": [{ "type": "longSum", "name": "count", "fieldName": "count" }]
    }
  },
  "intervals" : ["2015-09-12T00:00:00.000/2015-09-12T08:00:00.000"],
  "granularity" : "hour",
  "dimensions" : ["isAnonymous"],
  "aggregations" : [
    {
      "type" : "cardinality",
      "name": "outercar",
      "fieldNames": ["isAnonymous", "countryName"]
    }
  ]
}
```
Exception
```
java.lang.NullPointerException
	at io.druid.segment.incremental.IncrementalIndex.getRowDimensionAsComparables(IncrementalIndex.java:540) ~[druid-processing-0.9.2-SNAPSHOT.jar:0.9.2-SNAPSHOT]
	at io.druid.segment.incremental.IncrementalIndex.toTimeAndDims(IncrementalIndex.java:615) ~[druid-processing-0.9.2-SNAPSHOT.jar:0.9.2-SNAPSHOT]
	at io.druid.segment.incremental.IncrementalIndex.add(IncrementalIndex.java:567) ~[druid-processing-0.9.2-SNAPSHOT.jar:0.9.2-SNAPSHOT]

```

This problem happens because when building the incremental index from the subquery result, agg.getRequiredColumns() would includes aggregators with the same name as dimensions. 

The exception occurs when converting the dimensions object using value type associated with the dimension name, which in this case is actually the aggregator value type. For javascript aggregator, the type is float so it attempted to convert dimension to float, while for cardinality aggregator, the type is hyperUnique, and no converter is found for complex type.

### PR DESCRIPTION
**Pull request by acslk**
This PR changes the way v2 groupBy strategy process outer query using the result of inner query as datasource, addressing #3246. 

v1 groupBy strategy will use the same approach as before, by building an IncrementalIndex of inner query result, then use the query engine to process each interval on the built inner IncrementalIndex, and build an outer IncrementalIndex to merge the results.

v2 groupBy strategy will process the inner query results directly using a combined approach of process and merge with the v2 Grouper.

This change also fixes #3239 for v2 since AggregatorFactory.getRequiredColumn() is no longer used.

### CODE REVIEW

**Comment by fjy** [comment]
@acslk we won't need incremental index for groupBy after this right?

**Comment by acslk** [comment]
@fjy the v2 nested query doesn't need incremental anymore. I don't believe incremental index was used anywhere else for v2, so yeah.

**Comment by gianm** [comment]
@acslk Could you please include a test for the bug in #3239? Since I guess it'll still fail for v1, we could have the test expect a failure for v1 and a pass for v2. (along with a comment explaining what's going on)

See `GroupByQueryRunnerTest.testGroupByMaxRowsLimitContextOverrid` for an example of another test that works like that.

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByRowProcessor.java [hunk 1]
```diff
@@ -0,0 +1,460 @@
...
+        @Override
+        public boolean matches()
+        {
+          return row.getDimension(dimension).contains(value);
+        }
+      };
+    }
+
+    @Override
+    public ValueMatcher makeValueMatcher(final String dimension, final Predicate predicate)
```
Comment (jon-wei) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByRowProcessor.java]: The ValueMatcher interface has changed recently (accepts PredicateFactory instead of Predicate) now, e.g.:
https://github.com/jon-wei/druid/commit/a42ccb6d19997bb67622e0444ca564e974ddf24c#diff-d1a16d55a6958b521dc7517b7847f348R719

**Comment by acslk** [comment]
Some benchmarks:

basic groupBy query:
```
Benchmark                                     (defaultStrategy)  (initialBuckets)  (numProcessingThreads)  (numSegments)  (rowsPerSegment)  (schemaAndQuery)  Mode  Cnt       Score       Error  Units
GroupByBenchmark.queryMultiQueryableIndex                    v1                -1                       4              4            100000           basic.A  avgt   25  377404.567 ± 12965.980  us/op
GroupByBenchmark.queryMultiQueryableIndex                    v2                -1                       4              4            100000           basic.A  avgt   25  123248.725 ±  2217.685  us/op
GroupByBenchmark.querySingleIncrementalIndex                 v1                -1                       4              4            100000           basic.A  avgt   25  246516.135 ±  8189.603  us/op
GroupByBenchmark.querySingleIncrementalIndex                 v2                -1                       4              4            100000           basic.A  avgt   25   65689.103 ±  2379.866  us/op
GroupByBenchmark.querySingleQueryableIndex                   v1                -1                       4              4            100000           basic.A  avgt   25  205624.715 ±  9910.958  us/op
GroupByBenchmark.querySingleQueryableIndex                   v2                -1                       4              4            100000           basic.A  avgt   25   41422.967 ±  2396.144  us/op
```
nested groupBy query on master:
```
Benchmark                                     (defaultStrategy)  (initialBuckets)  (numProcessingThreads)  (numSegments)  (rowsPerSegment)  (schemaAndQuery)  Mode  Cnt       Score       Error  Units
GroupByBenchmark.queryMultiQueryableIndex                    v1                -1                       4              4            100000          nested.A  avgt   25  422383.160 ± 17237.959  us/op
GroupByBenchmark.queryMultiQueryableIndex                    v2                -1                       4              4            100000          nested.A  avgt   25  208302.359 ±  5632.006  us/op
GroupByBenchmark.querySingleIncrementalIndex                 v1                -1                       4              4            100000          nested.A  avgt   25  296041.435 ± 14012.584  us/op
GroupByBenchmark.querySingleIncrementalIndex                 v2                -1                       4              4            100000          nested.A  avgt   25  265163.983 ±  6364.364  us/op
GroupByBenchmark.querySingleQueryableIndex                   v1                -1                       4              4            100000          nested.A  avgt   25  255939.918 ± 14872.745  us/op
GroupByBenchmark.querySingleQueryableIndex                   v2                -1                       4              4            100000          nested.A  avgt   25  265171.625 ± 13430.492  us/op
```
nested groupBy query on patch:
```
Benchmark                                     (defaultStrategy)  (initialBuckets)  (numProcessingThreads)  (numSegments)  (rowsPerSegment)  (schemaAndQuery)  Mode  Cnt       Score       Error  Units
GroupByBenchmark.queryMultiQueryableIndex                    v1                -1                       4              4            100000          nested.A  avgt   25  419281.432 ± 16808.199  us/op
GroupByBenchmark.queryMultiQueryableIndex                    v2                -1                       4              4            100000          nested.A  avgt   25  177766.921 ±  3032.577  us/op
GroupByBenchmark.querySingleIncrementalIndex                 v1                -1                       4              4            100000          nested.A  avgt   25  291045.426 ± 16448.389  us/op
GroupByBenchmark.querySingleIncrementalIndex                 v2                -1                       4              4            100000          nested.A  avgt   25   77774.245 ±  4433.090  us/op
GroupByBenchmark.querySingleQueryableIndex                   v1                -1                       4              4            100000          nested.A  avgt   25  246214.304 ±  4907.190  us/op
GroupByBenchmark.querySingleQueryableIndex                   v2                -1                       4              4            100000          nested.A  avgt   25   54673.400 ±  4017.427  us/op
```

File: processing/src/main/java/io/druid/query/NoopQueryRunner.java [hunk 2]
```diff
@@ -28,9 +28,19 @@
 */
 public class NoopQueryRunner<T> implements QueryRunner<T>
 {
+  private final Sequence<T> results;
+
+  public NoopQueryRunner() {
+    results = Sequences.empty();
+  }
+
+  public NoopQueryRunner(Sequence<T> results) {
```
Comment (gianm) [inline processing/src/main/java/io/druid/query/NoopQueryRunner.java]: This isn't very noop-y… it actually does something!

IMO this could be an anonymous query runner defined where you're using it, or a query runner named something like `FixedSequenceQueryRunner` if it needs to have a name.

Comment (acslk) [inline processing/src/main/java/io/druid/query/NoopQueryRunner.java]: changed it to anonymous query runner

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByRowProcessor.java [hunk 3]
```diff
@@ -434,34 +446,63 @@ public void setRow(Row row)
...
     {
-      return new ValueMatcher()
-      {
-        Predicate<String> predicate = predicateFactory.makeStringPredicate();
-        @Override
-        public boolean matches()
+      if (dimension.equals(Column.TIME_COLUMN_NAME)) {
+        return new ValueMatcher()
+        {
+          DruidLongPredicate predicate = predicateFactory.makeLongPredicate();
```
Comment (jon-wei) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByRowProcessor.java]: Let's make the predicate `final`

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByRowProcessor.java [hunk 4]
```diff
@@ -434,34 +446,63 @@ public void setRow(Row row)
...
+          }
+        };
+      } else {
+        return new ValueMatcher()
         {
-          List<String> values = row.getDimension(dimension);
-          for (String value : values) {
-            if (predicate.apply(value)) {
-              return true;
+          Predicate<String> predicate = predicateFactory.makeStringPredicate();
```
Comment (jon-wei) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByRowProcessor.java]: Same `final` comment here as well

File: benchmarks/src/main/java/io/druid/benchmark/query/GroupByBenchmark.java [hunk 5]
```diff
@@ -116,7 +116,7 @@
   @Param({"100000"})
   private int rowsPerSegment;
 
-  @Param({"basic.A"})
+  @Param({"nested.A"})
```
Comment (jon-wei) [inline benchmarks/src/main/java/io/druid/benchmark/query/GroupByBenchmark.java]: This will disable the "basic.A" query and schema from running, you can enable them both:

@Param({"basic.A", "nested.A"})

File: benchmarks/src/main/java/io/druid/benchmark/query/GroupByBenchmark.java [hunk 6]
```diff
@@ -190,7 +190,47 @@ private void setupQueries()
...
+          .setDimensions(Lists.<DimensionSpec>newArrayList(
+              new DefaultDimensionSpec("dimSequential", null)
+          ))
+          .setAggregatorSpecs(
+              queryAggs
+          )
+          .setGranularity(QueryGranularities.WEEK)
+          .build();
+
+      nestedQueries.put("A", queryA);
```
Comment (jon-wei) [inline benchmarks/src/main/java/io/druid/benchmark/query/GroupByBenchmark.java]: continuing from the comment above, this should be something like ```basicQueries.put("nested", queryA)```

File: benchmarks/src/main/java/io/druid/benchmark/datagen/BenchmarkSchemas.java [hunk 7]
```diff
@@ -92,5 +92,6 @@
         basicSchemaDataInterval
     );
     SCHEMA_MAP.put("basic", basicSchema);
+    SCHEMA_MAP.put("nested", basicSchema);
```
Comment (jon-wei) [inline benchmarks/src/main/java/io/druid/benchmark/datagen/BenchmarkSchemas.java]: you can remove this after moving "nested" to be a query under the "basic" schema

File: benchmarks/src/main/java/io/druid/benchmark/query/GroupByBenchmark.java (hunk 6 above)
Comment (acslk) [inline benchmarks/src/main/java/io/druid/benchmark/query/GroupByBenchmark.java]: The current way result in Param({"basic.A", "nested.A"}), if nested is put into basicQueries, it would be  Param({"basic.A", "basic.nested"}). Which structure do you think is more reasonable?

Comment (jon-wei) [inline benchmarks/src/main/java/io/druid/benchmark/query/GroupByBenchmark.java]: Let's go with ```{"basic.A", "basic.nested"}```

**Comment by jon-wei** [comment]
:+1:

**Comment by gianm** [comment]
@acslk please also update groupbyquery.md describing how nested queries are done (see the "Implementation details" section)

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByRowProcessor.java [hunk 8]
```diff
@@ -0,0 +1,508 @@
...
+import java.io.File;
+import java.io.IOException;
+import java.nio.ByteBuffer;
+import java.util.ArrayList;
+import java.util.Iterator;
+import java.util.List;
+import java.util.Map;
+import java.util.UUID;
+
+public class GroupByRowProcessor
```
Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByRowProcessor.java]: This and GroupByMergingQueryRunnerV2 should be sharing code if at all possible. Is there any reason they can't?

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByRowProcessor.java [hunk 9]
```diff
@@ -0,0 +1,508 @@
...
+    }
+
+    private DimensionSelector makeDimensionSelectorUndecorated(
+        DimensionSpec dimensionSpec
+    )
+    {
+      final String dimension = dimensionSpec.getDimension();
+      final ExtractionFn extractionFn = dimensionSpec.getExtractionFn();
+
+      return new DimensionSelector()
```
Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByRowProcessor.java]: This kind of dimensionSelector will make some aggregators not work properly, like Filtered. That's probably fine for now, but we should have a failing test and a follow up issue for fixing it.

Possible fixes might be:

- Making this DimensionSelector's ids be global instead of per-row (the assumption that the filtered agg depends on)
- Modify the DimensionSelector interface itself so it can inform callers if the column is really dictionary backed or not. Aggregators and filters would do different behavior on columns that aren't dictionary backed.

I think I like the second one.

Comment (acslk) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByRowProcessor.java]: Added a failing test for outer filter aggregator, I'll open an issue for it after this PR gets merged.

**Comment by gianm** [comment]
@acslk there's a compilation error:

```
[ERROR] /home/travis/build/druid-io/druid/processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByRowProcessor.java:[222,26] cannot infer type arguments for io.druid.query.groupby.epinephelinae.CloseableGrouperIterator<>;
```

**Comment by acslk** [comment]
Added the helper class RowBasedGrouperHelper for some common code between RowProcessor and GroupByMergingQueryRunnerV2. The main common thing between these two classes is that they both aggregate on row sequence using the same grouping and spilling mechanism. The helper class include function to create the grouper and accumulator, and make row iterator from grouper.

**Comment by gianm** [comment]
@acslk could you update the groupbyquery.md docs too, under "Nested groupBys"?

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByMergingQueryRunnerV2.java [hunk 10]
```diff
@@ -148,6 +134,11 @@ public GroupByMergingQueryRunnerV2(
         String.format("druid-groupBy-%s_%s", UUID.randomUUID(), query.getId())
     );
 
+    final LimitedTemporaryStorage temporaryStorage = new LimitedTemporaryStorage(
```
Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByMergingQueryRunnerV2.java]: Any reason this is moved from where it was originally? It would be better to defer creation until the Sequence has started accumulating (see #3296)

Comment (acslk) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByMergingQueryRunnerV2.java]: I feel that it's more appropriate for the temporary storage to be instantiated together with the temporaryStorageDirectory. LimitedTemporaryStorage instantiation currently does not do any resource allocation similar to java File.

Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByMergingQueryRunnerV2.java]: That's true, but it does encapsulate resources if it's ever used at all, and in that case a it does need to be closed. Scoping it to the Sequence with the other stuff is a straight forward way of doing that. Otherwise we'd need to have some other way of making sure it gets closed if used.

Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByMergingQueryRunnerV2.java]: (And also not re-used once closed)

Comment (acslk) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByMergingQueryRunnerV2.java]: Alright, moved it back into sequence accumulation

File: docs/content/querying/groupbyquery.md [hunk 11]
```diff
@@ -150,11 +150,11 @@ results acceptable.
...
-Nested groupBys (dataSource of type "query") are performed the same way for both "v1" and "v2". The broker runs the
-inner groupBy query in the usual way, then materializes the inner query's results, then runs the outer query on those
-materialized results. In particular, the outer query is not distributed at all; it takes place completely on the broker.
-Currently the materialized results are stored on-heap in the broker, and the outer query is done in a single-threaded
-fashion.
+Nested groupBys (dataSource of type "query") are performed differently for "v1" and "v2". The broker first runs the
+inner groupBy query in the usual way. "v1" strategy then materializes the inner query's results on-heap with Druid's
+indexing mechanism, and runs the outer query on these materialized results. "v2" strategy runs the outer query on the
+inner query's results stream with off-heap fact map and on-heap string dictionary that can spill to disk. Both
+strategy perform the outer query on the broker in a single-threaded fashion.
```
Comment (fjy) [inline docs/content/querying/groupbyquery.md]: can we also add a note about the performance difference between v1 and v2 groupBy?

Comment (acslk) [inline docs/content/querying/groupbyquery.md]: not sure if we need another note here, the strategy description already indicated that v2 offer better performance and memory management, so I think it's reasonable to assume it also apply to nested query

File: processing/src/test/java/io/druid/query/groupby/GroupByQueryRunnerTest.java [hunk 12]
```diff
@@ -4424,6 +4425,223 @@ public boolean eval(Row row)
...
+        GroupByQueryRunnerTestHelper.createExpectedRow("2011-03-03", "rows", 0L),
+        GroupByQueryRunnerTestHelper.createExpectedRow("2011-04-01", "rows", 13L),
+        GroupByQueryRunnerTestHelper.createExpectedRow("2011-04-02", "rows", 0L),
+        GroupByQueryRunnerTestHelper.createExpectedRow("2011-04-03", "rows", 0L)
+    );
+    Iterable<Row> results = GroupByQueryRunnerTestHelper.runQuery(factory, runner, query);
+    TestHelper.assertExpectedObjects(expectedResults, results, "");
+  }
+
+  @Ignore
```
Comment (gianm) [inline processing/src/test/java/io/druid/query/groupby/GroupByQueryRunnerTest.java]: Why is this `@Ignore`?

File: processing/src/test/java/io/druid/query/groupby/GroupByQueryRunnerTest.java [hunk 13]
```diff
@@ -4424,6 +4425,223 @@ public boolean eval(Row row)
...
+            ImmutableList.<AggregatorFactory>of(
+                new FilteredAggregatorFactory(QueryRunnerTestHelper.rowsCount, filter)
+            )
+        )
+        .setGranularity(QueryRunnerTestHelper.allGran)
+        .build();
+
+    // v2 strategy would throw an exception for this because the dimension selector in GroupByRowProcessor is not
+    // dictionary encoded, but instead require the row to be set when doing lookup. Null Pointer Exception occurs
+    // when the filter aggregator is initialized with no row set.
```
Comment (gianm) [inline processing/src/test/java/io/druid/query/groupby/GroupByQueryRunnerTest.java]: Note to self: remember to file an issue for this.

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/RowBasedGrouperHelper.java [hunk 14]
```diff
@@ -0,0 +1,603 @@
...
+  )
+  {
+    final GroupByQueryConfig querySpecificConfig = config.withOverrides(query);
+    final Grouper.KeySerdeFactory<RowBasedKey> keySerdeFactory = new RowBasedKeySerdeFactory(
+        query.getDimensions().size(),
+        querySpecificConfig.getMaxMergingDictionarySize() / concurrencyHint
+    );
+    final RowBasedColumnSelectorFactory columnSelectorFactory = new RowBasedColumnSelectorFactory();
+    final Grouper<RowBasedKey> grouper;
+    if (concurrencyHint == 1) {
```
Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/RowBasedGrouperHelper.java]: The grouper still needs to be concurrency-safe even if `concurrencyHint` is 1. This could happen for the merging query runner if there's only one processing thread; in that case we still want to be able to read from a different query thread.

Maybe we could use a negative concurrencyHint to indicate that thread safety isn't needed.

File: processing/src/test/java/io/druid/query/groupby/GroupByQueryRunnerTest.java (hunk 12 above)
Comment (acslk) [inline processing/src/test/java/io/druid/query/groupby/GroupByQueryRunnerTest.java]: oops, the ignore shouldn't be there, I've already set V1 to expect exception below

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/RowBasedGrouperHelper.java [hunk 15]
```diff
@@ -0,0 +1,603 @@
...
+
+        if (queryGranularity instanceof AllGranularity) {
+          timestamp = query.getIntervals().get(0).getStartMillis();
+        }
+
+        columnSelectorFactory.setRow(row);
+        final String[] dimensions = new String[query.getDimensions().size()];
+        for (int i = 0; i < dimensions.length; i++) {
+          final String value;
+          if (applyExtractionFn) {
```
Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/RowBasedGrouperHelper.java]: hmm, `applyExtractionFn` doesn't seem like the right name for this. What this flag is really telling us is that we are operating on "raw" data rather than "partially merged" data. So maybe it should be called `isInputRaw`.

Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/RowBasedGrouperHelper.java]: That could also potentially control whether to make the agg factories combining factories or not.

raw data -> use the regular factory
partially merged (not raw) data -> use the combining factory

Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/RowBasedGrouperHelper.java]: That could also control if we need to truncate the timestamp or not.

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/RowBasedGrouperHelper.java (hunk 14 above)
Comment (acslk) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/RowBasedGrouperHelper.java]: changed concurrencyHint to -1 to indicate not to use concurrent grouper

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/RowBasedGrouperHelper.java (hunk 15 above)
Comment (acslk) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/RowBasedGrouperHelper.java]: changed the flag name, also it now control whether timestamp should be truncated instead of passing in granularity

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/RowBasedGrouperHelper.java [hunk 16]
```diff
@@ -0,0 +1,605 @@
...
+      final GroupByQuery query,
+      final boolean isInputRaw,
+      final GroupByQueryConfig config,
+      final ByteBuffer buffer,
+      final int concurrencyHint,
+      final LimitedTemporaryStorage temporaryStorage,
+      final ObjectMapper spillMapper,
+      final AggregatorFactory[] aggregatorFactories
+  )
+  {
```
Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/RowBasedGrouperHelper.java]: A snippet like this here would really clarify what's going on with concurrencyHint.

```java
// concurrencyHint >= 1 for thread safe groupers, -1 for non-thread-safe
Preconditions.checkArgument(concurrencyHint >= || concurrencyHint == -1, "invalid concurrencyHint");
```

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/RowBasedGrouperHelper.java [hunk 17]
```diff
@@ -0,0 +1,605 @@
...
+          spillMapper,
+          querySpecificConfig.getBufferGrouperMaxSize(),
+          querySpecificConfig.getBufferGrouperInitialBuckets(),
+          keySerdeFactory,
+          columnSelectorFactory,
+          aggregatorFactories
+      );
+    }
+
+    final DimensionSelector[] dimensionSelectors = new DimensionSelector[query.getDimensions().size()];
```
Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/RowBasedGrouperHelper.java]: These are only used if `isInputRaw` is true; might as well leave this null and skip initializing them otherwise.

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/RowBasedGrouperHelper.java (hunk 16 above)
Comment (acslk) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/RowBasedGrouperHelper.java]: good point, added this precondition check

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/RowBasedGrouperHelper.java (hunk 17 above)
Comment (acslk) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/RowBasedGrouperHelper.java]: now skip initialization based on isInputRaw

**Comment by gianm** [comment]
👍

**Comment by fjy** [comment]
👍
