### PR TITLE
fix NPE with filtered aggregator at ingestion time

### LINKED ISSUE #2061: Filtered aggregators should work at ingestion time
Right now including a filtered aggregator in the metricSpec throws an NPE but there are likely additional issues that need to be addressed to support this:

2015-12-07T23:00:54,620 ERROR [task-runner-0] io.druid.indexing.common.task.RealtimeIndexTask - Exception aborted realtime processing[twitter4]: {class=io.druid.indexing.common.task.RealtimeIndexTask, exceptionType=class java.lang.NullPointerException, exceptionMessage=null}
java.lang.NullPointerException
	at io.druid.segment.incremental.IncrementalIndex$1$6.lookupId(IncrementalIndex.java:238) ~[classes/:?]
	at io.druid.segment.filter.SelectorFilter.makeMatcher(SelectorFilter.java:67) ~[classes/:?]
	at io.druid.query.aggregation.FilteredAggregatorFactory.factorize(FilteredAggregatorFactory.java:53) ~[classes/:?]
	at io.druid.segment.incremental.OnheapIncrementalIndex.addToFacts(OnheapIncrementalIndex.java:144) ~[classes/:?]
	at io.druid.segment.incremental.IncrementalIndex.add(IncrementalIndex.java:462) ~[classes/:?]
	at io.druid.segment.realtime.plumber.Sink.add(Sink.java:125) ~[classes/:?]
	at io.druid.segment.realtime.plumber.RealtimePlumber.add(RealtimePlumber.java:232) ~[classes/:?]
	at io.druid.indexing.common.task.RealtimeIndexTask.run(RealtimeIndexTask.java:332) [classes/:?]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:286) [classes/:?]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:266) [classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
2015-12-07T23:00:54,624 ERROR [task-runner-0] io.druid.indexing.overlord.ThreadPoolTaskRunner - Exception while running task[RealtimeIndexTask{id=index_realtime_twitter4_2015-12-07T15:00:00.000-07:00_0_0, type=index_realtime, dataSource=twitter4}]
java.lang.NullPointerException
	at io.druid.segment.incremental.IncrementalIndex$1$6.lookupId(IncrementalIndex.java:238) ~[classes/:?]
	at io.druid.segment.filter.SelectorFilter.makeMatcher(SelectorFilter.java:67) ~[classes/:?]
	at io.druid.query.aggregation.FilteredAggregatorFactory.factorize(FilteredAggregatorFactory.java:53) ~[classes/:?]
	at io.druid.segment.incremental.OnheapIncrementalIndex.addToFacts(OnheapIncrementalIndex.java:144) ~[classes/:?]
	at io.druid.segment.incremental.IncrementalIndex.add(IncrementalIndex.java:462) ~[classes/:?]
	at io.druid.segment.realtime.plumber.Sink.add(Sink.java:125) ~[classes/:?]
	at io.druid.segment.realtime.plumber.RealtimePlumber.add(RealtimePlumber.java:232) ~[classes/:?]
	at io.druid.indexing.common.task.RealtimeIndexTask.run(RealtimeIndexTask.java:332) ~[classes/:?]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:286) [classes/:?]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:266) [classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
2015-12-07T23:00:54,628 INFO [task-runner-0] io.druid.indexing.worker.executor.ExecutorLifecycle - Task completed with status: {
  "id" : "index_realtime_twitter4_2015-12-07T15:00:00.000-07:00_0_0",
  "status" : "FAILED",
  "duration" : 644
}

### PR DESCRIPTION
**Pull request by sirpkt**
This PR fixes #2061 

NPE of #2061 is from filtered aggregator factory references RowSupplier at factorize() when row of RowSupplier is not set yet.
This patch delays the access of RowSupplier from makeMatcher() to ValueMatcher.matches(). 

It works only for aggregator with selector filter because extraction filter is not supported at ingestion time as cardinality is not fixed at ingestion time

### CODE REVIEW

**Comment by nishantmonu51** [comment]
The reason for lookup to be done early is to improve performance, lookup is generally a costly operation and multiple lookups should generally be avoided whenever possible. I believe this would slow down FilteredAggregator a lot. 
Can you run some performance benchmarks ?

**Comment by b-slim** [comment]
@sirpkt i am not sure how delaying the call to the method level will avoid the NPE.
Can we make it in a way where we can avoid looking up stuff multiple times ?

**Comment by himanshug** [comment]
agree with @nishantmonu51 regarding performance hit. I think, following workarounds can be used  to fulfill use case in #2061
1) in the ETL step create additional column in data which has 1 if filter condition is ok or 0 if not, then use a longSum aggregator on that colunn.
2) create custom druid InputRowParser to introduce above column on the fly when druid is ingesting data.

**Comment by navis** [comment]
@sirpkt How about to wrap `agg.factorize()` with `rowContainer.set(row);` and `rowContainer.set(null);` before and after? It's simple and will not affect performance.

**Comment by sirpkt** [comment]
Everyone worries about performance degradation, and I agree with that.
@navis I think it is perfect way to avoid NPE for OnHeapIncrementalIndex,
But it does not work with OffHeapIncrementalIndex, where agg.factorize() is called even before addToFacts, so I passed that approach.

However, if I change OffHeapIncrementalIndex code a little, I think I can make it work.
I'll try that approach.

**Comment by navis** [comment]
`OffHeapIncrementalIndex` is destined to be removed (it's included in some patches, like #2085, etc.). so it would not be a problem.

**Comment by fjy** [comment]
@sirpkt Offheap incremental index should be removed. It is not production ready and no one is using it.

**Comment by navis** [comment]
+1

**Comment by fjy** [comment]
@sirpkt Agree with previous comments that we need some performance testing before merging this.

**Comment by navis** [comment]
@fjy It's changed into the way that does not affect performance. I think it's ok to be committed.

**Comment by fjy** [comment]
@b-slim @himanshug do you guys have further thoughts with regards to @navis' comments in this PR?

**Comment by fjy** [comment]
@b-slim @himanshug

**Comment by b-slim** [comment]
@navis can you please solve the merging conflicts

File: processing/src/main/java/io/druid/segment/incremental/OffheapIncrementalIndex.java [hunk 1]
```diff
@@ -199,6 +192,15 @@ protected Integer addToFacts(
...
         rowOffset = prev;
       } else {
+        rowContainer.set(row);
+        for (int i = 0; i < metrics.length; i++) {
+          final AggregatorFactory agg = metrics[i];
+          aggs[i] = agg.factorizeBuffered(
+              makeColumnSelectorFactory(agg, rowSupplier, deserializeComplexMetrics)
+          );
+        }
+        rowContainer.set(null);
```
Comment (himanshug) [inline processing/src/main/java/io/druid/segment/incremental/OffheapIncrementalIndex.java]: same rowContainer set/unset happens at line210 and 216 also, can we do the rowContainer.set and unset once only?

File: processing/src/test/java/io/druid/segment/incremental/IncrementalIndexTest.java [hunk 2]
```diff
@@ -88,6 +90,49 @@ public IncrementalIndex createIndex()
...
+                {
+                  @Override
+                  public IncrementalIndex createIndex()
+                  {
+                    return new OnheapIncrementalIndex(
+                        0,
+                        QueryGranularity.MINUTE,
+                        new AggregatorFactory[]{
+                            new FilteredAggregatorFactory(
+                                new CountAggregatorFactory("cnt"),
```
Comment (himanshug) [inline processing/src/test/java/io/druid/segment/incremental/IncrementalIndexTest.java]: can u add FilteredAggregator to existing set of indexes instead of adding a new one just for this test?

**Comment by himanshug** [comment]
@sirpkt @navis new approach looks good to me. 
@fjy no perf needed with the latest updates.

@sirpkt pls rebase/squash and fix conflicts.

File: processing/src/main/java/io/druid/segment/incremental/OffheapIncrementalIndex.java (hunk 1 above)
Comment (sirpkt) [inline processing/src/main/java/io/druid/segment/incremental/OffheapIncrementalIndex.java]: We may make one set/unset to cover all the code of addToFacts.
In my thought, however, it is better to keep two sets of set/unset 
because there exist several error checking and exception throwing routines between those two and with one big set/unset, we should add unset before all the exception throwing that may be catched.

**Comment by sirpkt** [comment]
Thank you for the comments.
I updated based on the comments and rebase/squashed.

**Comment by himanshug** [comment]
:+1:
