### PR TITLE
Downgrade geoip2, exclude com.google.http-client.

### LINKED ISSUE #2717: WikipediaIrcDecoder is not working in master branch
looks like regression from #2646. seeing https://github.com/maxmind/GeoIP2-java/issues/57, we need upgrade version of jackson-binding to >= 2.7.0

```
2016-03-24T06:25:56,227 ERROR [task-runner-0-priority-0] io.druid.indexing.common.task.RealtimeIndexTask - Exception aborted realtime processing[wikipedia]: {class=io.druid.indexing.common.task.RealtimeIndexTask, exceptionType=class java.lang.IllegalArgumentException, exceptionMessage=Instantiation of [simple type, class io.druid.segment.realtime.firehose.WikipediaIrcDecoder] value failed: com.fasterxml.jackson.databind.node.ArrayNode.<init>(Lcom/fasterxml/jackson/databind/node/JsonNodeFactory;Ljava/util/List;)V}
java.lang.IllegalArgumentException: Instantiation of [simple type, class io.druid.segment.realtime.firehose.WikipediaIrcDecoder] value failed: com.fasterxml.jackson.databind.node.ArrayNode.<init>(Lcom/fasterxml/jackson/databind/node/JsonNodeFactory;Ljava/util/List;)V
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:2774) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:2700) ~[jackson-databind-2.4.6.jar:2.4.6]
        at io.druid.segment.indexing.DataSchema.getParser(DataSchema.java:101) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.indexing.common.task.RealtimeIndexTask.run(RealtimeIndexTask.java:336) [druid-indexing-service-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:411) [druid-indexing-service-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:384) [druid-indexing-service-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_75]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_75]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_75]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class io.druid.segment.realtime.firehose.WikipediaIrcDecoder] value failed: com.fasterxml.jackson.databind.node.ArrayNode.<init>(Lcom/fasterxml/jackson/databind/node/JsonNodeFactory;Ljava/util/List;)V
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapException(StdValueInstantiator.java:405) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:234) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:167) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:398) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1064) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:264) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:156) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:126) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:113) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:84) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:132) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:536) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:344) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1064) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:264) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:156) ~[jackson-databind-2.4.6.jar:2.4.6]...
```

### PR DESCRIPTION
**Pull request by gianm**
Reverts "Update com.maxmind.geoip2 to 2.6.0" and exclude the google http client
from com.maxmind.geoip2. This should satisfy the original need from #2646 (wanting
to run Druid along with an upgraded com.google.http-client) while preventing
Jackson conflicts pointed out in #2717.

This reverts commit 21b7572533592f1700f86379483d87e9e340f2a7.

Fixes #2717.

### CODE REVIEW

**Comment by gianm** [comment]
@erikdubbelboer does this approach work for you?

File: server/src/main/java/io/druid/server/lookup/cache/LookupCoordinatorManager.java [hunk 1]
```diff
@@ -160,7 +159,7 @@ void deleteOnHost(final URL url)
         lookupCoordinatorManagerConfig.getHostDeleteTimeout()
     ).get()) {
       // 404 is ok here, that means it was already deleted
-      if (!HttpStatusCodes.isSuccess(returnCode.get()) || HttpStatusCodes.STATUS_CODE_NOT_FOUND != returnCode.get()) {
+      if (!httpStatusIsSuccess(returnCode.get()) || !httpStatusIsNotFound(returnCode.get())) {
```
Comment (gianm) [inline server/src/main/java/io/druid/server/lookup/cache/LookupCoordinatorManager.java]: @drcrallen is this right? I think the `||` should be `&&`

Comment (drcrallen) [inline server/src/main/java/io/druid/server/lookup/cache/LookupCoordinatorManager.java]: Or is correct.

Normal logic is success only.

Here are 404 is also a "success"

Comment (drcrallen) [inline server/src/main/java/io/druid/server/lookup/cache/LookupCoordinatorManager.java]: Oh wai, let me look.

Comment (drcrallen) [inline server/src/main/java/io/druid/server/lookup/cache/LookupCoordinatorManager.java]: Yeah, this is supposed to be any of 200 202 or 404 essentially.  Looking into why unit tests didn't report weird stuff here

Comment (drcrallen) [inline server/src/main/java/io/druid/server/lookup/cache/LookupCoordinatorManager.java]: Thanks for the catch. Will have unit test fix in soon

**Comment by fjy** [comment]
:+1:

**Comment by xvrl** [comment]
:+1:

File: server/src/main/java/io/druid/server/lookup/cache/LookupCoordinatorManager.java (hunk 1 above)
Comment (drcrallen) [inline server/src/main/java/io/druid/server/lookup/cache/LookupCoordinatorManager.java]: test Fixed in https://github.com/druid-io/druid/pull/2743

**Comment by drcrallen** [comment]
```
Tests run: 16, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 29.569 sec <<< FAILURE! - in io.druid.indexing.overlord.RemoteTaskRunnerTest
testRunExistingTaskThatHasntStartedRunning(io.druid.indexing.overlord.RemoteTaskRunnerTest)  Time elapsed: 1.186 sec  <<< FAILURE!
java.lang.AssertionError: expected:<SUCCESS> but was:<FAILED>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.druid.indexing.overlord.RemoteTaskRunnerTest.testRunExistingTaskThatHasntStartedRunning(RemoteTaskRunnerTest.java:160)

```

**Comment by erikdubbelboer** [comment]
@gianm I'm on holiday at the moment so I haven't had time to test it yet.

**Comment by erikdubbelboer** [comment]
@gianm I finally had time to test this, it works perfectly.

**Comment by gianm** [comment]
@erikdubbelboer thanks, that's good to hear!
