### PR TITLE
Fix all transient test failures

### LINKED ISSUE #2113: Non-deterministic io.druid.query.extraction.namespace.TestKafkaExtractionCluster testSimpleRename
```
Running io.druid.query.extraction.namespace.TestKafkaExtractionCluster
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.488 sec <<< FAILURE! - in io.druid.query.extraction.namespace.TestKafkaExtractionCluster
testSimpleRename(io.druid.query.extraction.namespace.TestKafkaExtractionCluster)  Time elapsed: 0.088 sec  <<< FAILURE!
java.lang.AssertionError: expected:<bar> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.druid.query.extraction.namespace.TestKafkaExtractionCluster.testSimpleRename(TestKafkaExtractionCluster.java:352)
Running io.druid.query.extraction.namespace.KafkaExtractionNamespaceTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in io.druid.query.extraction.namespace.KafkaExtractionNamespaceTest
```

### LINKED ISSUE #2147: Transient test error in `SimpleResourceManagementStrategyTest.testProvisionAlert`
```
SimpleResourceManagementStrategyTest.testProvisionAlert:242 
  Unexpected method call ServiceEmitter.emit(com.metamx.emitter.service.AlertBuilder$1@2eb27091):
    ServiceEmitter.emit(<any>): expected: 1, actual: 2
```

### LINKED ISSUE #2158: Transient failure on io.druid.indexing.overlord.TaskLifecycleTest testRealtimeIndexTaskFailure
Build: https://travis-ci.org/druid-io/druid/jobs/98347527
```
io.druid.indexing.overlord.TaskLifecycleTest
testRealtimeIndexTaskFailure[taskStorageType=MetadataTaskStorage](io.druid.indexing.overlord.TaskLifecycleTest)  Time elapsed: 4.878 sec  <<< ERROR!
java.lang.Exception: test timed out after 4000 milliseconds
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parseNegNumber(UTF8StreamJsonParser.java:1259)
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:709)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:337)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1064)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:264)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:124)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3066)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2247)
    at io.druid.metadata.SQLMetadataStorageActionHandler$4.withHandle(SQLMetadataStorageActionHandler.java:195)
    at io.druid.metadata.SQLMetadataStorageActionHandler$4.withHandle(SQLMetadataStorageActionHandler.java:184)
    at org.skife.jdbi.v2.DBI.withHandle(DBI.java:281)
    at io.druid.metadata.SQLMetadataConnector$2.call(SQLMetadataConnector.java:110)
    at com.metamx.common.RetryUtils.retry(RetryUtils.java:38)
    at io.druid.metadata.SQLMetadataConnector.retryWithHandle(SQLMetadataConnector.java:115)
    at io.druid.metadata.SQLMetadataStorageActionHandler.getStatus(SQLMetadataStorageActionHandler.java:182)
    at io.druid.indexing.overlord.MetadataTaskStorage.getStatus(MetadataTaskStorage.java:178)
    at io.druid.indexing.overlord.TaskStorageQueryAdapter.getStatus(TaskStorageQueryAdapter.java:64)
    at io.druid.indexing.overlord.TaskLifecycleTest.testRealtimeIndexTaskFailure(TaskLifecycleTest.java:940)
```

### LINKED ISSUE #2159: Transient failure on io.druid.indexing.common.task.RealtimeIndexTaskTest testBasics
Build https://travis-ci.org/druid-io/druid/jobs/98378549
```
io.druid.indexing.common.task.RealtimeIndexTaskTest
testBasics(io.druid.indexing.common.task.RealtimeIndexTaskTest)  Time elapsed: 12.411 sec  <<< ERROR!
java.lang.Exception: test timed out after 10000 milliseconds
    at java.lang.Thread.sleep(Native Method)
    at io.druid.indexing.common.task.RealtimeIndexTaskTest.testBasics(RealtimeIndexTaskTest.java:207)
```

### LINKED ISSUE #2160: Transient failure on io.druid.server.namespace.cache.JDBCExtractionNamespaceTest testFindNew
Build: https://travis-ci.org/druid-io/druid/jobs/98409883

```
io.druid.server.namespace.cache.JDBCExtractionNamespaceTest
testFindNew[tsColumn](io.druid.server.namespace.cache.JDBCExtractionNamespaceTest)  Time elapsed: 4.362 sec  <<< FAILURE!
org.junit.ComparisonFailure: update check expected:<ba[z]> but was:<ba[r]>
    at org.junit.Assert.assertEquals(Assert.java:115)
    at io.druid.server.namespace.cache.JDBCExtractionNamespaceTest.assertUpdated(JDBCExtractionNamespaceTest.java:347)
    at io.druid.server.namespace.cache.JDBCExtractionNamespaceTest.testFindNew(JDBCExtractionNamespaceTest.java:288)
```

### LINKED ISSUE #2167: Transient failure on io.druid.curator.announcement.AnnouncerTest testSessionKilled
io.druid.curator.announcement.AnnouncerTest
testSessionKilled(io.druid.curator.announcement.AnnouncerTest) Time elapsed: 2.233 sec <<< FAILURE!
java.lang.AssertionError: expected null, but was:<10,10,1451284237249,1451284237249,0,0,0,95111363629613057,25,0,10

### PR DESCRIPTION
**Pull request by fjy**
I made all these changes together to make it easier to see if tests are passing or not.

This PR serves to:

- Fix #2167 
- Fix #2160 
- Fix #2159 
- Fix #2158 
- Fix #2147 
- Fix #2113

### CODE REVIEW

**Comment by fjy** [comment]
io.druid.curator.announcement.AnnouncerTest
testSessionKilled(io.druid.curator.announcement.AnnouncerTest)  Time elapsed: 2.233 sec  <<< FAILURE!
java.lang.AssertionError: expected null, but was:<10,10,1451284237249,1451284237249,0,0,0,95111363629613057,25,0,10
>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:664)
	at org.junit.Assert.assertNull(Assert.java:646)
	at org.junit.Assert.assertNull(Assert.java:656)
	at io.druid.curator.announcement.AnnouncerTest.testSessionKilled(AnnouncerTest.java:175)

**Comment by fjy** [comment]
5 straight passes :D

File: extensions/kafka-extraction-namespace/src/test/java/io/druid/query/extraction/namespace/TestKafkaExtractionCluster.java [hunk 1]
```diff
@@ -373,4 +399,55 @@ public void testSimpleRename() throws InterruptedException
...
+      String key,
+      ConcurrentMap<String, Function<String, String>> lookup
+  )
+      throws InterruptedException
+  {
+    final Function<String, String> extractionFn = lookup.get(namespace);
+
+    int count = 0;
+    if (expected == null) {
+      while (extractionFn.apply(key) != null) {
```
Comment (gianm) [inline extensions/kafka-extraction-namespace/src/test/java/io/druid/query/extraction/namespace/TestKafkaExtractionCluster.java]: Instead of having a timeout here, how about having this never timeout and instead applying a timeout to the test? `@Test(timeout = blah)`. Seems like it would be more robust to have one big timeout than a lot of little timeouts that would be more sensitive to noise.

File: extensions/namespace-lookup/src/test/java/io/druid/server/namespace/cache/JDBCExtractionNamespaceTest.java [hunk 2]
```diff
@@ -482,6 +483,15 @@ private void assertUpdated(String namespace, String key, String expected) throws
     waitForUpdates(1_000L, 2L);
 
     Function<String, String> extractionFn = fnCache.get(namespace);
+
+    int count = 0;
+    while (!extractionFn.apply(key).equals(expected)) {
+      Thread.sleep(100);
+      if (++count > 10) {
```
Comment (gianm) [inline extensions/namespace-lookup/src/test/java/io/druid/server/namespace/cache/JDBCExtractionNamespaceTest.java]: Similar comment… perhaps no timeout here, and rely on the test timeout

File: extensions/namespace-lookup/src/test/java/io/druid/server/namespace/cache/JDBCExtractionNamespaceTest.java [hunk 3]
```diff
@@ -413,7 +414,7 @@ public void testSkipOld()
     assertUpdated(extractionNamespace.getNamespace(), "foo", "bar");
   }
 
-  @Test(timeout = 10_000L)
+  //@Test(timeout = 10_000L)
   public void testFindNew()
```
Comment (gianm) [inline extensions/namespace-lookup/src/test/java/io/druid/server/namespace/cache/JDBCExtractionNamespaceTest.java]: Did you comment this test out intentionally? If so why?

Comment (fjy) [inline extensions/namespace-lookup/src/test/java/io/druid/server/namespace/cache/JDBCExtractionNamespaceTest.java]: oh i forgot to uncomment this

**Comment by gianm** [comment]
:+1: after travis
