### PR TITLE
Fix overlapping segments in IngestSegmentFirehose, DatasourceInputFormat

### LINKED ISSUE #1678: IngestSegmentFirehose may not handle overlapping segments properly
See https://groups.google.com/d/msg/druid-development/ZCXRGzGfXSM/qVVl3W1jDgAJ

It looks like the factory is using a VersionedIntervalTimeline to figure out what segments to read, but doesn't use the interval of the timeline holders to filter the segments.

### PR DESCRIPTION
**Pull request by gianm**
Fixes #1678. IngestSegmentFirehose (and its users) need to remember which
windows of which segments should actually be read, based on a timeline.

### CODE REVIEW

File: indexing-hadoop/src/test/java/io/druid/indexer/BatchDeltaIngestionTest.java [hunk 1]
```diff
@@ -70,8 +70,9 @@
   TemporaryFolder temporaryFolder = new TemporaryFolder();
 
   private ObjectMapper mapper;
-  private Interval interval;
-  private List<DataSegment> segments;
+  private Interval INTERVAL_FULL = new Interval("2014-10-22T00:00:00Z/P1D");
+  private Interval INTERVAL_PARTIAL = new Interval("2014-10-22T00:00:00Z/PT2H");
+  private DataSegment SEGMENT;
```
Comment (himanshug) [inline indexing-hadoop/src/test/java/io/druid/indexer/BatchDeltaIngestionTest.java]: since they are non-static, can we call them intervalFull, intervalPartial and segment ?

File: indexing-hadoop/src/test/java/io/druid/indexer/HadoopIngestionSpecUpdateDatasourcePathSpecSegmentsTest.java [hunk 2]
```diff
@@ -48,32 +48,30 @@
...
-              "type", "local",
-              "path", "/tmp/index1.zip"
-          ),
-          ImmutableList.of("host"),
-          ImmutableList.of("visited_sum", "unique_hosts"),
-          new NoneShardSpec(),
-          9,
-          2
-      )
+  private final DataSegment SEGMENT = new DataSegment(
```
Comment (himanshug) [inline indexing-hadoop/src/test/java/io/druid/indexer/HadoopIngestionSpecUpdateDatasourcePathSpecSegmentsTest.java]: same here, should be "segment"

File: indexing-hadoop/src/test/java/io/druid/indexer/BatchDeltaIngestionTest.java (hunk 1 above)
Comment (gianm) [inline indexing-hadoop/src/test/java/io/druid/indexer/BatchDeltaIngestionTest.java]: Oh, I was thinking they were static; should they just be static?

File: indexing-hadoop/src/main/java/io/druid/indexer/hadoop/WindowedDataSegment.java [hunk 3]
```diff
@@ -0,0 +1,89 @@
...
+package io.druid.indexer.hadoop;
+
+import com.fasterxml.jackson.annotation.JsonCreator;
+import com.fasterxml.jackson.annotation.JsonProperty;
+import io.druid.timeline.DataSegment;
+import org.joda.time.Interval;
+
+import java.util.Objects;
+
+public class WindowedDataSegment
```
Comment (himanshug) [inline indexing-hadoop/src/main/java/io/druid/indexer/hadoop/WindowedDataSegment.java]: can we add a WindowedDataSegmentTest to test simple Serde?

File: indexing-hadoop/src/main/java/io/druid/indexer/hadoop/DatasourceRecordReader.java [hunk 4]
```diff
@@ -70,18 +69,18 @@ public void initialize(InputSplit split, final TaskAttemptContext context) throw
...
         {
           @Override
-          public StorageAdapter apply(DataSegment segment)
+          public WindowedStorageAdapter apply(WindowedDataSegment segment)
           {
             try {
-              logger.info("Getting storage path for segment [%s]", segment.getIdentifier());
-              Path path = new Path(JobHelper.getURIFromSegment(segment));
+              logger.info("Getting storage path for segment [%s]", segment.getSegment().getIdentifier());
+              Path path = new Path(JobHelper.getURIFromSegment(segment.getSegment()));
```
Comment (fjy) [inline indexing-hadoop/src/main/java/io/druid/indexer/hadoop/DatasourceRecordReader.java]: does this file get used anywhere outside of Hadoop? If yes, this will cause dependency woes

Comment (fjy) [inline indexing-hadoop/src/main/java/io/druid/indexer/hadoop/DatasourceRecordReader.java]: ah nvm, i see what's up

File: indexing-hadoop/src/test/java/io/druid/indexer/BatchDeltaIngestionTest.java (hunk 1 above)
Comment (himanshug) [inline indexing-hadoop/src/test/java/io/druid/indexer/BatchDeltaIngestionTest.java]: yeah, they don't change, we can make everything static as well if you want.. I am fine both ways as it doesn't matter in this case.

File: indexing-service/src/test/java/io/druid/indexing/firehose/IngestSegmentFirehoseFactoryTest.java [hunk 5]
```diff
@@ -332,6 +302,41 @@ public void configure(Binder binder)
     return values;
   }
 
+  public static ObjectMapper newObjectMapper()
```
Comment (fjy) [inline indexing-service/src/test/java/io/druid/indexing/firehose/IngestSegmentFirehoseFactoryTest.java]: can we declare static methods at the top of the file?

**Comment by fjy** [comment]
:+1:

File: indexing-service/src/test/java/io/druid/indexing/firehose/IngestSegmentFirehoseFactoryTest.java (hunk 5 above)
Comment (gianm) [inline indexing-service/src/test/java/io/druid/indexing/firehose/IngestSegmentFirehoseFactoryTest.java]: this is the top of the file

File: indexing-hadoop/src/test/java/io/druid/indexer/BatchDeltaIngestionTest.java (hunk 1 above)
Comment (gianm) [inline indexing-hadoop/src/test/java/io/druid/indexer/BatchDeltaIngestionTest.java]: ok, updated them to statics

File: indexing-hadoop/src/main/java/io/druid/indexer/hadoop/WindowedDataSegment.java (hunk 3 above)
Comment (gianm) [inline indexing-hadoop/src/main/java/io/druid/indexer/hadoop/WindowedDataSegment.java]: added

File: indexing-hadoop/src/test/java/io/druid/indexer/HadoopIngestionSpecUpdateDatasourcePathSpecSegmentsTest.java (hunk 2 above)
Comment (gianm) [inline indexing-hadoop/src/test/java/io/druid/indexer/HadoopIngestionSpecUpdateDatasourcePathSpecSegmentsTest.java]: made static

**Comment by gianm** [comment]
should we backport this for 0.8.1-rc3? (and if so who does that?)

**Comment by himanshug** [comment]
@gianm yes
@xvrl for backporting into 0.8.1 , is there a automated way that you use to create those backport PRs or authors are individually supposed to just create a new PR with necessary commits?

**Comment by drcrallen** [comment]
@gianm Backport failed >.<   #1690

File: indexing-hadoop/src/main/java/io/druid/indexer/HadoopIngestionSpec.java [hunk 6]
```diff
@@ -116,25 +122,40 @@ public static HadoopIngestionSpec updateSegmentListIfDatasourcePathSpecIsUsed(
...
+      DatasourceIngestionSpec ingestionSpecObj = jsonMapper.convertValue(
+          ingestionSpecMap,
+          DatasourceIngestionSpec.class
+      );
       List<DataSegment> segmentsList = segmentLister.getUsedSegmentsForInterval(
           ingestionSpecObj.getDataSource(),
           ingestionSpecObj.getInterval()
       );
-      datasourcePathSpec.put(segments, segmentsList);
+      VersionedIntervalTimeline<String, DataSegment> timeline = new VersionedIntervalTimeline<>(Ordering.natural());
```
Comment (guobingkun) [inline indexing-hadoop/src/main/java/io/druid/indexer/HadoopIngestionSpec.java]: @gianm , I was wondering why we need to scan the timeline here since the returned segments from ```segmentLister.getUsedSegmentsForInterval``` already did that?

Comment (gianm) [inline indexing-hadoop/src/main/java/io/druid/indexer/HadoopIngestionSpec.java]: @guobingkun We also need to know which sections of those segments we should scan. Some segments may only be partially valid due to overshadowing. (you might have a newer hourly granularity segment partially overshadowing an older day granularity segment)

Comment (guobingkun) [inline indexing-hadoop/src/main/java/io/druid/indexer/HadoopIngestionSpec.java]: I see, thanks!
