### PR TITLE
Fix AnnouncerTest.testSanity()

### LINKED ISSUE #2253: transient AnnouncerTest.testSanity() failure
https://travis-ci.org/druid-io/druid/jobs/101730020

```
testSanity(io.druid.curator.announcement.AnnouncerTest)  Time elapsed: 61.019 sec  <<< ERROR!

java.lang.Exception: test timed out after 60000 milliseconds

    at sun.misc.Unsafe.park(Native Method)

    at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)

    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)

    at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)

    at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)

    at org.apache.curator.test.Timing.awaitLatch(Timing.java:120)

    at io.druid.curator.announcement.AnnouncerTest.testSanity(AnnouncerTest.java:101)
```

### PR DESCRIPTION
**Pull request by jihoonson**
Fix #2253.

AnnouncerTest essentially

1. Makes a PathChildrenCache for ```/``` and writes something on a ```/test1``` in background. The PathChildrenCache has an event listener for the ```CHILD_REMOVED``` event.
2. Deletes ```/test1``` transactionally.
3. Expects PathChildrenCache recreates the removed path on ```CHILD_REMOVED``` event.

However, if the delete in the second step is performed before the write in the first step is finished, PathChildrenCache never receives ```CHILD_REMOVED``` event. 

I fixed this issue by waiting for the ```/test1``` path to be created before calling the delete operation. However, I'm still concerned with that this issue may exist in real applications.

Since ZooKeeper and Curator offers eventual consistency, it doesn't guarantee that all events are received. So I think the best solution is to use another coordination system guaranteeing all events are seen. HTTP-based coordination system @himanshug is working on can be a good solution.

---
This change is [Reviewable](https://reviewable.io/reviews/druid-io/druid/5077)

### CODE REVIEW

**Comment by jihoonson** [comment]
Hmm weird. Looks there is another issue.

**Comment by leventov** [comment]
CI just failed with the same error:
```
io.druid.curator.announcement.AnnouncerTest
testSanity(io.druid.curator.announcement.AnnouncerTest)  Time elapsed: 61.104 sec  <<< ERROR!
java.lang.Exception: test timed out after 60000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
	at org.apache.curator.test.Timing.awaitLatch(Timing.java:120)
	at io.druid.curator.announcement.AnnouncerTest.testSanity(AnnouncerTest.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
```

**Comment by gianm** [comment]
Oops, the test still failed. I guess I won't merge this yet.

**Comment by himanshug** [comment]
It might be good idea to take a deeper look into Announcer class and make sure that it doesn't have a bug instead of test.

**Comment by jihoonson** [comment]
Thanks guys for the review.

I think there might be several issues beyond this failure. I could reproduce this timeout failure with a lazy executorService which sleeps for 10 secs before every ```execute()``` call, and, in this case, it was because of the missing ```CHILD_REMOVED``` event described above.

I also checked Announcer, but couldn't find any race condition. Even if it has a race condition, I bet it does not relate to this timeout issue because AnnouncerTest is essentially single-threaded. For all operations executed in background (write on ZK), it immediately checks the result of those operations or waits for them to be finished using latch. 

However, yeah, it still fails sometimes. I'm not sure why this happens.
I'm testing this patch by running travis CI multiple times. Hopefully this patch helps to reduce the timeout failure.

**Comment by jihoonson** [comment]
The test looks being passed after adding a travis job for server module test. I feel the time when most travis builds fail is 09:00 PDT, so I will run more travis builds for this patch during that time.

**Comment by jihoonson** [comment]
I found that ```CHILD_ADDED``` event for ```/test``` (and thus ```CHILD_REMOVED``` event as well) can be missed even with this patch. See the below log from https://travis-ci.org/jihoonson/druid/jobs/302864575.

```
2017-11-17T05:47:43,075 INFO [Thread-41] io.druid.curator.announcement.AnnouncerTest - begin testSanity
2017-11-17T05:47:43,075 INFO [Thread-41] org.apache.curator.framework.imps.CuratorFrameworkImpl - Starting
2017-11-17T05:47:43,075 INFO [Thread-41] org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=127.0.0.1:42721 sessionTimeout=2000 watcher=org.apache.curator.ConnectionState@70ec6475
2017-11-17T05:47:43,079 INFO [Thread-41-SendThread(127.0.0.1:42721)] org.apache.zookeeper.ClientCnxn - Opening socket connection to server 127.0.0.1/127.0.0.1:42721. Will not attempt to authenticate using SASL (unknown error)
2017-11-17T05:47:43,079 INFO [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:42721] org.apache.zookeeper.server.NIOServerCnxnFactory - Accepted socket connection from /127.0.0.1:38990
2017-11-17T05:47:43,079 INFO [Thread-41] org.apache.curator.framework.imps.CuratorFrameworkImpl - Default schema
2017-11-17T05:47:43,080 INFO [Thread-41-SendThread(127.0.0.1:42721)] org.apache.zookeeper.ClientCnxn - Socket connection established to 127.0.0.1/127.0.0.1:42721, initiating session
2017-11-17T05:47:43,080 INFO [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:42721] org.apache.zookeeper.server.ZooKeeperServer - Client attempting to establish new session at /127.0.0.1:38990
2017-11-17T05:47:43,080 INFO [SyncThread:0] org.apache.zookeeper.server.persistence.FileTxnLog - Creating new log file: log.1
2017-11-17T05:47:43,082 INFO [SyncThread:0] org.apache.zookeeper.server.ZooKeeperServer - Established session 0x15fc884b86a0000 with negotiated timeout 6000 for client /127.0.0.1:38990
2017-11-17T05:47:43,083 INFO [Thread-41-SendThread(127.0.0.1:42721)] org.apache.zookeeper.ClientCnxn - Session establishment complete on server 127.0.0.1/127.0.0.1:42721, sessionid = 0x15fc884b86a0000, negotiated timeout = 6000
2017-11-17T05:47:43,083 INFO [Thread-41-EventThread] org.apache.curator.framework.state.ConnectionStateManager - State change: CONNECTED
2017-11-17T05:47:43,087 INFO [Thread-41] io.druid.curator.announcement.Announcer - Starting announcer
2017-11-17T05:47:43,110 INFO [test-announcer-sanity-0] io.druid.curator.announcement.Announcer - Path[/] got event[PathChildrenCacheEvent{type=CHILD_ADDED, data=ChildData{path='/zookeeper', stat=0,0,0,0,0,-1,0,0,0,1,0
, data=null}}]
2017-11-17T05:47:43,110 INFO [test-announcer-sanity-0] io.druid.curator.announcement.Announcer - Path[/] got event[PathChildrenCacheEvent{type=CHILD_ADDED, data=ChildData{path='/somewhere', stat=3,3,1510897663095,1510897663095,0,1,0,0,11,1,4
, data=null}}]
2017-11-17T05:47:43,111 INFO [test-announcer-sanity-0] io.druid.curator.announcement.Announcer - Path[/somewhere] got event[PathChildrenCacheEvent{type=CHILD_ADDED, data=ChildData{path='/somewhere/test2', stat=4,4,1510897663096,1510897663096,0,0,0,99018189180633088,25,0,4
, data=null}}]
2017-11-17T05:47:45,000 INFO [SessionTracker] org.apache.zookeeper.server.SessionTrackerImpl - SessionTrackerImpl exited loop!
2017-11-17T05:48:43,076 INFO [Thread-41] io.druid.curator.announcement.Announcer - Stopping announcer
2017-11-17T05:48:43,076 INFO [Thread-41] io.druid.curator.announcement.Announcer - unannouncing [/somewhere/test2]
2017-11-17T05:48:43,076 INFO [Thread-41] io.druid.curator.announcement.AnnouncerTest - end testSanity
```

I think the best solution for now is polling to check the ```/test``` path exists instead of waiting for ```CuratorEventType.CREATE```using latch. I'll update this PR shortly.

**Comment by gianm** [comment]
@jihoonson is this patch ready or are you still doing more testing?

**Comment by jihoonson** [comment]
The latest commit was my last test. It's finally ready.
I added an interface to ```Announcer``` to know for which ZK paths CHILD_ADDED events are received. This doesn't look the best way, but safest.

**Comment by gianm** [comment]
Do you think this is masking a real bug in the Announcer? If so what kind of bug do you suspect -- and can you leave a comment?

**Comment by jihoonson** [comment]
Well, the root cause is Zookeeper and PathChildrenCache don't guarantee that Announcer will get all events (http://mail-archives.apache.org/mod_mbox/curator-user/201711.mbox/browser), so Announcer should be based on something another system which guarantees it. I added a comment.

File: server/src/main/java/io/druid/curator/announcement/Announcer.java [hunk 1]
```diff
@@ -217,6 +236,8 @@ public void announce(String path, byte[] bytes, boolean removeParentIfCreated)
                 @Override
                 public void childEvent(CuratorFramework client, PathChildrenCacheEvent event) throws Exception
                 {
+                  // NOTE: ZooKeeper does not guarantee that we will get every event, and thus PathChildrenCache doesn't
+                  // as well. If one of the below events are missed, Announcer might not work properly.
```
Comment (gianm) [inline server/src/main/java/io/druid/curator/announcement/Announcer.java]: This comment seems related to another one in the same file (last couple of sentences).

```
// Lost connection, which means session is broken, take inventory of what has been seen.
// This is to protect from a race condition in which the ephemeral node could have been
// created but not actually seen by the PathChildrenCache, which means that it won't know
// that it disappeared and thus will not generate a CHILD_REMOVED event for us.  Under normal
// circumstances, this can only happen upon connection loss; but technically if you have
// an adversary in the system, they could also delete the ephemeral node before the cache sees
// it.  This does not protect from that case, so don't have adversaries.
```

**Comment by gianm** [comment]
Thanks for the deep investigation @jihoonson!

File: server/src/main/java/io/druid/curator/announcement/Announcer.java (hunk 1 above)
Comment (jihoonson) [reply server/src/main/java/io/druid/curator/announcement/Announcer.java]: Right. It's related.

**Comment by jihoonson** [comment]
@gianm no problem!
