### PR TITLE
limit size of X-Druid-Response-Context header to 7K

### LINKED ISSUE #2331: introduce mechanism to limit response context size
druid query response can contain header "X-Druid-Response-Context" which is unbounded in size and can lead to exception like below.
```
2015-12-16T17:33:21,646 WARN [qtp296974277-44] org.eclipse.jetty.server.HttpChannel - /druid/v2/?pretty
java.io.IOException: Response header too large
    at org.eclipse.jetty.http.HttpGenerator.generateResponse(HttpGenerator.java:400) ~[jetty-http-9.2.5.v20141112.jar:9.2.5.v20141112]
    at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:599) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
    at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:246) ~[jetty-util-9.2.5.v20141112.jar:9.2.5.v20141112]
    at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:208) ~[jetty-util-9.2.5.v20141112.jar:9.2.5.v20141112]
    at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:448) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
    at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:762) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
    at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:800) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:139) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:132) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:347) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
...
Caused by: java.nio.BufferOverflowException
    at java.nio.Buffer.nextPutIndex(Buffer.java:521) ~[?:1.8.0_51]
    at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:169) ~[?:1.8.0_51]
    at org.eclipse.jetty.http.HttpGenerator.putSanitisedValue(HttpGenerator.java:1057) ~[jetty-http-9.2.5.v20141112.jar:9.2.5.v20141112]
    at org.eclipse.jetty.http.HttpGenerator.putTo(HttpGenerator.java:1079) ~[jetty-http-9.2.5.v20141112.jar:9.2.5.v20141112]
    at org.eclipse.jetty.http.HttpGenerator.generateHeaders(HttpGenerator.java:703) ~[jetty-http-9.2.5.v20141112.jar:9.2.5.v20141112]
    at org.eclipse.jetty.http.HttpGenerator.generateResponse(HttpGenerator.java:385) ~[jetty-http-9.2.5.v20141112.jar:9.2.5.v20141112]
    ... 74 more
```

there should be a mechanism to configure the header size in jetty and also a way to enforce that limit w/o getting jetty exceptions and query failure.

it was exposed in https://github.com/druid-io/druid/issues/2108

### PR DESCRIPTION
**Pull request by himanshug**
fixes #2331

### CODE REVIEW

File: server/src/main/java/io/druid/server/QueryResource.java [hunk 1]
```diff
@@ -220,8 +222,17 @@ public void write(OutputStream outputStream) throws IOException, WebApplicationE
                 },
                 contentType
             )
-            .header("X-Druid-Query-Id", queryId)
-            .header("X-Druid-Response-Context", jsonMapper.writeValueAsString(responseContext))
+            .header("X-Druid-Query-Id", queryId);
+
+        //Limit the response-context header, see https://github.com/druid-io/druid/issues/2331
+        String responseCtxString = jsonMapper.writeValueAsString(responseContext);
```
Comment (gianm) [inline server/src/main/java/io/druid/server/QueryResource.java]: The limit is probably on the bytes rather than chars so I think it would be better to `writeValueAsBytes`

File: server/src/main/java/io/druid/server/QueryResource.java [hunk 2]
```diff
@@ -220,8 +222,17 @@ public void write(OutputStream outputStream) throws IOException, WebApplicationE
...
+        if (responseCtxString.length() > RESPONSE_CTX_HEADER_LEN_LIMIT) {
+          log.warn("Response Context truncated for id [%s] . Full context is [%s].", queryId, responseCtxString);
+          responseCtxString = responseCtxString.substring(0, RESPONSE_CTX_HEADER_LEN_LIMIT);
```
Comment (gianm) [inline server/src/main/java/io/druid/server/QueryResource.java]: IMO there should be another header to tell you whether the response context has been truncated, otherwise callers will have to rely on catching parse errors, which may mask other problems

File: server/src/main/java/io/druid/server/QueryResource.java [hunk 3]
```diff
@@ -220,8 +222,17 @@ public void write(OutputStream outputStream) throws IOException, WebApplicationE
...
                 contentType
             )
-            .header("X-Druid-Query-Id", queryId)
-            .header("X-Druid-Response-Context", jsonMapper.writeValueAsString(responseContext))
+            .header("X-Druid-Query-Id", queryId);
+
+        //Limit the response-context header, see https://github.com/druid-io/druid/issues/2331
+        String responseCtxString = jsonMapper.writeValueAsString(responseContext);
+        if (responseCtxString.length() > RESPONSE_CTX_HEADER_LEN_LIMIT) {
+          log.warn("Response Context truncated for id [%s] . Full context is [%s].", queryId, responseCtxString);
```
Comment (gianm) [inline server/src/main/java/io/druid/server/QueryResource.java]: maybe also have a max log line length that is somewhat longer than 7KB but not crazy long (7KB is already gonna generate at least a 70 line log message).

File: server/src/main/java/io/druid/server/QueryResource.java (hunk 2 above)
Comment (xvrl) [inline server/src/main/java/io/druid/server/QueryResource.java]: Is it even worthwhile to truncate it? If we are fine removing any part of the context we might want to remove it altogether, since we won't have a good idea of what part will be in it anyways.

Comment (gianm) [inline server/src/main/java/io/druid/server/QueryResource.java]: the only reason I can think of doing that is that it might help debugging without having access to the server logs. If your truncated context has a ton of the same kind of object in it then that would give you some hints about what is going on.

Comment (xvrl) [inline server/src/main/java/io/druid/server/QueryResource.java]: maybe just stick into `X-Druid-Truncated-Response-Context`, this way there is no need for a flag.

File: server/src/main/java/io/druid/server/QueryResource.java (hunk 1 above)
Comment (himanshug) [inline server/src/main/java/io/druid/server/QueryResource.java]: header bytes are encoded using ASCII, so 1 char = 1 byte
in the builder.header(String key, Object value), eventually somewhere value.toString() is called and encoded using ASCII . I tried passing a byte[] to builder.header(..) and in response I got `[B@468a1ce3`.
I have updated the comment.

File: server/src/main/java/io/druid/server/QueryResource.java (hunk 3 above)
Comment (himanshug) [inline server/src/main/java/io/druid/server/QueryResource.java]: hmm... the reason we are logging so that user can see what was full content of the context as some of what is being truncated might be useful meta information.
what is the worst that will happen when we do not truncate the log? maybe some slowness from writing big log line.

i'm not sure if we really need a limit here. what do others think, @xvrl? what would be suggested limit of that?

File: server/src/main/java/io/druid/server/QueryResource.java (hunk 2 above)
Comment (himanshug) [inline server/src/main/java/io/druid/server/QueryResource.java]: @xvrl you mean in normal case user will get `X-Druid-Response-Context` and in overflow case user would get `X-Druid-Truncated-Response-Context` with truncated context?
I actually find another header as flag cleaner approach.

File: server/src/main/java/io/druid/server/QueryResource.java (hunk 1 above)
Comment (drcrallen) [inline server/src/main/java/io/druid/server/QueryResource.java]: `StringUtils.toUtf8(responseCtxString).length` might not equal `responseCtxString.length()`

Comment (drcrallen) [inline server/src/main/java/io/druid/server/QueryResource.java]: what happens in utf8 multi-byte characters in headers?

Comment (himanshug) [inline server/src/main/java/io/druid/server/QueryResource.java]: @drcrallen jetty would do a buffer.put((byte)(0xff&c)); see https://github.com/eclipse/jetty.project/blob/master/jetty-http/src/main/java/org/eclipse/jetty/http/HttpGenerator.java#L963

File: server/src/main/java/io/druid/server/QueryResource.java (hunk 3 above)
Comment (gianm) [inline server/src/main/java/io/druid/server/QueryResource.java]: mostly log size getting out of control if there is something systematically emitting huge contexts on every query (like uncoveredIntervals on disjoint segments, or something else of that nature).

File: server/src/main/java/io/druid/server/QueryResource.java (hunk 2 above)
Comment (xvrl) [inline server/src/main/java/io/druid/server/QueryResource.java]: I don't have a strong feeling, either way we have to have an extra header. My thought was, always being able to parse X-Druid-Response-Context without having to check another flag was cleaner.

File: server/src/main/java/io/druid/server/QueryResource.java (hunk 3 above)
Comment (xvrl) [inline server/src/main/java/io/druid/server/QueryResource.java]: @himanshug @gianm maybe we can limit it to maximum length of a Java stacktrace, if there is such a thing?

File: server/src/main/java/io/druid/server/QueryResource.java (hunk 1 above)
Comment (xvrl) [inline server/src/main/java/io/druid/server/QueryResource.java]: @drcrallen @himanshug the most correct way would be to enable the `JsonGenerator .Feature.ESCAPE_NON_ASCII` feature in jackson to ensure we correctly escape all non-ascii characters, otherwise the resulting context may not be valid JSON.

File: server/src/main/java/io/druid/server/QueryResource.java (hunk 3 above)
Comment (xvrl) [inline server/src/main/java/io/druid/server/QueryResource.java]: looks like Java limits stacktraces to 1024 lines, I'm fine doing the same.

**Comment by xvrl** [comment]
@himanshug added a few more comments that got buried in the rebase, in case you don't see them.

https://github.com/druid-io/druid/pull/2336#discussion_r51056851
https://github.com/druid-io/druid/pull/2336#discussion_r51057740
https://github.com/druid-io/druid/pull/2336#discussion_r51058172

File: server/src/main/java/io/druid/server/QueryResource.java (hunk 3 above)
Comment (himanshug) [inline server/src/main/java/io/druid/server/QueryResource.java]: we'll have to have character limit, definition of line is arbitrary. how about limiting the log to 20K chars?

File: server/src/main/java/io/druid/server/QueryResource.java (hunk 2 above)
Comment (himanshug) [inline server/src/main/java/io/druid/server/QueryResource.java]: i would prefer the flag header so that there is no extra encoding defined on `X-Druid-Response-Context`... will add the flag header.

File: server/src/main/java/io/druid/server/QueryResource.java (hunk 1 above)
Comment (himanshug) [inline server/src/main/java/io/druid/server/QueryResource.java]: @xvrl i guess if we are worried about invalid json in the header, then we should really  move towards having a first class "metadata" attribute in the query response payload and put the information there. header is not probably the right place as you are going to remove some stuff to make it valid json anyway.

**Comment by fjy** [comment]
:+1:

**Comment by xvrl** [comment]
@himanshug we don't have to get held up by the non-ascii stuff, but I feel having a header that might either be incomplete or mangled will have to be addressed at some point.

+1 once we file an issue about the non-ascii mangling in reponse context

**Comment by himanshug** [comment]
@xvrl tracking in https://github.com/druid-io/druid/issues/2372
