### PR TITLE
Fix race in CachingCostBalancerStrategyFactory

### LINKED ISSUE #4984: Callback race on start in cachingCost balancer
CachingCostBalancerStrategyFactory registers callbacks in its `start()` method, which is problematic since any callbacks that happen between start of ServerInventoryView and BalancerStrategyFactory will be missed. Inventory view callbacks should generally be registered in constructors, not in start methods.

I discovered this when trying to test the cachingCost balancer on a cluster that has a small number of segments, and found that it missed the initialization callback (happened too fast) so it refused to create itself.

cc: @dgolitsyn @leventov

### PR DESCRIPTION
**Pull request by leventov**
Fixes #4984

### CODE REVIEW

**Comment by leventov** [comment]
@gianm I don't see the reason for that, removed timeout.

File: server/src/main/java/io/druid/server/coordinator/CachingCostBalancerStrategyFactory.java [hunk 1]
```diff
@@ -41,115 +38,100 @@
...
       try {
+        // Calling clusterCostCacheBuilder.build() in the same thread (executor's sole thread) where
+        // clusterCostCacheBuilder is updated, to avoid problems with concurrent updates
         CompletableFuture<CachingCostBalancerStrategy> future = CompletableFuture.supplyAsync(
             () -> new CachingCostBalancerStrategy(clusterCostCacheBuilder.build(), exec),
             executor
         );
         try {
-          return future.get(1, TimeUnit.SECONDS);
+          return future.get();
```
Comment (himanshug) [inline server/src/main/java/io/druid/server/coordinator/CachingCostBalancerStrategyFactory.java]: why do above computation in separate thread and not in this thread when we are blocking this thread endlessly anyway ?

Comment (leventov) [reply server/src/main/java/io/druid/server/coordinator/CachingCostBalancerStrategyFactory.java]: Because clusterCostCacheBuilder is not thread-safe for concurrent use. And there is no way to copy this object without races, other than in the executor's thread as well. It would be just more complicated that the current solution, without benefits.

**Comment by gianm** [comment]
👍

**Comment by gianm** [comment]
@leventov could you backport this to 0.11.0 please? (assuming it should be there since you set the milestone)

**Comment by leventov** [comment]
I will do, some time this week, very busy resolving issues in production after 0.11 rollout, so be sure this version is not ready to release yet. It's not the only issue.

**Comment by gianm** [comment]
@leventov I'll backport this then to save you some time.
