### PR TITLE
FilteredHttpServerInventoryViewProvider to start with always false predicate for each segment discovered

### LINKED ISSUE #5121: Http broker filters probably do not work as expected.
https://github.com/druid-io/druid/blob/druid-0.11.0-rc2/server/src/main/java/io/druid/client/FilteredHttpServerInventoryViewProvider.java#L63 sets an alwaysTrue whereas https://github.com/druid-io/druid/blob/druid-0.11.0-rc2/server/src/main/java/io/druid/client/FilteredBatchServerInventoryViewProvider.java#L55 sets an alwaysFalse.

This comes into play in the OR statement creation at https://github.com/druid-io/druid/blob/druid-0.11.0-rc2/server/src/main/java/io/druid/client/HttpServerInventoryView.java#L269-L272 and https://github.com/druid-io/druid/blob/druid-0.11.0-rc2/server/src/main/java/io/druid/client/BatchServerInventoryView.java#L97-L100 respectively

### PR DESCRIPTION
**Pull request by himanshug**
Fixes #5121 

and minor unrelated change to ensure all predicates are registered before lifecycle starts. it happens that way already but just adding the verification for same.

### CODE REVIEW

File: server/src/main/java/io/druid/client/HttpServerInventoryView.java [hunk 1]
```diff
@@ -96,6 +96,11 @@
 
   private final ConcurrentMap<SegmentCallback, Predicate<Pair<DruidServerMetadata, DataSegment>>> segmentPredicates =
       new ConcurrentHashMap<>();
+
+  // Users of this instance can register filters for what segments should be stored and reported to registered
```
Comment (leventov) [inline server/src/main/java/io/druid/client/HttpServerInventoryView.java]: Could you please make this a javadoc comment?

Comment (himanshug) [reply server/src/main/java/io/druid/client/HttpServerInventoryView.java]: you mean on the constructor ?

Comment (leventov) [reply server/src/main/java/io/druid/client/HttpServerInventoryView.java]: on the field

Comment (himanshug) [reply server/src/main/java/io/druid/client/HttpServerInventoryView.java]: just curious, why does that matter ?

Comment (leventov) [reply server/src/main/java/io/druid/client/HttpServerInventoryView.java]: - More apparent that this comment belongs to a field, not just random comment between the lines
 - When code is refactored in IDE, the doc comment is attached to a field and moves with it, unlike `//` comments
 - Ability to make other class refs in a comment links, to ease navigation in IDE, and also when classes are renamed, links in Javadocs are renamed automatically too.

Comment (himanshug) [reply server/src/main/java/io/druid/client/HttpServerInventoryView.java]: ok, changed.
