### PR TITLE
Don't use QueryMetrics from multiple threads in DirectDruidClient (fixes #4308)

### LINKED ISSUE #4308: DefaultQueryMetrics modified by netty worker threads in DirectDruidClient
Got this stack trace on master today. The caller, `io.druid.client.DirectDruidClient$1.handleResponse`, is running in a netty worker thread for http-client, but the "owner thread" of DefaultQueryMetrics is the query server handling thread.

```
java.lang.IllegalStateException: DefaultQueryMetrics must not be modified from multiple threads. If it is needed to gather dimension or metric information from multiple threads or from an async thread, this information should explicitly be passed between threads (e. g. using Futures), or this DefaultQueryMetrics's ownerThread should be reassigned explicitly
        at io.druid.query.DefaultQueryMetrics.checkModifiedFromOwnerThread(DefaultQueryMetrics.java:56) ~[druid-processing-0.10.1-SNAPSHOT.jar:0.10.1-SNAPSHOT]
        at io.druid.query.DefaultQueryMetrics.reportMetric(DefaultQueryMetrics.java:232) ~[druid-processing-0.10.1-SNAPSHOT.jar:0.10.1-SNAPSHOT]
        at io.druid.query.DefaultQueryMetrics.reportMillisTimeMetric(DefaultQueryMetrics.java:227) ~[druid-processing-0.10.1-SNAPSHOT.jar:0.10.1-SNAPSHOT]
        at io.druid.query.DefaultQueryMetrics.reportNodeTimeToFirstByte(DefaultQueryMetrics.java:216) ~[druid-processing-0.10.1-SNAPSHOT.jar:0.10.1-SNAPSHOT]
        at io.druid.client.DirectDruidClient$1.handleResponse(DirectDruidClient.java:199) ~[druid-server-0.10.1-SNAPSHOT.jar:0.10.1-SNAPSHOT]
        at com.metamx.http.client.NettyHttpClient$1.messageReceived(NettyHttpClient.java:209) [http-client-1.0.6.jar:?]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.handler.timeout.ReadTimeoutHandler.messageReceived(ReadTimeoutHandler.java:184) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.10.4.Final.jar:?]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.10.4.Final.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

### PR DESCRIPTION
**Pull request by leventov**
See #4308

### CODE REVIEW

**Comment by gianm** [comment]
Did you test this? I don't think it will work, since the callbacks will be called by netty in various threads in the http-client worker pool.

**Comment by leventov** [comment]
@gianm no, I didn't test, submitted PR for CI testing. I don't see how callbacks will be called from multiple threads. Netty 3 Javadoc [suggests](http://netty.io/3.10/api/org/jboss/netty/channel/ChannelPipeline.html) that there is a Thread associated with a Channel, from where operations are performed. In http-client, we create a pipeline to serve just one request, hence just one Channel.

File: server/src/main/java/io/druid/client/DirectDruidClient.java [hunk 1]
```diff
@@ -315,6 +322,7 @@ public InputStream nextElement()
               nodeTimeMs,
               byteCount.get() / (0.001 * nodeTimeMs) // Floating math; division by zero will yield Inf, not exception
           );
+          QueryMetrics<? super Query<T>> queryMetrics = acquireQueryMetrics();
```
Comment (gianm) [inline server/src/main/java/io/druid/client/DirectDruidClient.java]: How about just calling `acquireQueryMetrics()` -- the shadowing of a reference with another reference to the same object is weird.

Comment (leventov) [inline server/src/main/java/io/druid/client/DirectDruidClient.java]: To me, calling `acquireQueryMetrics()` on three lines in a row is also misleading, because someone may think that three different objects are expected to be returned from this method. I renamed `acquireQueryMetrics()` to `acquireResponseMetrics()` and local variable accordingly.

**Comment by gianm** [comment]
If that's right, the approach in the patch looks good. http://netty.io/wiki/thread-model.html suggests as well that inbound events happen on "the thread that performs I/O for the channel" which sure sounds like there is only one. If the patch holds up to testing, then, ok.

**Comment by leventov** [comment]
@gianm this wiki page doesn't apply to Netty 3.x (see the bottom of the page). However AFAIR there were some efforts on moving http-client to Netty 4.x, @esevastyanov could you comment on this?

**Comment by gianm** [comment]
It looks like that page is describing goals and problems with 3.x. In my reading, this statement was meant to apply to 3.x:

> UGLY: The upstream events triggered as a side effect of a downstream event is triggered by the caller thread,

AFAIK upstream (inbound) events are the ones we are handling in our handler, could it be that a "side effect of a downstream event" could involve our handler's callbacks getting called by an unexpected thread when some outgoing data fails to send, or when the connection is reset, or something?
