### PR TITLE
Make extension classloader caching keyed on directory

### LINKED ISSUE #3163: Only one class loader is created for multiple hadoopDependencyCoordinates
If I post an indexing task with hadoop coordinates like:

```
  "hadoopDependencyCoordinates": ["org.apache.hadoop:hadoop-client:2.7.1", "org.apache.hadoop:hadoop-aws:2.7.1"]
```

the function Initialization.getClassLoaderForExtension does not create a class loader for the second dependency in the list.

```
  public static URLClassLoader getClassLoaderForExtension(File extension) throws MalformedURLException
  {
    URLClassLoader loader = loadersMap.get(extension.getName());
...
```

This occurs because the two dependencies have the same "extension name", the hadoop version:

FILE: /Users/jw/jw_repo/druid/hadoop-dependencies-tmp/hadoop-client/2.7.1
EXTNAME: 2.7.1

FILE: /Users/jw/jw_repo/druid/hadoop-dependencies-tmp/hadoop-aws/2.7.1
EXTNAME: 2.7.1

### PR DESCRIPTION
**Pull request by drcrallen**
* Keys extension by extension base directory
* Fixes #3163

### CODE REVIEW

File: server/src/main/java/io/druid/initialization/Initialization.java [hunk 1]
```diff
@@ -78,13 +77,15 @@
...
+import java.util.concurrent.ConcurrentHashMap;
+import java.util.concurrent.ConcurrentMap;
 
 /**
  */
 public class Initialization
 {
   private static final Logger log = new Logger(Initialization.class);
-  private static final Map<String, URLClassLoader> loadersMap = Maps.newHashMap();
+  private static final ConcurrentMap<File, URLClassLoader> LOADERS_MAP = new ConcurrentHashMap<>();
```
Comment (fjy) [inline server/src/main/java/io/druid/initialization/Initialization.java]: does this need to be thread safe? was it a bug before?

Comment (drcrallen) [inline server/src/main/java/io/druid/initialization/Initialization.java]: I *think* things were more or less guarded by time or locking waaaaay up the call stack. There isn't really any explicit guarantee that `getClassLoaderForExtension` is or is not thread safe. Since this map is updated in a public static method (and pretty trivial to make threadsafe) I figured I'd make the change.

Comment (drcrallen) [inline server/src/main/java/io/druid/initialization/Initialization.java]: Also `putIfAbsent` isn't in `Map` until java8

File: server/src/main/java/io/druid/initialization/Initialization.java [hunk 2]
```diff
@@ -264,18 +265,13 @@ static void clearLoadedModules()
    */
   public static URLClassLoader getClassLoaderForExtension(File extension) throws MalformedURLException
   {
-    URLClassLoader loader = loadersMap.get(extension.getName());
+    URLClassLoader loader = LOADERS_MAP.get(extension);
     if (loader == null) {
-      final Collection<File> jars = FileUtils.listFiles(extension, new String[]{"jar"}, false);
```
Comment (jon-wei) [inline server/src/main/java/io/druid/initialization/Initialization.java]: @drcrallen I tried a hadoop batch ingestion job with this patch applied, and the task didn't pick up my hadoop-client jars.

Passing in the directory:
```
new URL[]{extension.toURL()}
```

doesn't seem to get the jars picked up, I had to change the URLClassLoader creation back to the original implementation with a url for each file to get the task to proceed.

Comment (drcrallen) [inline server/src/main/java/io/druid/initialization/Initialization.java]: garg. that needs a unit test then.

Comment (drcrallen) [inline server/src/main/java/io/druid/initialization/Initialization.java]: Added patch to address this

**Comment by nishantmonu51** [comment]
👍

**Comment by fjy** [comment]
Committers: Please do not merge until @jon-wei has had a chance to validate things

**Comment by drcrallen** [comment]
Agree with @fjy

**Comment by jon-wei** [comment]
Just tried the latest version of this patch, I'm still running into issues.

For testing, I'm running druid 0.9.0 with a batch ingestion job on a remote hadoop cluster (sequenceiq hadoop 2.7.1 in a docker container), and using S3 for both the input file and the deep storage.

In the ingestion spec I have:

```
  "hadoopDependencyCoordinates" : [ "org.apache.hadoop:hadoop-client:2.7.1", "org.apache.hadoop:hadoop-aws:2.7.1" ]
```

Without the patch, I'll get the following hadoop-aws related error:
```
Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3native.NativeS3FileSystem not found
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2101) ~[?:?]
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2193) ~[?:?]
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2638) ~[?:?]
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2651) ~[?:?]
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:92) ~[?:?]
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2687) ~[?:?]
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2669) ~[?:?]
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:371) ~[?:?]
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295) ~[?:?]
	at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.setInputPaths(FileInputFormat.java:500) ~[?:?]
	at org.apache.hadoop.mapreduce.lib.input.DelegatingInputFormat.getSplits(DelegatingInputFormat.java:110) ~[?:?]
	at org.apache.hadoop.mapreduce.JobSubmitter.writeNewSplits(JobSubmitter.java:301) ~[?:?]
	at org.apache.hadoop.mapreduce.JobSubmitter.writeSplits(JobSubmitter.java:318) ~[?:?]
	at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:196) ~[?:?]
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1290) ~[?:?]
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1287) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_74]
	at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_74]
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657) ~[?:?]
	at org.apache.hadoop.mapreduce.Job.submit(Job.java:1287) ~[?:?]
	at io.druid.indexer.DetermineHashedPartitionsJob.run(DetermineHashedPartitionsJob.java:116) ~[druid-indexing-hadoop-0.9.0.jar:0.9.0]
	at io.druid.indexer.JobHelper.runJobs(JobHelper.java:323) ~[druid-indexing-hadoop-0.9.0.jar:0.9.0]
	at io.druid.indexer.HadoopDruidDetermineConfigurationJob.run(HadoopDruidDetermineConfigurationJob.java:86) ~[druid-indexing-hadoop-0.9.0.jar:0.9.0]
	at io.druid.indexing.common.task.HadoopIndexTask$HadoopDetermineConfigInnerProcessing.runTask(HadoopIndexTask.java:291) ~[druid-indexing-service-0.9.0.jar:0.9.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:157) ~[druid-indexing-service-0.9.0.jar:0.9.0]
	... 7 more
```

With the patch, it appears hadoop-client cannot be found:
```
Caused by: java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream
	at io.druid.indexing.common.task.HadoopIndexTask$HadoopDetermineConfigInnerProcessing.runTask(HadoopIndexTask.java:277) ~[druid-indexing-service-0.9.0.jar:0.9.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:157) ~[druid-indexing-service-0.9.0.jar:0.9.0]
	... 7 more
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.FSDataInputStream
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_74]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_74]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_74]
	at io.druid.indexing.common.task.HadoopIndexTask$HadoopDetermineConfigInnerProcessing.runTask(HadoopIndexTask.java:277) ~[druid-indexing-service-0.9.0.jar:0.9.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:157) ~[druid-indexing-service-0.9.0.jar:0.9.0]
	... 7 more
```

**Comment by jon-wei** [comment]
Some more info

If I just take druid 0.9.0 and change the classloader map in Initialization to be keyed by File instead of "extension name", e.g.:
https://github.com/jon-wei/druid/commit/bfde13e890496e473fcb4c688bd11b2a4572c2be

then my batch ingestion job described in the previous comment succeeds.

-----

If I take this current patch, and restore the old implementation of   ```public static URLClassLoader getClassLoaderForExtension(File extension) throws MalformedURLException``` (with the individual file URLs), I no longer see hadoop-aws/hadoop-client related errors, but I get the following instead:

https://github.com/jon-wei/druid/commit/7ddbf55d71c4ec47a751431363c23ce58aa5a9af
```
2016-06-22T22:34:38,476 INFO [task-runner-0-priority-0] org.apache.hadoop.mapreduce.Job - Task Id : attempt_1466634772064_0001_m_000000_2, Status : FAILED
Error: com.metamx.common.ISE: Extension [/tmp/hadoop-root/nm-local-dir/usercache/root/appcache/application_1466634772064_0001/container_1466634772064_0001_01_000004/dist/druid/extensions/druid-histogram] specified in "druid.extensions.loadList" didn't exist!?
	at io.druid.initialization.Initialization.getExtensionFilesToLoad(Initialization.java:209)
	at io.druid.initialization.Initialization.getFromExtensions(Initialization.java:150)
	at io.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:327)
	at io.druid.indexer.HadoopDruidIndexerConfig.<clinit>(HadoopDruidIndexerConfig.java:98)
	at io.druid.indexer.HadoopDruidIndexerMapper.setup(HadoopDruidIndexerMapper.java:46)
	at io.druid.indexer.DetermineHashedPartitionsJob$DetermineCardinalityMapper.setup(DetermineHashedPartitionsJob.java:222)
	at io.druid.indexer.DetermineHashedPartitionsJob$DetermineCardinalityMapper.run(DetermineHashedPartitionsJob.java:279)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
```

**Comment by drcrallen** [comment]
@jon-wei grrr, looks like I don't have the right kind of tests around task launching to support this right now. I'll shrink down the scope to just the bug.

**Comment by jon-wei** [comment]
cool, :+1:

**Comment by drcrallen** [comment]
I accidentally deleted the test for the bug, I'll add that back "soon"

**Comment by jon-wei** [comment]
haha sounds good

**Comment by drcrallen** [comment]
@jon-wei  / @nishantmonu51 added test
