### PR TITLE
Atomic merge buffer acquisition for groupBys

### LINKED ISSUE #3819: groupBy v2: Deadlock on deeply nested subqueries
Deeply nested groupBys can cause deadlocks, because they require a separate merge buffer on the broker for each layer beyond the first layer of the groupBy. Since the merge buffers are limited in number and are acquired one-by-one, two problems can occur:

- Case 1: a nested groupBy needs X buffers but numMergeBuffers < X, so it can never get what it needs
- Case 2: two nested groupBys each need X buffers, but numMergeBuffers < X * 2 - 1, so it's possible for them to deadlock (both might get X - 1 buffers and then neither of them can get the final buffer).

Better behavior would be:

- Case 1: the query should fail
- Case 2: buffer acquisition should be atomic, so the queries can proceed without deadlocks

### PR DESCRIPTION
**Pull request by jihoonson**
This patch fixes #3819.
After this patch, when a group-by query is submitted, all needed merge buffers are first acquired atomically before query execution.

---
This change is [Reviewable](https://reviewable.io/reviews/druid-io/druid/3939)

### CODE REVIEW

File: processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+   *
+   * @return broker resource needed to execute the query
+   *
+   * @throws ResourceLimitExceededException if there isn't enough resources for query execution
+   */
+  public GroupByQueryBrokerResource prepare(GroupByQuery query)
+  {
+    final int requiredMergeBufferNum;
+    if (strategySelector.useStrategyV2(query)) {
+      final int groupByLayerNum = countGroupByLayers(query, 1);
```
Comment (jon-wei) [inline processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java]: I think this check could be simplified to just see if the top level query has a table datasource or inner query datasource, without needing to check the number of layers, since the buffer requirement is always 2 if layers > 1

**Comment by himanshug** [comment]
it looks like this will solve first case reported in #3819 too, however description seems to be very explicit about case two only. no ?

File: common/src/main/java/io/druid/collections/BlockingPool.java [hunk 2]
```diff
@@ -72,17 +80,53 @@ public BlockingPool(
           @Override
           public void close() throws IOException
           {
-            if (!objects.offer(theObject)) {
-              log.error("WTF?! Queue offer failed, uh oh...");
+            offer(theObject);
```
Comment (himanshug) [inline common/src/main/java/io/druid/collections/BlockingPool.java]: nit: not sure why simple logic is separated in to a method

File: processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java (hunk 1 above)
Comment (himanshug) [inline processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java]: +1

File: processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java [hunk 3]
```diff
@@ -84,22 +83,19 @@
...
-  private final StupidPool<ByteBuffer> bufferPool;
+  private final GroupByQueryBrokerResourceInitializer brokerResourceInitializer;
   private final IntervalChunkingQueryRunnerDecorator intervalChunkingQueryRunnerDecorator;
 
   @Inject
   public GroupByQueryQueryToolChest(
-      Supplier<GroupByQueryConfig> configSupplier,
       GroupByStrategySelector strategySelector,
-      @Global StupidPool<ByteBuffer> bufferPool,
+      GroupByQueryBrokerResourceInitializer brokerResourceInitializer,
```
Comment (himanshug) [inline processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java]: instead of adding this class, can't we just add prepare(..) method to GroupByQueryStrategy  and have that return the resource?

File: processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java [hunk 4]
```diff
@@ -0,0 +1,91 @@
...
+      requiredMergeBufferNum = Math.min(2, groupByLayerNum - 1);
```
Comment (jon-wei) [inline processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java]: Can you add a note or otherwise make it more clear that this GroupByQueryBrokerResource isn't used when running a non-nested query? It threw me off for a bit when I was looking at what happens when `requiredMergeBufferNum` is 0

File: processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java [hunk 5]
```diff
@@ -0,0 +1,91 @@
...
+    } else {
+      requiredMergeBufferNum = 0;
+    }
+
+    final ResourceHolder<List<ByteBuffer>> mergeBufferHolders = mergeBufferPool.drain(requiredMergeBufferNum);
+    if (mergeBufferHolders.get().size() < requiredMergeBufferNum) {
+      mergeBufferHolders.close();
+      throw new ResourceLimitExceededException("Cannot acquire enough merge buffers");
```
Comment (jon-wei) [inline processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java]: Failing the query here seems too aggressive to me, e.g.:

* Suppose there are two merge buffers, with a nested query A and a single-level query B
* Query B runs first, grabs one of the buffers
* Query A runs, with this query A would fail right there even though the query could be successfully executed if query A waited for query B to finish

I think the `ResourceLimitExceededException` should only be thrown if the number of buffers required by a single query exceeds the total number of buffers available, but not for the situation where a buffer is only temporarily unavailable

I think the query that needs more buffers than currently available should wait for the timeout set in the query before failing, for the nested queries that require > 2 this may need an atomic `checkAndDrain` method that grabs the ArrayBlockingQueue's lock and checks the size before either grabbing resources or waiting for a timeout

File: processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java (hunk 1 above)
Comment (jihoonson) [inline processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java]: Since brokers require merge buffers for processing the groupBy layers beyond the inner-most one, a nested groupBy (groupBy -> groupBy -> table) requires only a single merge buffer.
It can be still simplified by early exiting the count recursion (or loop) when the found number of groupBy layers becomes 2, but I wonder how worthwhile it is because most groupBys have very short depth.

File: common/src/main/java/io/druid/collections/BlockingPool.java (hunk 2 above)
Comment (jihoonson) [inline common/src/main/java/io/druid/collections/BlockingPool.java]: For avoiding the mistake to forget handling the case when ```offer()``` is failed. This case means there is a bug in returning unused resources. We are now simply logging an error message, but I think it should be improved.

File: processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java (hunk 3 above)
Comment (jihoonson) [inline processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java]: Thanks. It sounds good. I'll change.

File: processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java (hunk 4 above)
Comment (jihoonson) [inline processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java]: I'll add a note and improve the javadoc.

File: processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java (hunk 5 above)
Comment (jihoonson) [inline processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java]: Thanks for your suggestion. 
I think the case you mentioned is the problem of query scheduling. With query scheduling, when a query is submitted, it first waits for its turn until the resources are ready and other queries of higher priority complete.
However, timeout seems necessary in anyway. I'll add it soon.

Comment (jihoonson) [inline processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java]: @jon-wei, I simply added a timeout parameter to ```drain()``` method. I think it is better for now because adding ```checkSizeAndDrain``` method causes the below problems.
- This method requires for ```BlockingPool``` to maintain a lock itself, and thus the type of ```objects``` should be changed from BlockingQueue to something another to avoid unnecessary locking. 
- Even with ```checkSizeAndDrain``` method, the starvation problem still exists, so additional handling for that problem is required.

I think it would be better to redesign BlockingPool to address both problems, but it's not covered by this issue. So, how about opening a new issue for this?

**Comment by jihoonson** [comment]
@jon-wei, @himanshug thanks for your review. I addressed your comments. 

@himanshug, yes this PR covers the case 1 as well. I updated the pr description.

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByMergingQueryRunnerV2.java [hunk 6]
```diff
@@ -169,11 +169,11 @@ public GroupByMergingQueryRunnerV2(
                 // This will potentially block if there are no merge buffers left in the pool.
                 final long timeout = timeoutAt - System.currentTimeMillis();
                 if (timeout <= 0 || (mergeBufferHolder = mergeBufferPool.take(timeout)) == null) {
-                  throw new QueryInterruptedException(new TimeoutException());
+                  throw new TimeoutException();
```
Comment (himanshug) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByMergingQueryRunnerV2.java]: why this change? i think this is used to propagate issues properly from historicals to brokers

File: processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResource.java [hunk 7]
```diff
@@ -0,0 +1,93 @@
...
+import java.nio.ByteBuffer;
+import java.util.List;
+
+/**
+ * This class contains all resources required by the Broker during executing a group-by query.
+ * Currently, it contains only merge buffers, but any additional resources can be added in the future.
+ */
+public class GroupByQueryBrokerResource implements Closeable
+{
+  private static final EmittingLogger log = new EmittingLogger(GroupByQueryBrokerResource.class);
```
Comment (himanshug) [inline processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResource.java]: nit: don't really need the EmittingLogger

File: processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResource.java [hunk 8]
```diff
@@ -0,0 +1,93 @@
...
+   *
+   * @return a resource holder containing a merge buffer
+   *
+   * @throws IllegalStateException if this resource is not initialized with available merge buffers, or
+   *                               there isn't any available merge buffers
+   */
+  public ResourceHolder<ByteBuffer> getMergeBuffer()
+  {
+    Preconditions.checkState(mergeBuffers != null);
+    Preconditions.checkState(mergeBuffers.size() > 0);
```
Comment (himanshug) [inline processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResource.java]: Preconditions.checkState(mergeBuffer != null && mergeBuffers.size() > 0) ?

File: processing/src/main/java/io/druid/query/groupby/strategy/GroupByStrategySelector.java [hunk 9]
```diff
@@ -61,4 +61,14 @@ public GroupByStrategy strategize(GroupByQuery query)
         throw new ISE("No such strategy[%s]", strategyString);
     }
   }
+
+  public String getStrategy(GroupByQuery query)
+  {
+    return config.withOverrides(query).getDefaultStrategy();
+  }
+
+  public boolean useStrategyV2(GroupByQuery query)
```
Comment (himanshug) [inline processing/src/main/java/io/druid/query/groupby/strategy/GroupByStrategySelector.java]: not sure why is this introduced? who is using this

File: processing/src/main/java/io/druid/query/groupby/strategy/GroupByStrategySelector.java [hunk 10]
```diff
@@ -48,7 +48,7 @@ public GroupByStrategySelector(
 
   public GroupByStrategy strategize(GroupByQuery query)
   {
-    final String strategyString = config.withOverrides(query).getDefaultStrategy();
+    final String strategyString = getStrategy(query);
```
Comment (himanshug) [inline processing/src/main/java/io/druid/query/groupby/strategy/GroupByStrategySelector.java]: again, not sure if there is any advantage in separating this into a method

File: processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java (hunk 1 above)
Comment (himanshug) [inline processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java]: @jihoonson  even then we don't need to count beyond 3 layers

File: common/src/main/java/io/druid/collections/BlockingPool.java [hunk 11]
```diff
@@ -39,50 +43,117 @@
...
    * @param timeout maximum time to wait for a resource, in milliseconds. Negative means do not use a timeout.
    *
    * @return a resource, or null if the timeout was reached
+   */
+  public ReferenceCountingResourceHolder<T> take(final long timeout)
+  {
+    checkInitialized();
+    final T theObject;
+    try {
+      theObject = timeout >= 0 ? objects.poll(timeout, TimeUnit.MILLISECONDS) : objects.take();
```
Comment (himanshug) [inline common/src/main/java/io/druid/collections/BlockingPool.java]: timeout > 0 ?

File: processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java (hunk 5 above)
Comment (himanshug) [inline processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java]: @jihoonson @jon-wei with the timeout , it looks good to me ... I don't think `checkSizeAndDrain` is necessary
can we reduce the timeout when sending the query to historical since we already used some of the time that user allowed ?

Comment (jon-wei) [inline processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java]: Hm, without checking the size and draining atomically, two nested groupbys needing 2 buffers each could still in theory block each other:

* Suppose there are 2 buffers, and two nested queries are issued simultaneously,  the window for both acquiring one buffer and block each other should be much smaller now (from duration of subquery execution to the much shorter drainTo processing time)

* Suppose there are 2 free buffers, with two nested queries, but 1 buffer is currently in use by a non-nested query. Nested query A runs and drains one buffer, but waits for the second one. Nested query B also runs and sees no buffers, so it waits. Now suppose the non-nested query finishes and returns its buffer, but nested query B gets to run before nested query A, and takes the second buffer, leaving both nested queries blocked on each other

I'm okay with using this drain + timeout for now if that's the consensus, and opening a follow on issue about implementing truly atomic buffer acquisition coupled with something to address starvation issues for queries that need > 1 buffers

Comment (jihoonson) [inline processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java]: In the first case, you mean two queries needing 2 buffers can block each other even when there are 2 available buffers in the pool?

Anyway, yes, drain + timeout is not enough. I'll open a follow-up issue if others agree.

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByMergingQueryRunnerV2.java (hunk 6 above)
Comment (jihoonson) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByMergingQueryRunnerV2.java]: BlockingPool.take() now throws RuntimeException instead of InterruptedException, and the below ```catch``` block catches all kinds of exceptions and throws again with wrapping QueryInterruptedException (https://github.com/druid-io/druid/pull/3939/files/4f36f619bdfe5f7084913e77c583cf2f423d304a#diff-852ac93b1541cb9178ad922dc30be4baR176). This line causes QueryInterruptedException is wrapped twice unnecessarily, so I changed.

File: processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResource.java (hunk 8 above)
Comment (jihoonson) [inline processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResource.java]: The null mergeBuffers means this resource is initialized with 0 merge buffers, and mergeBuffers of size 0 means there remains no available merge buffers. I would like to make sure this.

File: processing/src/main/java/io/druid/query/groupby/strategy/GroupByStrategySelector.java (hunk 9 above)
Comment (jihoonson) [inline processing/src/main/java/io/druid/query/groupby/strategy/GroupByStrategySelector.java]: I forgot to remove. Thanks.

File: common/src/main/java/io/druid/collections/BlockingPool.java (hunk 11 above)
Comment (jihoonson) [inline common/src/main/java/io/druid/collections/BlockingPool.java]: 0 time means no wait.

File: processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java (hunk 5 above)
Comment (jihoonson) [inline processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java]: I'm curious why we don't simply use well-known libraries like netty. @gianm, would you share any reasons?

Comment (jon-wei) [inline processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResourceInitializer.java]: Sorry, scratch what I said about the first case, while the BlockingQueue `drainTo` method contract doesn't specify what happens with concurrent modifications while draining occurs, the ArrayBlockingQueue implementation does have a lock internally

File: common/src/main/java/io/druid/collections/BlockingPool.java (hunk 11 above)
Comment (leventov) [inline common/src/main/java/io/druid/collections/BlockingPool.java]: Why `take()` rather than `poll()`?

File: common/src/main/java/io/druid/collections/BlockingPool.java [hunk 12]
```diff
@@ -39,50 +43,117 @@
...
-        theObject,
+    checkInitialized();
+    final List<T> batch = Lists.newArrayListWithCapacity(maxElements);
+
+    try {
+      final int n = timeout >= 0 ?
+                    Queues.drain(objects, batch, maxElements, timeout, TimeUnit.MILLISECONDS) :
+                    objects.drainTo(batch, maxElements);
+      if (n < maxElements) {
+        if (log.isDebugEnabled()) {
```
Comment (leventov) [inline common/src/main/java/io/druid/collections/BlockingPool.java]: `log.isDebugEnabled()` is baked in `Logger` already, so suggested
```java
log.debug("Requested %d elements, but drained %d elements", maxElements, n);
```

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByRowProcessor.java [hunk 13]
```diff
@@ -133,17 +127,15 @@ public boolean apply(Row input)
           @Override
           public CloseableGrouperIterator<RowBasedKey, Row> make()
           {
-            final List<Closeable> closeOnFailure = Lists.newArrayList();
+            final List<Closeable> closeOnExit = Lists.newArrayList();
```
Comment (leventov) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByRowProcessor.java]: Why not using `Closer` for this?

File: processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResource.java [hunk 14]
```diff
@@ -0,0 +1,93 @@
...
+      }
+    };
+  }
+
+  @Override
+  public void close()
+  {
+    if (mergeBuffersHolder != null) {
+      if (mergeBuffers.size() != mergeBuffersHolder.get().size()) {
+        log.warn((mergeBuffersHolder.get().size() - mergeBuffers.size()) + " resources are not returned yet");
```
Comment (leventov) [inline processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResource.java]: Use log message formatting `%d`

File: processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResource.java [hunk 15]
```diff
@@ -0,0 +1,93 @@
...
+ * Currently, it contains only merge buffers, but any additional resources can be added in the future.
+ */
+public class GroupByQueryBrokerResource implements Closeable
+{
+  private static final Logger log = new Logger(GroupByQueryBrokerResource.class);
+
+  private final ResourceHolder<List<ByteBuffer>> mergeBuffersHolder;
+  private final List<ByteBuffer> mergeBuffers;
+
+  public GroupByQueryBrokerResource()
```
Comment (leventov) [inline processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResource.java]: What's the point of this constructor?

File: processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResource.java [hunk 16]
```diff
@@ -0,0 +1,93 @@
...
+   *
+   * @return a resource holder containing a merge buffer
+   *
+   * @throws IllegalStateException if this resource is not initialized with available merge buffers, or
+   *                               there isn't any available merge buffers
+   */
+  public ResourceHolder<ByteBuffer> getMergeBuffer()
+  {
+    Preconditions.checkState(mergeBuffers != null, "Resource is initialized with empty merge buffers");
+    Preconditions.checkState(mergeBuffers.size() > 0, "No available merge buffers");
```
Comment (leventov) [inline processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResource.java]: If using `ArrayDeque`, these two lines could be replaced with `buffer = mergeBuffers.pop()`

File: processing/src/main/java/io/druid/query/groupby/strategy/GroupByStrategyV2.java [hunk 17]
```diff
@@ -113,6 +123,57 @@ public static DateTime getUniversalTimestamp(final GroupByQuery query)
...
+        return new GroupByQueryBrokerResource();
+      } else {
+        final Number timeout = query.getContextValue(QueryContextKeys.TIMEOUT, JodaUtils.MAX_INSTANT);
+        final ResourceHolder<List<ByteBuffer>> mergeBufferHolders;
+
+        try {
+          mergeBufferHolders = mergeBufferPool.drain(requiredMergeBufferNum, timeout.longValue());
+          if (mergeBufferHolders.get().size() < requiredMergeBufferNum) {
+            mergeBufferHolders.close();
+            throw new TimeoutException("Cannot acquire enough merge buffers");
```
Comment (leventov) [inline processing/src/main/java/io/druid/query/groupby/strategy/GroupByStrategyV2.java]: Why TimeoutException? It's not a timeout. Maybe IllegalStateException

File: processing/src/main/java/io/druid/query/groupby/strategy/GroupByStrategyV2.java [hunk 18]
```diff
@@ -113,6 +123,57 @@ public static DateTime getUniversalTimestamp(final GroupByQuery query)
   }
 
   @Override
+  public GroupByQueryBrokerResource prepareResource(GroupByQuery query, boolean willMergeRunners)
+  {
+    if (!willMergeRunners) {
+      // Note: A broker requires merge buffers for processing the groupBy layers beyond the inner-most one.
```
Comment (leventov) [inline processing/src/main/java/io/druid/query/groupby/strategy/GroupByStrategyV2.java]: Please move this comment to `countRequiredMergeBufferNum()`

File: processing/src/main/java/io/druid/query/groupby/strategy/GroupByStrategyV2.java [hunk 19]
```diff
@@ -113,6 +123,57 @@ public static DateTime getUniversalTimestamp(final GroupByQuery query)
...
+          mergeBufferHolders = mergeBufferPool.drain(requiredMergeBufferNum, timeout.longValue());
+          if (mergeBufferHolders.get().size() < requiredMergeBufferNum) {
+            mergeBufferHolders.close();
+            throw new TimeoutException("Cannot acquire enough merge buffers");
+          } else {
+            return new GroupByQueryBrokerResource(mergeBufferHolders);
+          }
+        }
+        catch (Exception e) {
+          throw new QueryInterruptedException(e);
```
Comment (leventov) [inline processing/src/main/java/io/druid/query/groupby/strategy/GroupByStrategyV2.java]: Why `QueryInterruptedException`?

File: common/src/main/java/io/druid/collections/BlockingPool.java (hunk 12 above)
Comment (jihoonson) [inline common/src/main/java/io/druid/collections/BlockingPool.java]: Done.

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByRowProcessor.java (hunk 13 above)
Comment (jihoonson) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByRowProcessor.java]: It seems that the order of closing matters. I don't want to change it in this PR.

File: processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResource.java (hunk 15 above)
Comment (jihoonson) [inline processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResource.java]: This default constructor is used when any merge buffers are not required for groupBy execution.

I renamed to ```GroupByQueryResource``` which is more general name because druid's convention generally doesn't distinguish the broker side things and others. 
```GroupByQueryResource``` can be used by queryable nodes, i.e., brokers, historicals, and real times. However, currently it is used by only brokers to get merge buffers atomically if necessary. And, even in brokers, merge buffers are not used when the groupBy strategy v1 is used.

File: processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResource.java (hunk 16 above)
Comment (jihoonson) [inline processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResource.java]: Done.

File: processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResource.java (hunk 14 above)
Comment (jihoonson) [inline processing/src/main/java/io/druid/query/groupby/resource/GroupByQueryBrokerResource.java]: Done.

File: processing/src/main/java/io/druid/query/groupby/strategy/GroupByStrategyV2.java (hunk 18 above)
Comment (jihoonson) [inline processing/src/main/java/io/druid/query/groupby/strategy/GroupByStrategyV2.java]: Done.

File: processing/src/main/java/io/druid/query/groupby/strategy/GroupByStrategyV2.java (hunk 17 above)
Comment (jihoonson) [inline processing/src/main/java/io/druid/query/groupby/strategy/GroupByStrategyV2.java]: Changed to InsufficientResourcesException

File: processing/src/main/java/io/druid/query/groupby/strategy/GroupByStrategyV2.java (hunk 19 above)
Comment (jihoonson) [inline processing/src/main/java/io/druid/query/groupby/strategy/GroupByStrategyV2.java]: QueryInterruptedException is used for all kinds of failed queries.

**Comment by jihoonson** [comment]
@leventov thanks for your review. Addressed some of your comments.

I don't know why I can't add an inline reply for [your comment](https://github.com/druid-io/druid/pull/3939#discussion_r102354444). That part is not what I changed. I just changed that ```take()``` method throws a RuntimeException instead of an InterruptedException.

File: processing/src/main/java/io/druid/query/InsufficientResourcesException.java [hunk 20]
```diff
@@ -0,0 +1,31 @@
...
+ * specific language governing permissions and limitations
+ * under the License.
+ */
+
+package io.druid.query;
+
+/**
+ * This exception is thrown when the requested operation cannot be completed due to a lack of available resources.
+ */
+public class InsufficientResourcesException extends Exception
```
Comment (leventov) [inline processing/src/main/java/io/druid/query/InsufficientResourcesException.java]: Please make new exceptions to extend RuntimeException. Checked exceptions only force us to write more boilerplate, try-catch-throwables-propagate.

File: processing/src/main/java/io/druid/query/groupby/strategy/GroupByStrategyV2.java [hunk 21]
```diff
@@ -60,20 +61,21 @@
...
 import java.util.List;
 import java.util.Map;
-import java.util.concurrent.TimeoutException;
 
 public class GroupByStrategyV2 implements GroupByStrategy
 {
   public static final String CTX_KEY_FUDGE_TIMESTAMP = "fudgeTimestamp";
   public static final String CTX_KEY_OUTERMOST = "groupByOutermost";
 
+  private static final int MAX_MERGE_BUFFER_NUM = 2;
```
Comment (leventov) [inline processing/src/main/java/io/druid/query/groupby/strategy/GroupByStrategyV2.java]: Worth adding at least "see countRequiredMergeBufferNum() for explanation" comment, or move part of countRequiredMergeBufferNum()'s comment to this constant

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByRowProcessor.java (hunk 13 above)
Comment (leventov) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByRowProcessor.java]: Please leave a comment explaining this in the code.

**Comment by leventov** [comment]
@jihoonson and about `poll` vs `take()` - before you explained, that timeout 0 means "no wait", but `take()` is blocking.

File: common/src/main/java/io/druid/collections/BlockingPool.java (hunk 12 above)
Comment (leventov) [inline common/src/main/java/io/druid/collections/BlockingPool.java]: Not changed

Comment (jihoonson) [inline common/src/main/java/io/druid/collections/BlockingPool.java]: Sorry. Changed.

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByRowProcessor.java (hunk 13 above)
Comment (jihoonson) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByRowProcessor.java]: Left a comment.

File: processing/src/main/java/io/druid/query/InsufficientResourcesException.java (hunk 20 above)
Comment (jihoonson) [inline processing/src/main/java/io/druid/query/InsufficientResourcesException.java]: Changed.

File: processing/src/main/java/io/druid/query/groupby/strategy/GroupByStrategyV2.java (hunk 21 above)
Comment (jihoonson) [inline processing/src/main/java/io/druid/query/groupby/strategy/GroupByStrategyV2.java]: Added.

**Comment by jihoonson** [comment]
@leventov ah, I got your point. That's also not what I changed, but I clarified it.

**Comment by jihoonson** [comment]
@jon-wei I simply added a new ```takeBatch()``` method to BlockingPool which is ```checkAndDrain()``` you mentioned. After thinking about this for a while, I decided to add it because this issue focuses on guaranteeing the atomicity when acquiring merge buffers, and it cannot be achieved without ```takeBatch()```. But I still believe that we need to improve and maybe redesign BlockingPool.

Sorry for going back and forth. Would you and other reviewers @himanshug @leventov mind reviewing again please?

**Comment by gianm** [comment]
Hmm, travis has been done for a while but the PR hasn't figured that out yet. Going to bounce it to see if that helps.

**Comment by himanshug** [comment]
:+1:

**Comment by jihoonson** [comment]
@himanshug thank you for the review and merge.
@gianm @leventov @jon-wei if you have more comments on the newly added part, please feel free to tell me. I'll do in a follow-up pr.
