### PR TITLE
KafkaLookupExtractorFactory: shutdown kafka consumer on close()

### LINKED ISSUE #3531: Kafka indexing fails to stop correctly in 0.9.2rc1
**Steps to reproduce:**

1. Create a [kafka indexer](http://druid.io/docs/0.9.1.1/development/extensions-core/kafka-ingestion.html)
2. Wait for a kafka index task to start
3. Emulate a `/stop` request sent from supervisor to worker, e.g. via
```
http post localhost:8100/druid/worker/v1/chat/index_kafka_Example_0f2f4bbb5f488f3_mjmpbfek/stop
```

**Expected behavior:**
Worker successfully stops

**Actual behavior:**
Worker process remains lingering until middle manager forcefully kills the process after timeout. The following exception is seen in the logs:

```
2016-10-04T13:16:56,181 ERROR [task-runner-0-priority-0] io.druid.indexing.overlord.ThreadPoolTaskRunner - Exception while running task[KafkaIndexTask{id=index_kafka_Example_0f2f4bbb5f488f3_mjmpbfek, type=index_kafka, dataSource=Example}]
java.util.concurrent.RejectedExecutionException: Got Interrupted while adding to the Queue
	at io.druid.concurrent.Execs$1.rejectedExecution(Execs.java:123) ~[druid-common-0.9.2-rc1.jar:0.9.2-rc1]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) ~[?:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369) ~[?:1.8.0_102]
	at com.google.common.util.concurrent.MoreExecutors$ListeningDecorator.execute(MoreExecutors.java:484) ~[guava-16.0.1.jar:?]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) ~[?:1.8.0_102]
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:58) ~[guava-16.0.1.jar:?]
	at io.druid.segment.realtime.appenderator.AppenderatorImpl.persistAll(AppenderatorImpl.java:377) ~[druid-server-0.9.2-rc1.jar:0.9.2-rc1]
	at io.druid.segment.realtime.appenderator.AppenderatorImpl.add(AppenderatorImpl.java:218) ~[druid-server-0.9.2-rc1.jar:0.9.2-rc1]
	at io.druid.segment.realtime.appenderator.FiniteAppenderatorDriver.add(FiniteAppenderatorDriver.java:199) ~[druid-server-0.9.2-rc1.jar:0.9.2-rc1]
	at io.druid.indexing.kafka.KafkaIndexTask.run(KafkaIndexTask.java:416) ~[?:?]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:436) [druid-indexing-service-0.9.2-rc1.jar:0.9.2-rc1]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:408) [druid-indexing-service-0.9.2-rc1.jar:0.9.2-rc1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
2016-10-04T13:16:56,284 INFO [task-runner-0-priority-0] io.druid.indexing.overlord.TaskRunnerUtils - Task [index_kafka_Example_0f2f4bbb5f488f3_mjmpbfek] status changed to [FAILED].
2016-10-04T13:16:56,293 INFO [task-runner-0-priority-0] io.druid.indexing.worker.executor.ExecutorLifecycle - Task completed with status: {
  "id" : "index_kafka_Example_0f2f4bbb5f488f3_mjmpbfek",
  "status" : "FAILED",
  "duration" : 1811725
}
```

---

This does not happen every time, but in about 70% of the cases so far. This issue is quite similar to https://github.com/druid-io/druid/issues/3346, except that this time the lookups do not have anything to do with it.

As I understand, `KafkaIndexTask` attempts to persist everything to `FiniteAppenderatorDriver`, but since the peon is being shut down, submitting a task in `AppenderatorImpl.persistAll` gets rejected.

I do not yet see what change could have caused it, but we do not observe the issue in 0.9.1.1. Any ideas? This would be a show-stopper for upgrading to 0.9.2 for anyone using kafka ingestion.

### PR DESCRIPTION
**Pull request by dclim**
This call:

```
for (final MessageAndMetadata<String, String> messageAndMetadata : kafkaStream) {
```
never exits until the Kafka consumer is shutdown (or consumer.timeout.ms elapses). The consumer needs to be signaled to shutdown in close() so that the for loop exits and our Runnable can terminate, otherwise the JVM will not exit (the ConsumerFetcherThread created by the Kafka consumer is non-daemon).

This fixes #3531

### CODE REVIEW

File: extensions-core/kafka-extraction-namespace/src/main/java/io/druid/query/lookup/KafkaLookupExtractorFactory.java [hunk 1]
```diff
@@ -194,7 +195,7 @@ public boolean start()
             public void run()
             {
               while (!executorService.isShutdown()) {
-                final ConsumerConnector consumerConnector = buildConnector(kafkaProperties);
+                consumerConnector = buildConnector(kafkaProperties);
```
Comment (drcrallen) [inline extensions-core/kafka-extraction-namespace/src/main/java/io/druid/query/lookup/KafkaLookupExtractorFactory.java]: Since this is in some other executor service and not guarded, there is a race condition here where `close()` can be in flight when it reaches here, missing the connector opening.

The catch here is that the `start()` method awaits this code path to make a certain level of progress, so that coordination would need to be taken account for in whatever race-condition prevention is used here.

Comment (dclim) [inline extensions-core/kafka-extraction-namespace/src/main/java/io/druid/query/lookup/KafkaLookupExtractorFactory.java]: @drcrallen can you describe the race condition in more detail? from what I can see, the `synchronized(started)` along with `start()` not releasing the lock until after `startingReads` is cleared should prevent missing the connector opening.

Comment (drcrallen) [inline extensions-core/kafka-extraction-namespace/src/main/java/io/druid/query/lookup/KafkaLookupExtractorFactory.java]: If the loop `while (!executorService.isShutdown())` is looping while stop is called, `consumerConnector` can be created and assigned after it reaches `if (consumerConnector != null) {` in the `close()` method

Comment (dclim) [inline extensions-core/kafka-extraction-namespace/src/main/java/io/druid/query/lookup/KafkaLookupExtractorFactory.java]: @drcrallen makes sense, is there any particular reason buildConnector needs to be in the loop or can we just create the ConsumerConnector once on start?

Comment (drcrallen) [inline extensions-core/kafka-extraction-namespace/src/main/java/io/druid/query/lookup/KafkaLookupExtractorFactory.java]: Quite simply, this tries to rebuild a connection on whatever error may have been thrown. For example, if a broker goes down and a new consumer needs to be setup to a new broker.

**Comment by gvsmirnov** [comment]
I can confirm that with a version built from this branch, the issue I reported in #3531 no longer reproduces. Yay! 🎉

**Comment by dclim** [comment]
@drcrallen any more comments on this PR?

**Comment by dclim** [comment]
@drcrallen any more comments on this PR?

File: extensions-core/kafka-extraction-namespace/src/main/java/io/druid/query/lookup/KafkaLookupExtractorFactory.java (hunk 1 above)
Comment (gianm) [inline extensions-core/kafka-extraction-namespace/src/main/java/io/druid/query/lookup/KafkaLookupExtractorFactory.java]: I think the race is still there:

1. kafka lookup thingy is running happily for a while
2. executor thread's consumer crashes, it re-loops to the top of the `while` 
3. executor thread checks `executorService.isShutdown()`, finds it's false and continues into the body
4. close is called in some other thread
5. close thread calls `executorService.shutdown()`
6. close thread closes a `consumerConnector` from a previous loop of the executor
7. executor thread creates a new consumerConnector and does its thing, never exiting

I think this can be addressed by having close call `shutdownNow` instead of `shutdown`, and the executor thread exiting if interrupted (rather than re-looping) by (a) exiting on InterruptedException, (b) checking for interrupt flag on each message read.

Comment (dclim) [inline extensions-core/kafka-extraction-namespace/src/main/java/io/druid/query/lookup/KafkaLookupExtractorFactory.java]: @gianm isn't this what would actually happen?
...
6. close thread closes a `consumerConnector` from a previous loop of the executor
7. executor thread creates a new consumerConnector
8. the check for `executorService.isShutdown()` returns true and we break from the loop
9. the finally block executes and the new consumerConnector created in 7 is closed

Comment (gianm) [inline extensions-core/kafka-extraction-namespace/src/main/java/io/druid/query/lookup/KafkaLookupExtractorFactory.java]: (8) will not happen, because at that point the executor thread will be in the loop over `for (... : kafkaStream)` which is an infinite loop and does not contain any checking for shutdown.

So I think that loop needs to check for the executor service being stopped. I also think a `shutdownNow` is still called for, since the `kafkaStream` iterator may block forever if no new messages are forthcoming in the Kafka topic, and that needs to be dealt with. It's probably a likely situation for a lookup oriented topic to be in, since I bet new messages may not come very often.

Comment (gianm) [inline extensions-core/kafka-extraction-namespace/src/main/java/io/druid/query/lookup/KafkaLookupExtractorFactory.java]: Ah, okay, nevermind, I see what you're saying. The check for isShutdown happens again after creating the connector and that prevents the race. I missed that check when I was looking at the diff, thanks for explaining it.

**Comment by navis** [comment]
@dclim Now it's complaining it's called 3 times instead of 2. Could you check that?

https://travis-ci.org/druid-io/druid/jobs/170028487
https://travis-ci.org/druid-io/druid/jobs/170029074
https://travis-ci.org/druid-io/druid/jobs/170029747

occurs only in JDK8. interesting..

**Comment by dclim** [comment]
@navis there was a timing issue in the test, should be fixed in #3604
