### PR TITLE
Fix #2782, Unit test failed for DruidProcessingConfigTest.testDeserialization

### LINKED ISSUE #2782: Unit test failed for DruidProcessingConfigTest.testDeserialization
Hi,

Unit test failed for DruidProcessingConfigTest.testDeserialization. Did any one faced this issue?

Stack Trace:
sts: 
  DruidProcessingConfigTest.testDeserialization:45 null

Tests run: 9551, Failures: 1, Errors: 0, Skipped: 13

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] io.druid:druid .................................... SUCCESS [12.957s]
[INFO] druid-api ......................................... SUCCESS [3:15.808s]
[INFO] druid-common ...................................... SUCCESS [1:52.465s]
[INFO] druid-processing .................................. FAILURE [27:07.759s]
[INFO] druid-aws-common .................................. SKIPPED
[INFO] druid-server ...................................... SKIPPED
[INFO] druid-examples .................................... SKIPPED
[INFO] druid-indexing-hadoop ............................. SKIPPED
[INFO] druid-indexing-service ............................ SKIPPED
[INFO] druid-services .................................... SKIPPED
[INFO] druid-s3-extensions ............................... SKIPPED
[INFO] druid-datasketches ................................ SKIPPED
[INFO] druid-kafka-eight ................................. SKIPPED
[INFO] druid-histogram ................................... SKIPPED
[INFO] mysql-metadata-storage ............................ SKIPPED
[INFO] druid-integration-tests ........................... SKIPPED
[INFO] druid-benchmarks .................................. SKIPPED
[INFO] druid-avro-extensions ............................. SKIPPED
[INFO] druid-hdfs-storage ................................ SKIPPED
[INFO] druid-namespace-lookup ............................ SKIPPED
[INFO] druid-kafka-extraction-namespace .................. SKIPPED
[INFO] druid-kafka-indexing-service ...................... SKIPPED
[INFO] postgresql-metadata-storage ....................... SKIPPED
[INFO] druid-azure-extensions ............................ SKIPPED
[INFO] druid-cassandra-storage ........................... SKIPPED
[INFO] druid-rocketmq .................................... SKIPPED
[INFO] druid-cloudfiles-extensions ....................... SKIPPED
[INFO] graphite-emitter .................................. SKIPPED
[INFO] druid-kafka-eight-simple-consumer ................. SKIPPED
[INFO] druid-rabbitmq .................................... SKIPPED
[INFO] druid-distinctcount ............................... SKIPPED
[INFO] druid-parquet-extensions .......................... SKIPPED
[INFO] distribution ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 32:44.532s
[INFO] Finished at: Sat Apr 02 22:38:09 PDT 2016
[INFO] Final Memory: 28M/165M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project druid-processing: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/cloudera/git/druid/processing/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :druid-processing

### PR DESCRIPTION
**Pull request by erikdubbelboer**
On systems with only once processor this test fails. Systems with 2 processors are fine.

### CODE REVIEW

File: processing/src/test/java/io/druid/query/DruidProcessingConfigTest.java [hunk 1]
```diff
@@ -42,7 +42,9 @@ public void testDeserialization() throws Exception
 
     Assert.assertEquals(1024 * 1024 * 1024, config.intermediateComputeSizeBytes());
     Assert.assertEquals(Integer.MAX_VALUE, config.poolCacheMaxCount());
-    Assert.assertTrue(config.getNumThreads() < Runtime.getRuntime().availableProcessors());
+    if (Runtime.getRuntime().availableProcessors() > 1) {
+      Assert.assertTrue(config.getNumThreads() < Runtime.getRuntime().availableProcessors());
+    }
```
Comment (nishantmonu51) [inline processing/src/test/java/io/druid/query/DruidProcessingConfigTest.java]: it would be nice to also assert that numThreads is 1 when available processors is 1

**Comment by gianm** [comment]
@erikdubbelboer this looks good to me with @nishantmonu51's suggestion.

**Comment by erikdubbelboer** [comment]
Done. I think it can be merged now.

**Comment by gianm** [comment]
👍
