### PR TITLE
Throw away rows with timestamps beyond long bounds in kafka indexing

### LINKED ISSUE #4485: Kafka indexing service confused by the distant future
Timestamps after `JodaUtils.MAX_INSTANT` cause strange behavior. Example stack trace is below. I'm not exactly sure what went wrong here (probably some kind of overflow?). I think we should simply treat these out of range timestamps as unparseable rows.

```
2017-06-26T19:23:43,774 INFO [qtp1146045637-133] io.druid.indexing.common.actions.LocalTaskActionClient - Performing action for task[index_kafka_XXX_14759287c3f3b7b_hjehimnb]: SegmentAllocateAction{dataSource='XXX', timestamp=213484092-10-22T10:45:15.392Z, queryGranularity={type=period, period=PT1M, timeZone=UTC, origin=null}, preferredSegmentGranularity={type=period, period=P1D, timeZone=UTC, origin=null}, sequenceName='index_kafka_XXX_14759287c3f3b7b_10', previousSegmentId='XXX_10031072-10-16T00:00:00.000Z_10031072-10-17T00:00:00.000Z_2017-06-22T22:47:52.070Z_1'}
2017-06-26T19:23:43,832 ERROR [qtp1146045637-133] com.sun.jersey.spi.container.ContainerResponse - The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
java.lang.IllegalArgumentException: The end instant must be greater or equal to the start
      at org.joda.time.base.AbstractInterval.checkInterval(AbstractInterval.java:63) ~[joda-time-2.8.2.jar:2.8.2]
      at org.joda.time.base.BaseInterval.<init>(BaseInterval.java:94) ~[joda-time-2.8.2.jar:2.8.2]
      at org.joda.time.Interval.<init>(Interval.java:122) ~[joda-time-2.8.2.jar:2.8.2]
```

### PR DESCRIPTION
**Pull request by jon-wei**
Fixes #4485

### CODE REVIEW

File: extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/KafkaIndexTask.java [hunk 1]
```diff
@@ -2015,6 +2016,11 @@ private boolean withinMinMaxRecordTime(final InputRow row)
     final boolean afterMaximumMessageTime = ioConfig.getMaximumMessageTime().isPresent()
                                             && ioConfig.getMaximumMessageTime().get().isBefore(row.getTimestamp());
 
+    if (!Intervals.ETERNITY.contains(row.getTimestamp())) {
+      log.error("Encountered row with timestamp that cannot be represented as a long: [%s]", row);
```
Comment (jihoonson) [inline extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/KafkaIndexTask.java]: This probably emits too many logs?

File: extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/KafkaIndexTask.java [hunk 2]
```diff
@@ -2015,6 +2016,11 @@ private boolean withinMinMaxRecordTime(final InputRow row)
...
+      return false;
+    }
```
Comment (nishantmonu51) [inline extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/KafkaIndexTask.java]: how about reporting it as ParseException in case user has set reportParseExceptions to true ?

File: extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/KafkaIndexTask.java (hunk 1 above)
Comment (jon-wei) [reply extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/KafkaIndexTask.java]: changed this to log.debug instead

File: extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/KafkaIndexTask.java (hunk 2 above)
Comment (jon-wei) [reply extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/KafkaIndexTask.java]: changed this to throw a ParseException if reportParseExceptions is true
