### PR TITLE
Make hadoop classpath isolation more explicit

### LINKED ISSUE #2428: HadoopTask does not load extension jars into isolated classpath
HadoopTask's creation of the isolated classloader creation finds the extension jar URLs but does not actually use them in the classloader. It instead simply includes them as dependent jars.

As such any extension classes used in runTask will fail since they are not in the isolated classloader.

### PR DESCRIPTION
**Pull request by drcrallen**
* Fixes #2428 
* Also fixes messy pull deps

I confirmed this locally against https://github.com/metamx/druid-spark-batch/tree/v0.0.27 running on a local mesos master/slave^H^H^H^H^Hagent

### CODE REVIEW

File: indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java [hunk 1]
```diff
@@ -84,27 +107,35 @@ protected ClassLoader buildClassLoader(final TaskToolbox toolbox) throws Excepti
...
             extensionsConfig
         )) {
       final ClassLoader hadoopLoader = Initialization.getClassLoaderForExtension(hadoopDependency);
-      driverURLs.addAll(Arrays.asList(((URLClassLoader) hadoopLoader).getURLs()));
+      classLoader = new URLClassLoader(((URLClassLoader) hadoopLoader).getURLs(), classLoader);
     }
 
-    final URLClassLoader loader = new URLClassLoader(driverURLs.toArray(new URL[driverURLs.size()]), null);
+    classLoader = new URLClassLoader(druidURLs.toArray(new URL[druidURLs.size()]), classLoader);
+    classLoader = new URLClassLoader(extensionURLs.toArray(new URL[extensionURLs.size()]), classLoader);
```
Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java]: @gianm this is the step that was missing.

**Comment by xvrl** [comment]
:+1: once travis passes

File: services/src/main/java/io/druid/cli/PullDependencies.java [hunk 2]
```diff
@@ -65,7 +65,38 @@
 
   private static final Set<String> exclusions = Sets.newHashSet(
       "io.druid",
-      "com.metamx.druid"
+      "com.metamx.druid",
+
+      // These should be included by druid and not pulled down in extensions
```
Comment (xvrl) [inline services/src/main/java/io/druid/cli/PullDependencies.java]: how does one determine what needs to be excluded here?

**Comment by xvrl** [comment]
I'm a bit concerned with the maintenance required on the list of things to exclude. Unless it's somehow automated we are bound to forget to update it

**Comment by drcrallen** [comment]
@xvrl it won't be worse than it currently is

File: services/src/main/java/io/druid/cli/PullDependencies.java (hunk 2 above)
Comment (drcrallen) [inline services/src/main/java/io/druid/cli/PullDependencies.java]: trial and error

Comment (drcrallen) [inline services/src/main/java/io/druid/cli/PullDependencies.java]: More explicitly, this came about through exploration of myself and @hbutani on how to get https://github.com/metamx/druid-spark-batch/blob/master/build.sbt to work

File: indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java [hunk 3]
```diff
@@ -69,6 +74,24 @@ protected HadoopTask(
...
+  {
+    @Override
+    public boolean apply(@Nullable URL input)
+    {
+      try {
+        if (input == null) {
+          return false;
+        }
+        final String fName = Paths.get(input.toURI()).getFileName().toString();
+        return fName.startsWith("druid") && fName.endsWith(".jar");
```
Comment (gianm) [inline indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java]: is there any way this can be more robust?

I'm imagining one day someone having a bad time because their extension depends on a jar called "druid-mything-adapter.jar"

Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java]: That's a great question. I couldn't think of a better way. If you have any good suggestions I'd love to hear them.

Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java]: This essentially splits the jars between "before hadoop classloader" and "after hadoop classloader"
where the druid jars come after the hadoop classloader

Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java]: Just realized it doesn't give the druid URLs to hadoop

I can't remember right now where the druid jars are included.

Comment (gianm) [inline indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java]: Nothing better really comes to mind, but I haven't spent that much time thinking about this.

File: indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java [hunk 4]
```diff
@@ -84,27 +107,35 @@ protected ClassLoader buildClassLoader(final TaskToolbox toolbox) throws Excepti
     final List<URL> nonHadoopURLs = Lists.newArrayList();
     nonHadoopURLs.addAll(Arrays.asList(((URLClassLoader) HadoopIndexTask.class.getClassLoader()).getURLs()));
 
-    final List<URL> driverURLs = Lists.newArrayList();
-    driverURLs.addAll(nonHadoopURLs);
+    final List<URL> druidURLs = ImmutableList.copyOf(
```
Comment (gianm) [inline indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java]: how do the druidURLs get added to the hadoop job classpath?

File: indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java [hunk 5]
```diff
@@ -84,27 +107,35 @@ protected ClassLoader buildClassLoader(final TaskToolbox toolbox) throws Excepti
...
+    );
+    final List<URL> nonDruidURLs = Lists.newArrayList(nonHadoopURLs);
+    nonDruidURLs.removeAll(druidURLs);
+
+    // Start from a fresh slate
+    ClassLoader classLoader = null;
+    classLoader = new URLClassLoader(nonDruidURLs.toArray(new URL[nonDruidURLs.size()]), classLoader);
 
-    // put hadoop dependencies last to avoid jets3t & apache.httpcore version conflicts
+    // hadoop dependencies come before druid classes because some extensions depend on them
```
Comment (himanshug) [inline indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java]: not sure why hadoop dependencies has to appear first, what breaks?

File: services/src/main/java/io/druid/cli/PullDependencies.java (hunk 2 above)
Comment (himanshug) [inline services/src/main/java/io/druid/cli/PullDependencies.java]: not sure how this will be kept up-to-date. does something go wrong if these are not excluded ?

**Comment by himanshug** [comment]
@drcrallen the part that fixes #2428 by including extensionUrls in the classloader looks ok.

File: indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java (hunk 3 above)
Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java]: problem is the files are just files, so we can either actually parse the jar and find information, or use the filename to guess information.

File: services/src/main/java/io/druid/cli/PullDependencies.java (hunk 2 above)
Comment (drcrallen) [inline services/src/main/java/io/druid/cli/PullDependencies.java]: Potentially a jar is included in the hadoop jar list in the wrong order.

File: indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java (hunk 5 above)
Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java]: Indexing service depends on hadoop Indexing

File: indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java (hunk 4 above)
Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java]: I'll double check. May have missed a collection to add at the end

Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java]: jars added to the Job are nonHadoopURLs

The nonHadoopURLs are split into druidURLs and nonDruidURLs which are only used in the ClassLoader for launching the job via runTask.

File: indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java [hunk 6]
```diff
@@ -84,27 +107,35 @@ protected ClassLoader buildClassLoader(final TaskToolbox toolbox) throws Excepti
     final List<URL> nonHadoopURLs = Lists.newArrayList();
     nonHadoopURLs.addAll(Arrays.asList(((URLClassLoader) HadoopIndexTask.class.getClassLoader()).getURLs()));
 
-    final List<URL> driverURLs = Lists.newArrayList();
-    driverURLs.addAll(nonHadoopURLs);
+    final List<URL> druidURLs = ImmutableList.copyOf(
+        Collections2.filter(nonHadoopURLs, IS_DRUID_URL)
+    );
+    final List<URL> nonDruidURLs = Lists.newArrayList(nonHadoopURLs);
```
Comment (gianm) [inline indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java]: nonHadoopNonDruidURLs? :)

**Comment by drcrallen** [comment]
@himanshug / @gianm I think I addressed comments. Please let me know if there are any more

File: indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java (hunk 3 above)
Comment (gianm) [inline indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java]: hmm, perhaps just adding a comment about the name situation is enough.

**Comment by gianm** [comment]
@drcrallen couple minor ones (comments & var naming). I tried this on EMR and it worked. :+1: from me

**Comment by himanshug** [comment]
:+1: with the new comments in pull dependencies exclusion list.

File: services/src/main/java/io/druid/cli/PullDependencies.java [hunk 7]
```diff
@@ -65,7 +65,47 @@
...
+      // Note to future developers: This list is hand-crafted and will probably be out of date in the future
+      // A good way to know where to look for errant dependencies is to compare the lib/ directory in the distribution
+      // tarball with the jars included in the extension directories.
+      //
+      // This list is best-effort, and might still pull down more than desired.
+      //
+      // Different tasks which are classloader sensitive attempt to maintain a sane order for loading libraries in the
+      // classloader, but it is always possible that something didn't load in the right order. Also we don't want to be
```
Comment (xvrl) [inline services/src/main/java/io/druid/cli/PullDependencies.java]: can we explain what  "right order" means and under what circumstances something should be included / excluded, and why? What does "classloader sensitive" mean? A concrete example would be welcome.

File: services/src/main/java/io/druid/cli/PullDependencies.java [hunk 8]
```diff
@@ -65,7 +65,47 @@
...
       "io.druid",
-      "com.metamx.druid"
+      "com.metamx.druid",
+
+      // These should be included by druid and not pulled down in extensions
+      // Note to future developers: This list is hand-crafted and will probably be out of date in the future
+      // A good way to know where to look for errant dependencies is to compare the lib/ directory in the distribution
+      // tarball with the jars included in the extension directories.
+      //
+      // This list is best-effort, and might still pull down more than desired.
```
Comment (xvrl) [inline services/src/main/java/io/druid/cli/PullDependencies.java]: why are things not "desired" ? An explanation on the problem and what causes it would be more helpful and just an off-handed comment about something not being desired.

**Comment by drcrallen** [comment]
@xvrl added even more explanation

File: services/src/main/java/io/druid/cli/PullDependencies.java (hunk 7 above)
Comment (drcrallen) [inline services/src/main/java/io/druid/cli/PullDependencies.java]: added

**Comment by xvrl** [comment]
:+1:

**Comment by guobingkun** [comment]
@drcrallen I am getting this error after applying this patch.
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-16.0.1.jar:?]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:170) ~[classes/:?]
	at io.druid.indexing.common.task.HadoopIndexTask.run(HadoopIndexTask.java:175) ~[classes/:?]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:338) [classes/:?]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:318) [classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:167) ~[classes/:?]
	... 7 more
Caused by: java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream
	at io.druid.indexing.common.task.HadoopIndexTask$HadoopDetermineConfigInnerProcessing.runTask(HadoopIndexTask.java:277) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:167) ~[classes/:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.FSDataInputStream
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_45]
	at io.druid.indexing.common.task.HadoopIndexTask$HadoopDetermineConfigInnerProcessing.runTask(HadoopIndexTask.java:277) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:167) ~[classes/:?]
	... 7 more
2016-02-16T19:28:21,964 INFO [task-runner-0-priority-0] io.druid.indexing.worker.executor.ExecutorLifecycle - Task completed with status: {
  "id" : "index_hadoop_basefact_network_2016-02-16T19:28:18.853Z",
  "status" : "FAILED",
  "duration" : 39
}
```

**Comment by rasahner** [comment]
And in our test environment, I'm seeing this in a test that does a hadoop indexing task:
2016-02-16T17:39:22,054 INFO [task-runner-0-priority-0] io.druid.guice.JsonConfigurator - Loaded class[class io.druid.guice.ExtensionsConfig] from props[druid.extensions.] as [ExtensionsConfig{searchCurrentClassloader=true, directory='extensions', hadoopDependenciesDir='hadoop-dependencies', loadList=null}]
2016-02-16 17:39:22,075 task-runner-0-priority-0 ERROR Recursive call to appender Console
2016-02-16 17:39:22,096 task-runner-0-priority-0 ERROR Recursive call to appender Console
2016-02-16 17:39:22,098 task-runner-0-priority-0 ERROR Recursive call to appender Console
2016-02-16 17:39:22,099 task-runner-0-priority-0 ERROR Recursive call to appender Console
Feb 16, 2016 5:39:22 PM com.google.inject.servlet.GuiceFilter setPipeline
WARNING: Multiple Servlet injectors detected. This is a warning indicating that you have more than one GuiceFilter running in your web application. If this is deliberate, you may safely ignore this message. If this is NOT deliberate however, your application may not work as expected.
2016-02-16T17:39:22,062 ERROR [task-runner-0-priority-0] io.druid.indexing.overlord.ThreadPoolTaskRunner - Exception while running task[HadoopIndexTask{id=index_hadoop_basefact_network_2016-02-16T17:39:12.771Z, type=index_hadoop, dataSource=basefact_network}]
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-16.0.1.jar:?]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:170) ~[druid-indexing-service-0.9.0-1455643294-b1f90f4-2.jar:0.9.0-1455643294-b1f90f4-2]
	at io.druid.indexing.common.task.HadoopIndexTask.run(HadoopIndexTask.java:175) ~[druid-indexing-service-0.9.0-1455643294-b1f90f4-2.jar:0.9.0-1455643294-b1f90f4-2]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:338) [druid-indexing-service-0.9.0-1455643294-b1f90f4-2.jar:0.9.0-1455643294-b1f90f4-2]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:318) [druid-indexing-service-0.9.0-1455643294-b1f90f4-2.jar:0.9.0-1455643294-b1f90f4-2]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:167) ~[druid-indexing-service-0.9.0-1455643294-b1f90f4-2.jar:0.9.0-1455643294-b1f90f4-2]
	... 7 more
Caused by: java.lang.NoClassDefFoundError: io/druid/initialization/DruidModule
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_60]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_60]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_60]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_60]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_60]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_60]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_60]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_60]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_60]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_60]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_60]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370) ~[?:1.8.0_60]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[?:1.8.0_60]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[?:1.8.0_60]
	at io.druid.initialization.Initialization.getFromExtensions(Initialization.java:133) ~[druid-server-0.9.0-1455643294-b1f90f4-2.jar:0.9.0-1455643294-b1f90f4-2]
	at io.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:320) ~[druid-server-0.9.0-1455643294-b1f90f4-2.jar:0.9.0-1455643294-b1f90f4-2]
	at io.druid.indexer.HadoopDruidIndexerConfig.<clinit>(HadoopDruidIndexerConfig.java:98) ~[druid-indexing-hadoop-0.9.0-1455643294-b1f90f4-2.jar:0.9.0-1455643294-b1f90f4-2]
	at io.druid.indexing.common.task.HadoopIndexTask$HadoopDetermineConfigInnerProcessing.runTask(HadoopIndexTask.java:277) ~[druid-indexing-service-0.9.0-1455643294-b1f90f4-2.jar:0.9.0-1455643294-b1f90f4-2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:167) ~[druid-indexing-service-0.9.0-1455643294-b1f90f4-2.jar:0.9.0-1455643294-b1f90f4-2]
	... 7 more
Caused by: java.lang.ClassNotFoundException: io.druid.initialization.DruidModule
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_60]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_60]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_60]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_60]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_60]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_60]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_60]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_60]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_60]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_60]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_60]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_60]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370) ~[?:1.8.0_60]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[?:1.8.0_60]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[?:1.8.0_60]
	at io.druid.initialization.Initialization.getFromExtensions(Initialization.java:133) ~[druid-server-0.9.0-1455643294-b1f90f4-2.jar:0.9.0-1455643294-b1f90f4-2]
	at io.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:320) ~[druid-server-0.9.0-1455643294-b1f90f4-2.jar:0.9.0-1455643294-b1f90f4-2]
	at io.druid.indexer.HadoopDruidIndexerConfig.<clinit>(HadoopDruidIndexerConfig.java:98) ~[druid-indexing-hadoop-0.9.0-1455643294-b1f90f4-2.jar:0.9.0-1455643294-b1f90f4-2]
	at io.druid.indexing.common.task.HadoopIndexTask$HadoopDetermineConfigInnerProcessing.runTask(HadoopIndexTask.java:277) ~[druid-indexing-service-0.9.0-1455643294-b1f90f4-2.jar:0.9.0-1455643294-b1f90f4-2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:167) ~[druid-indexing-service-0.9.0-1455643294-b1f90f4-2.jar:0.9.0-1455643294-b1f90f4-2]
	... 7 more
2016-02-16T17:39:22,322 INFO [task-runner-0-priority-0] io.druid.indexing.worker.executor.ExecutorLifecycle - Task completed with status: {
  "id" : "index_hadoop_basefact_network_2016-02-16T17:39:12.771Z",
  "status" : "FAILED",
  "duration" : 2158
}

**Comment by drcrallen** [comment]
@rasahner is this patch included? https://github.com/druid-io/druid/pull/2448

**Comment by rasahner** [comment]
yes

**Comment by drcrallen** [comment]
@rasahner can you please file an issue against 0.9.0 and include the following:

The system classpath jars, the layout of extension directories and what files are in them, which extensions are in the list to be included, and the layout of the hadoop directory?

For some reason the jar which contains the druid-api classes is being injected in a weird place.

This worked for @gianm on EMR, so I'm guessing it is related to how the jars are packaged in the test deployment. Any help you can give in debugging would be appreciated.

**Comment by guobingkun** [comment]
@drcrallen Regarding the issue I discovered, I just submitted the hadoop task locally to overlord,
I have ```druid.extensions.loadList=["mysql-metadata-storage", "druid-datasketches"]```.
My hadoop directory looks like this ,
```
tree hadoop-client/
hadoop-client/
└── 2.3.0
    ├── avro-1.7.4.jar
    ├── commons-beanutils-1.7.0.jar
    ├── commons-beanutils-core-1.8.0.jar
    ├── commons-collections-3.2.1.jar
    ├── commons-compress-1.4.1.jar
    ├── commons-configuration-1.6.jar
    ├── commons-digester-1.8.jar
    ├── commons-httpclient-3.1.jar
    ├── commons-math3-3.1.1.jar
    ├── commons-net-3.1.jar
    ├── hadoop-annotations-2.3.0.jar
    ├── hadoop-auth-2.3.0.jar
    ├── hadoop-client-2.3.0.jar
    ├── hadoop-common-2.3.0.jar
    ├── hadoop-hdfs-2.3.0.jar
    ├── hadoop-mapreduce-client-app-2.3.0.jar
    ├── hadoop-mapreduce-client-common-2.3.0.jar
    ├── hadoop-mapreduce-client-core-2.3.0.jar
    ├── hadoop-mapreduce-client-jobclient-2.3.0.jar
    ├── hadoop-mapreduce-client-shuffle-2.3.0.jar
    ├── hadoop-yarn-api-2.3.0.jar
    ├── hadoop-yarn-client-2.3.0.jar
    ├── hadoop-yarn-common-2.3.0.jar
    ├── hadoop-yarn-server-common-2.3.0.jar
    ├── jaxb-api-2.2.2.jar
    ├── paranamer-2.3.jar
    ├── servlet-api-2.5.jar
    ├── snappy-java-1.0.4.1.jar
    ├── stax-api-1.0-2.jar
    ├── xmlenc-0.52.jar
    └── xz-1.0.jar
```

**Comment by rasahner** [comment]
@drcrallen, I will, but I have to deal with some build problems first.

**Comment by rasahner** [comment]
Our deployment setup is totally different from the open source way, and some of your questions don't really apply.  We basically put most of the jars in one place and put that place on the classpath.  hadoop is an exception - there's a set of directories on the path containing hadoop stuff.  We're going to investigate further and see what we can find out.  

I did look to see if druid-api was on the classpath and it is, and it contains io/druid/initialization/DruidModule.class.
