### PR TITLE
Fixes and improvements to SQL metadata caching.

### LINKED ISSUE #4258: SQL: Spurious 'table not found'
Some users have reported `Table 'xxx' not found` errors that (sometimes) resolve when restarting brokers. Seems like something off with the metadata caching.

See https://groups.google.com/d/topic/druid-user/A_C9pKWzc0M/discussion for context.

### PR DESCRIPTION
**Pull request by gianm**
Also adds support for MultipleSpecificSegmentSpec to CachingClusteredClient.

SQL changes:
- Cache metadata on a per-segment level, in addition to per-dataSource, so
  we don't need to re-query all segments whenever a single new one appears.
  This should lower the load placed on the cluster by metadata queries.
- Fix race condition in DruidSchema that can cause us to miss metadata. It was
  possible to notice new segments, then issue a query, and have that query
  not actually hit those segments, and not notice that it didn't hit those segments.
  Then, the metadata from those segments would be ignored.
- Fix assumption in DruidSchema that all segments are immutable. Now, mutable
  segments are periodically re-queried.
- Fix inappropriate re-use of SchemaPlus. Now we create one for each planning
  cycle, rather than sharing one. It caches table objects, which we want to
  avoid, since it can cause stale metadata. We do the caching in DruidSchema
  so we don't need the SchemaPlus caching.

Server changes:
- Add a TimelineCallback to TimelineServerView, for callers that want to get updates
  when the timeline has been modified.
- Change CachingClusteredClient from a QueryRunner to a QuerySegmentWalker. This
  allows it to accept queries that are segment-descriptor-based rather than
  intervals-based. In particular it will now support MultipleSpecificSegmentSpec.

Should fix #4258.

### CODE REVIEW

**Comment by richiesgr** [comment]
Sorry for CossPosting I've already open this 

Hi
I'm using imply 2.4.0 version and the problem still exists
after restarting the broker the SQL server lose the metadata of the data source.
After some time it come back but not always
Is there any workaround ?
Thanks

File: sql/src/main/java/io/druid/sql/calcite/schema/DruidSchema.java [hunk 1]
```diff
@@ -59,42 +58,66 @@
...
 import java.util.concurrent.CountDownLatch;
 import java.util.concurrent.ExecutorService;
+import java.util.function.Function;
+import java.util.stream.Collectors;
+import java.util.stream.StreamSupport;
 
 @ManageLifecycle
 public class DruidSchema extends AbstractSchema
 {
+  // Newest segments first, so they override older ones.
```
Comment (leventov) [inline sql/src/main/java/io/druid/sql/calcite/schema/DruidSchema.java]: I fail to see where exactly this order is used and why inner maps in `segmentSignatures` need to be TreeMaps, @gianm could you please explain?

Comment (gianm) [reply sql/src/main/java/io/druid/sql/calcite/schema/DruidSchema.java]: The idea is that Druid allows different segments to have different column types, and even allows the same column to have different types across different segments. But for SQL planning and metadata reporting purposes (e.g. INFORMATION_SCHEMA.COLUMNS) we can only report one type per column. We are preferring later segments (based on segment interval) over earlier ones if there's such a conflict, and achieve that by having `SEGMENT_ORDER` be an order that puts the newest segments first, and using it to affect the iteration order of `segmentMap.values()` in `buildDruidTable`.

Comment (leventov) [reply sql/src/main/java/io/druid/sql/calcite/schema/DruidSchema.java]: There are more uses of `TreeMap` and `TreeSet` in this class. Including some that are constructed without `SEGMENT_ORDER`. Maybe some of them don't need to be sorted collections.

Comment (leventov) [reply sql/src/main/java/io/druid/sql/calcite/schema/DruidSchema.java]: It also might be that based on how often `buildDruidTable()` is called compared to some other methods in `DruidSchema` that it's better to use HashMap for segmentMetadataInfo's values, and perform more work in `buildDruidTable()`, like having `Map<String, Pair<DataSegment, ValueType>> columnTypes`, iterating over `segmentMap.entrySet()` and use `columnTypes.compute()` with replacement decided comparing `DataSegment` objects.

Comment (leventov) [reply sql/src/main/java/io/druid/sql/calcite/schema/DruidSchema.java]: The latter may not improve performance, but be necessary for #6827, because `segmentMetadataInfo` may need to become `ConcurrentHashMap<String, ConcurrentHashMap<DataSegment, SegmentMetadataHolder>>` to enable safe iteration concurrent with modification. Assuming that we want to avoid `ConcurrentSkipListMap` because it's not memory efficient and slow.
