### PR TITLE
fix kafka indexing task not processing through end offsets on publish

### LINKED ISSUE #6602: Kafka: Publishing improperly starts immediately after setEndOffsets
#6129 contained a change that causes publishing to happen immediately when setEndOffsets is called: https://github.com/apache/incubator-druid/pull/6129/files#diff-d4624efd6954ee4ac442c4dc05b1f77aL434. This is not right: instead, the task should read up to its endOffsets.

This looks to be a regression since 0.12.3, so we should fix it before the release of 0.13.0.

### PR DESCRIPTION
**Pull request by clintropolis**
fixes #6602

test is somewhat strange, but tests the thing

### CODE REVIEW

File: extensions-core/kafka-indexing-service/src/test/java/org/apache/druid/indexing/kafka/KafkaIndexTaskTest.java [hunk 1]
```diff
@@ -761,6 +761,73 @@ public void testTimeBasedIncrementalHandOff() throws Exception
...
+    maxRowsPerSegment = 2;
+
+    // Insert data
+    try (final KafkaProducer<byte[], byte[]> kafkaProducer = kafkaServer.newProducer()) {
+      for (ProducerRecord<byte[], byte[]> record : records) {
+        kafkaProducer.send(record).get();
+      }
+    }
+    Map<String, Object> consumerProps = kafkaServer.consumerProperties();
+    consumerProps.put("max.poll.records", "1");
```
Comment (gianm) [inline extensions-core/kafka-indexing-service/src/test/java/org/apache/druid/indexing/kafka/KafkaIndexTaskTest.java]: Why does this need to be 1?

Comment (clintropolis) [reply extensions-core/kafka-indexing-service/src/test/java/org/apache/druid/indexing/kafka/KafkaIndexTaskTest.java]: It doesn't _need_ to be '1', it could also be '5' with how this test data is arranged, however '1' is really easy to reason about because it reads 1 test record per read loop (and that's what all the other incremental tests are using). It is set, along with max rows per segment of 2, to make the test task pause at a predictable offset, then setting a checkpoint offset ahead of the current offset to ensure that the task continues processing records until it hits the checkpointed offset.
