### PR TITLE
Fix GroupBy limit push down error when buffer is too small

### LINKED ISSUE #4739: GroupBy V2 query fails when using a large limit
0.10.1 added limit push down optimization to GroupBy V2 in PR #3873. 

When the optimization is on, GroupBy V2 requires a buffer with a minimum size depending on the limit.

If the user submits a query with a limit that's large enough such that the configured processing buffers are too small to support this optimization, the query fails with an error like:

```
 { "errorClass": "io.druid.java.util.common.IAE", "host": "localhost:8083", "errorMessage": "Buffer capacity [34636833] is too small for limit[500000000] with load factor[0.700000], minimum bytes needed: [1666887684]", "error": "Unknown exception" }
```

It would be better to disable the push down optimization in that situation instead of failing the query.

### PR DESCRIPTION
**Pull request by jon-wei**
Fixes #4739 

This PR adds a check before the LimitedBufferHashGrouper is used, to ensure that there is enough buffer capacity to apply the limit push down optimization.

A test is included that merges results for a query run on two segments, one where limit push down is applied and the other where the optimization is skipped because of insufficient buffer capacity.

### CODE REVIEW

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/BufferHashGrouper.java [hunk 1]
```diff
@@ -58,10 +61,12 @@ public BufferHashGrouper(
       final AggregatorFactory[] aggregatorFactories,
       final int bufferGrouperMaxSize,
       final float maxLoadFactor,
-      final int initialBuckets
+      final int initialBuckets,
+      final boolean useDefaultSorting
```
Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/BufferHashGrouper.java]: This parameter is confusingly named since it raises the question: which non-default sorting is used if `useDefaultSorting` is false?

A similar variable seems to be called `sortHasNonGroupingFields` in LimitedBufferHashGrouper. Would it make sense to use the same one here? It would at least be more consistent.

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/LimitedBufferHashGrouper.java [hunk 2]
```diff
@@ -375,27 +374,25 @@ public int compare(Integer o1, Integer o2)
...
     int targetTableArenaSize = numBucketsNeeded * bucketSize * 2;
     int heapSize = (limit + 1) * (Ints.BYTES);
     int requiredSize = targetTableArenaSize + heapSize;
 
-    if (buffer.capacity() < requiredSize) {
-      throw new IAE(
-          "Buffer capacity [%d] is too small for limit[%d] with load factor[%f], minimum bytes needed: [%d]",
-          buffer.capacity(),
+    if (bufferCapacity < requiredSize) {
+      log.info(
```
Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/LimitedBufferHashGrouper.java]: I think "debug" is better here -- this kind of diagnostic is a bit too loud for logging by default.

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/LimitedBufferHashGrouper.java [hunk 3]
```diff
@@ -375,27 +374,25 @@ public int compare(Integer o1, Integer o2)
...
+          "Buffer capacity [%d] is too small for limit[%d] with load factor[%f], " +
```
Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/LimitedBufferHashGrouper.java]: `%,d` will be more readable as it inserts commas into large numbers.

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/SpillingGrouper.java [hunk 4]
```diff
@@ -99,6 +103,25 @@ public SpillingGrouper(
           limitSpec.getLimit(),
           sortHasNonGroupingFields
       );
+      // if configured buffer size is too small to support limit push down, don't apply that optmization
+      if (!limitGrouper.validateBufferCapacity(mergeBufferSize)) {
+        if (sortHasNonGroupingFields) {
+          log.info("Ignoring forceLimitPushDown, insufficient buffer capacity.");
```
Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/SpillingGrouper.java]: IMO, this message should be at "debug" level.

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/ConcurrentGrouper.java [hunk 5]
```diff
@@ -79,6 +79,7 @@
   private final int priority;
   private final boolean hasQueryTimeout;
   private final long queryTimeoutAt;
+  private final int mergeBufferSize;
```
Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/ConcurrentGrouper.java]: This looks unused.

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByMergingQueryRunnerV2.java [hunk 6]
```diff
@@ -92,7 +93,8 @@ public GroupByMergingQueryRunnerV2(
       int concurrencyHint,
       BlockingPool<ByteBuffer> mergeBufferPool,
       ObjectMapper spillMapper,
-      String processingTmpDir
+      String processingTmpDir,
+      int mergeBufferSize
```
Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByMergingQueryRunnerV2.java]: IMO, put this next to mergeBufferPool, as it's very related.

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/SpillingGrouper.java [hunk 7]
```diff
@@ -99,6 +103,25 @@ public SpillingGrouper(
           limitSpec.getLimit(),
           sortHasNonGroupingFields
       );
+      // if configured buffer size is too small to support limit push down, don't apply that optmization
```
Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/SpillingGrouper.java]: optimization (spelling)

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/SpillingGrouper.java [hunk 8]
```diff
@@ -99,6 +103,25 @@ public SpillingGrouper(
...
+        }
+        this.grouper = new BufferHashGrouper<>(
+            bufferSupplier,
+            keySerde,
+            columnSelectorFactory,
+            aggregatorFactories,
+            bufferGrouperMaxSize,
+            bufferGrouperMaxLoadFactor,
+            bufferGrouperInitialBuckets,
+            // when there are non-grouping fields, we need to sort by a dimension-only ordering for merging to work
```
Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/epinephelinae/SpillingGrouper.java]: This comment seems strange to me. Don't we _always_ need to sort by a dimension-only ordering for merging, regardless of whether or not there are non-grouping fields?

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/BufferHashGrouper.java (hunk 1 above)
Comment (jon-wei) [reply processing/src/main/java/io/druid/query/groupby/epinephelinae/BufferHashGrouper.java]: I decided to keep it the same name but added some comments on its meaning, it's there t handle the case where some machines don't have enough buffer capacity to apply limit push down but other machines do.

It's not quite the same as sortHasNonGroupingFields, useDefaultSorting would be true when:
- Not using BufferHashGrouper for limit push down
- Using BufferHashGrouper because we don't have buffer capacity, but the sorting order has fields that are not in the grouping key, so we use the default ordering instead

False when
- Using BufferHashGrouper because we don't have buffer capacity for limit push down, but the OrderBy's ordering fields are all contained in the grouping key

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/LimitedBufferHashGrouper.java (hunk 2 above)
Comment (jon-wei) [reply processing/src/main/java/io/druid/query/groupby/epinephelinae/LimitedBufferHashGrouper.java]: changed to debug

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/LimitedBufferHashGrouper.java (hunk 3 above)
Comment (jon-wei) [reply processing/src/main/java/io/druid/query/groupby/epinephelinae/LimitedBufferHashGrouper.java]: Added comma

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/SpillingGrouper.java (hunk 7 above)
Comment (jon-wei) [reply processing/src/main/java/io/druid/query/groupby/epinephelinae/SpillingGrouper.java]: Fixed spelling

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/SpillingGrouper.java (hunk 4 above)
Comment (jon-wei) [reply processing/src/main/java/io/druid/query/groupby/epinephelinae/SpillingGrouper.java]: Changed to debug

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/SpillingGrouper.java (hunk 8 above)
Comment (jon-wei) [reply processing/src/main/java/io/druid/query/groupby/epinephelinae/SpillingGrouper.java]: Clarified the comment

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/ConcurrentGrouper.java (hunk 5 above)
Comment (jon-wei) [reply processing/src/main/java/io/druid/query/groupby/epinephelinae/ConcurrentGrouper.java]: Removed this

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByMergingQueryRunnerV2.java (hunk 6 above)
Comment (jon-wei) [reply processing/src/main/java/io/druid/query/groupby/epinephelinae/GroupByMergingQueryRunnerV2.java]: Moved this next to mergeBufferPool

File: processing/src/main/java/io/druid/query/groupby/epinephelinae/BufferHashGrouper.java (hunk 1 above)
Comment (gianm) [reply processing/src/main/java/io/druid/query/groupby/epinephelinae/BufferHashGrouper.java]: OK, thanks for adding the comment.

**Comment by gianm** [comment]
LGTM after the latest changes.
