### PR TITLE
Replace two-column index on pendingSegments table with one-column index.

### LINKED ISSUE #2319: Failure on creating pending segments table in MySQL or MariaDB metadata storage
I experienced following exception when I started Druid Overlord.
```
2016-01-20T11:32:40,984 INFO [main] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking start method[public void io.druid.metadata.IndexerSQLMetadataStorageCoordinator.start()] on object[io.druid.metadata.IndexerSQLMetadataStorageCoordinator@2d7a9786].
2016-01-20T11:32:40,986 INFO [main] io.druid.metadata.SQLMetadataConnector - Creating table[druid_pendingSegments]
2016-01-20T11:32:40,997 WARN [main] com.metamx.common.RetryUtils - Failed on try 1, retrying in 1,927ms.
org.skife.jdbi.v2.exceptions.CallbackFailedException: org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: java.sql.BatchUpdateException: Specified key was too long; max key length is 1000 bytes [statement:"null", located:"null", rewritten:"null", arguments:null]
        at org.skife.jdbi.v2.DBI.withHandle(DBI.java:284) ~[jdbi-2.63.1.jar:2.63.1]
        at io.druid.metadata.SQLMetadataConnector$2.call(SQLMetadataConnector.java:110) ~[druid-server-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
        at com.metamx.common.RetryUtils.retry(RetryUtils.java:38) [java-util-0.27.6.jar:?]
        at io.druid.metadata.SQLMetadataConnector.retryWithHandle(SQLMetadataConnector.java:115) [druid-server-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
        at io.druid.metadata.SQLMetadataConnector.createTable(SQLMetadataConnector.java:160) [druid-server-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
        at io.druid.metadata.SQLMetadataConnector.createPendingSegmentsTable(SQLMetadataConnector.java:188) [druid-server-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
        at io.druid.metadata.SQLMetadataConnector.createPendingSegmentsTable(SQLMetadataConnector.java:388) [druid-server-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
        at io.druid.metadata.IndexerSQLMetadataStorageCoordinator.start(IndexerSQLMetadataStorageCoordinator.java:91) [druid-server-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_65]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_65]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_65]
        at com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler.start(Lifecycle.java:350) [java-util-0.27.6.jar:?]
        at com.metamx.common.lifecycle.Lifecycle.start(Lifecycle.java:259) [java-util-0.27.6.jar:?]
        at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:155) [druid-api-0.3.15.jar:0.9.0-SNAPSHOT]
        at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:73) [druid-services-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
        at io.druid.cli.ServerRunnable.run(ServerRunnable.java:40) [druid-services-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
        at io.druid.cli.Main.main(Main.java:107) [druid-services-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
Caused by: org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: java.sql.BatchUpdateException: Specified key was too long; max key length is 1000 bytes [statement:"null", located:"null", rewritten:"null", arguments:null]
        at org.skife.jdbi.v2.Batch.execute(Batch.java:131) ~[jdbi-2.63.1.jar:2.63.1]
        at io.druid.metadata.SQLMetadataConnector$4.withHandle(SQLMetadataConnector.java:172) ~[druid-server-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
        at io.druid.metadata.SQLMetadataConnector$4.withHandle(SQLMetadataConnector.java:162) ~[druid-server-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
        at org.skife.jdbi.v2.DBI.withHandle(DBI.java:281) ~[jdbi-2.63.1.jar:2.63.1]
        ... 17 more
Caused by: java.sql.BatchUpdateException: Specified key was too long; max key length is 1000 bytes
        at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:1110) ~[?:?]
        at org.apache.commons.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:345) ~[commons-dbcp2-2.0.1.jar:2.0.1]
        at org.apache.commons.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:345) ~[commons-dbcp2-2.0.1.jar:2.0.1]
        at org.skife.jdbi.v2.Batch.execute(Batch.java:121) ~[jdbi-2.63.1.jar:2.63.1]
        at io.druid.metadata.SQLMetadataConnector$4.withHandle(SQLMetadataConnector.java:172) ~[druid-server-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
        at io.druid.metadata.SQLMetadataConnector$4.withHandle(SQLMetadataConnector.java:162) ~[druid-server-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
        at org.skife.jdbi.v2.DBI.withHandle(DBI.java:281) ~[jdbi-2.63.1.jar:2.63.1]
        ... 17 more
```

### PR DESCRIPTION
**Pull request by gianm**
Fixes #2319. Note that this change is not backwards compatible, but the table being changed was never in a release, so I think that's okay.

Anyone that already has this table could update its schema (assuming MySQL) by running:

```
ALTER TABLE druid_pendingSegments ADD COLUMN sequence_name_prev_id_sha1 VARCHAR(255) NOT NULL;
ALTER TABLE druid_pendingSegments ADD UNIQUE KEY (sequence_name_prev_id_sha1);
ALTER TABLE druid_pendingSegments DROP INDEX `sequence_name`;
```

### CODE REVIEW

**Comment by fjy** [comment]
:+1: after travis

File: server/src/main/java/io/druid/metadata/IndexerSQLMetadataStorageCoordinator.java [hunk 1]
```diff
@@ -447,10 +450,21 @@ public SegmentIdentifier inTransaction(Handle handle, TransactionStatus transact
             // Avoiding ON DUPLICATE KEY since it's not portable.
             // Avoiding try/catch since it may cause inadvertent transaction-splitting.
 
+            // UNIQUE key for the row, ensuring sequences do not fork in two directions.
```
Comment (himanshug) [inline server/src/main/java/io/druid/metadata/IndexerSQLMetadataStorageCoordinator.java]: can you add more to this comment, not clear why previous thing woulnd't work?

File: server/src/main/java/io/druid/metadata/IndexerSQLMetadataStorageCoordinator.java [hunk 2]
```diff
@@ -461,6 +475,7 @@ public SegmentIdentifier inTransaction(Handle handle, TransactionStatus transact
                   .bind("end", interval.getEnd().toString())
                   .bind("sequence_name", sequenceName)
                   .bind("sequence_prev_id", previousSegmentIdNotNull)
+                  .bind("sequence_name_prev_id_sha1", sequenceNamePrevIdSha1)
```
Comment (himanshug) [inline server/src/main/java/io/druid/metadata/IndexerSQLMetadataStorageCoordinator.java]: can we call this "sqeuence_name_and_prev_id_sha1" as its not just prev_id hashed in there.

Comment (gianm) [inline server/src/main/java/io/druid/metadata/IndexerSQLMetadataStorageCoordinator.java]: `sequence_name_prev_id_sha1` does include both "name" and "prev_id"…

File: server/src/main/java/io/druid/metadata/IndexerSQLMetadataStorageCoordinator.java (hunk 1 above)
Comment (gianm) [inline server/src/main/java/io/druid/metadata/IndexerSQLMetadataStorageCoordinator.java]: sure

Comment (gianm) [inline server/src/main/java/io/druid/metadata/IndexerSQLMetadataStorageCoordinator.java]: added

**Comment by xvrl** [comment]
@gianm instead, should we just make innodb a requirement for Druid 0.9?

**Comment by gianm** [comment]
@xvrl I think we should definitely make innodb a recommendation, but I think it's nice to support other storage engines if possible, to make life easier for people that already have tables in those engines (migrating metadata is a pain)

File: server/src/main/java/io/druid/metadata/IndexerSQLMetadataStorageCoordinator.java [hunk 3]
```diff
@@ -447,10 +450,23 @@ public SegmentIdentifier inTransaction(Handle handle, TransactionStatus transact
             // Avoiding ON DUPLICATE KEY since it's not portable.
             // Avoiding try/catch since it may cause inadvertent transaction-splitting.
 
+            // UNIQUE key for the row, ensuring sequences do not fork in two directions.
+            // Using a single column instead of (sequence_name, sequence_prev_id) as some MySQL storage engines
+            // have difficulty with large unique keys (see https://github.com/druid-io/druid/issues/2319)
+            final String sequenceNamePrevIdSha1 = BaseEncoding.base16().encode(
+                Hashing.sha1()
+                       .newHasher()
+                       .putBytes(sequenceName.getBytes(Charsets.UTF_8))
```
Comment (drcrallen) [inline server/src/main/java/io/druid/metadata/IndexerSQLMetadataStorageCoordinator.java]: Sugget StringUtils.toUtf8

File: server/src/main/java/io/druid/metadata/IndexerSQLMetadataStorageCoordinator.java [hunk 4]
```diff
@@ -447,10 +450,23 @@ public SegmentIdentifier inTransaction(Handle handle, TransactionStatus transact
...
+                       .putByte((byte) 0xff)
+                       .putBytes(previousSegmentIdNotNull.getBytes(Charsets.UTF_8))
```
Comment (drcrallen) [inline server/src/main/java/io/druid/metadata/IndexerSQLMetadataStorageCoordinator.java]: Suggest StringUtils.toUtf8

File: server/src/main/java/io/druid/metadata/SQLMetadataConnector.java [hunk 5]
```diff
@@ -197,9 +197,10 @@ public void createPendingSegmentsTable(final String tableName)
                 + "  \"end\" VARCHAR(255) NOT NULL,\n"
                 + "  sequence_name VARCHAR(255) NOT NULL,\n"
                 + "  sequence_prev_id VARCHAR(255) NOT NULL,\n"
+                + "  sequence_name_prev_id_sha1 VARCHAR(255) NOT NULL,\n"
                 + "  payload %2$s NOT NULL,\n"
                 + "  PRIMARY KEY (id),\n"
-                + "  UNIQUE (sequence_name, sequence_prev_id)\n"
+                + "  UNIQUE (sequence_name_prev_id_sha1)\n"
```
Comment (drcrallen) [inline server/src/main/java/io/druid/metadata/SQLMetadataConnector.java]: There is no guard against hash collisions here, right?

How is unique hash ensured?

**Comment by himanshug** [comment]
:+1: after comments regarding StringUtils.toUtf8 are addressed.

File: server/src/main/java/io/druid/metadata/IndexerSQLMetadataStorageCoordinator.java (hunk 4 above)
Comment (gianm) [inline server/src/main/java/io/druid/metadata/IndexerSQLMetadataStorageCoordinator.java]: ah okay, I was looking for that but hadn't found it. I only found SerializerUtils which wasn't statics and didn't seem right.

File: server/src/main/java/io/druid/metadata/SQLMetadataConnector.java (hunk 5 above)
Comment (gianm) [inline server/src/main/java/io/druid/metadata/SQLMetadataConnector.java]: No there's no guard. It's ensured by http://git-scm.com/book/en/v1/Git-Tools-Revision-Selection#A-SHORT-NOTE-ABOUT-SHA-1 :)

Comment (gianm) [inline server/src/main/java/io/druid/metadata/SQLMetadataConnector.java]: It's also not so bad if this does collide, all it'll do is make a sequence that *should* have worked not actually work. So the task trying to do the data load will fail. It won't lead to incorrect data.

I would also eat my hat if it ever happened, ever, to anyone.

File: server/src/main/java/io/druid/metadata/IndexerSQLMetadataStorageCoordinator.java (hunk 4 above)
Comment (gianm) [inline server/src/main/java/io/druid/metadata/IndexerSQLMetadataStorageCoordinator.java]: updated

**Comment by gianm** [comment]
@himanshug @drcrallen switched to StringUtils.toUtf8

File: server/src/main/java/io/druid/metadata/SQLMetadataConnector.java (hunk 5 above)
Comment (drcrallen) [inline server/src/main/java/io/druid/metadata/SQLMetadataConnector.java]: !RemindMe if this ever happens to have @gianm eat a hat.. a big, feathery one

Comment (himanshug) [inline server/src/main/java/io/druid/metadata/SQLMetadataConnector.java]: finding a sha1 hash collision would be a discovery in itself :)

Comment (drcrallen) [inline server/src/main/java/io/druid/metadata/SQLMetadataConnector.java]: A better way to say it is: If the segment database ever gets large enough to where sha-1 collisions are a concern, there are MANY other places that will break first.

**Comment by drcrallen** [comment]
:+1:

File: server/src/main/java/io/druid/metadata/SQLMetadataConnector.java (hunk 5 above)
Comment (xvrl) [inline server/src/main/java/io/druid/metadata/SQLMetadataConnector.java]: @gianm doesn't own a hat
