### PR TITLE
Make URIExtraction not require FileSystem impls for URIs it understands

### LINKED ISSUE #2928: FileSystemNotFoundException when loading S3-based lookup with specific location
https://github.com/druid-io/druid/pull/2738/files#r62376615

appears to be a regression since 0.9.0.

### PR DESCRIPTION
**Pull request by drcrallen**
* Fixes #2928

### CODE REVIEW

File: extensions-core/namespace-lookup/src/main/java/io/druid/server/namespace/URIExtractionNamespaceFunctionFactory.java [hunk 1]
```diff
@@ -151,7 +151,7 @@ public String call()
             versionRegex = null;
           }
         } else {
-          final Path filePath = Paths.get(extractionNamespace.getUri());
+          final Path filePath = Paths.get(extractionNamespace.getUri().getPath());
```
Comment (gianm) [inline extensions-core/namespace-lookup/src/main/java/io/druid/server/namespace/URIExtractionNamespaceFunctionFactory.java]: This is just going to be the path part (not the scheme or the authority), is this going to do the right thing? In particular uriBase is not going to have the same scheme as the original uri.

Comment (drcrallen) [inline extensions-core/namespace-lookup/src/main/java/io/druid/server/namespace/URIExtractionNamespaceFunctionFactory.java]: ah crap yeah no, fixing

Comment (drcrallen) [inline extensions-core/namespace-lookup/src/main/java/io/druid/server/namespace/URIExtractionNamespaceFunctionFactory.java]: Fixed and tests now include snowmen in the URI.

**Comment by drcrallen** [comment]
@gianm fixed and added utf-8 tests as well

File: extensions-core/namespace-lookup/src/main/java/io/druid/server/namespace/URIExtractionNamespaceFunctionFactory.java [hunk 2]
```diff
@@ -151,9 +151,23 @@ public String call()
             versionRegex = null;
           }
         } else {
-          final Path filePath = Paths.get(extractionNamespace.getUri());
+          final URI rawURI = extractionNamespace.getUri();
+          final Path filePath = Paths.get(rawURI.getPath());
```
Comment (gianm) [inline extensions-core/namespace-lookup/src/main/java/io/druid/server/namespace/URIExtractionNamespaceFunctionFactory.java]: This code block only happens if `doSearch` is false; in that case why do we need to be looking at parents at all?

Comment (gianm) [inline extensions-core/namespace-lookup/src/main/java/io/druid/server/namespace/URIExtractionNamespaceFunctionFactory.java]: or calling `puller.getLatestVersion`; that seems unnecessary when we provide a specific uri.

Comment (gianm) [inline extensions-core/namespace-lookup/src/main/java/io/druid/server/namespace/URIExtractionNamespaceFunctionFactory.java]: I'm mostly asking those things because `Paths.get(String)` is going to parse the path as if it were on the local filesystem, which I'm not sure will always work? So if it turns out we don't actually _need_ to do that, it could be simpler to just not do it.

Comment (drcrallen) [inline extensions-core/namespace-lookup/src/main/java/io/druid/server/namespace/URIExtractionNamespaceFunctionFactory.java]: Yes, can be done. Check it out now please

File: extensions-core/namespace-lookup/src/main/java/io/druid/server/namespace/URIExtractionNamespaceFunctionFactory.java [hunk 3]
```diff
@@ -140,37 +137,36 @@ public String call()
...
+                        "Could not find match for pattern `%s` in [%s] for %s",
+                        versionRegex,
+                        originalUri,
+                        extractionNamespace
+                    )
+                )
+            );
+          }
+        } else {
+          uri = extractionNamespace.getUri();
```
Comment (gianm) [inline extensions-core/namespace-lookup/src/main/java/io/druid/server/namespace/URIExtractionNamespaceFunctionFactory.java]: So fresh and so clean!

**Comment by gianm** [comment]
👍

**Comment by nishantmonu51** [comment]
:+1:
