### PR TITLE
Better handling of ParseExceptions.

### LINKED ISSUE #2510: Half-ingested events are possible when exceptions are caught on IncrementalIndex.add
Pre-0.8.2, and post #2505, RealtimeManager catches ParseExceptions on `plumber.add`, increments the unparseable counter, and continues. Post #2505 RealtimeIndexTask does too. This can cause half-ingested events, because the ParseExceptions get thrown while the index is updating aggregators in its facts map. In this case:

- other aggregators are not updated,
- but a row does end up in the facts table (with potentially some aggregators updated and some not),
- and the event is counted "unparseable" rather than "processed" which is strange as now the "processed" count does not match the number of events actually added to the index.

One example of when a ParseException can get thrown is if you have a longSum aggregator reading from a field in the InputRow that cannot be parsed as a number. (& other things like this)

Possible better behaviors,

1. abort realtime processing, like happened between 0.8.2 and #2505. Folks might have a hard time with this one, though, if they aren't validating their inputs before passing them to Druid.
2. don't include the event in the index at all, and count it "unparseable". But this might be tough to implement given that when this exception is thrown, the facts table has already been partially updated.
3. keep the same indexing behavior, but count the event as "processed" instead of "unparseable"
4. catch ParseException on `agg.aggregate()` in OnheapIncrementalIndex, and move on to the next aggregator, and count the event as "processed".

potential risk with options 3 & 4: inconsistent aggregator state, if any aggregator out there is implemented such that its state cannot be relied on after it encounters an exception during `aggregate`.

### PR DESCRIPTION
**Pull request by gianm**
Two changes:
- Allow IncrementalIndex to suppress ParseExceptions on "aggregate".
- Add "reportParseExceptions" option to realtime tuning configs. By default this is "false".

Behavior of the counters should now be:

- processed: Number of rows indexed, including rows where some fields could be parsed and some could not.
- thrownAway: Number of rows thrown away due to rejection policy.
- unparseable: Number of rows thrown away due to being completely unparseable (no fields salvageable at all).

If "reportParseExceptions" is true then "unparseable" will always be zero (because a parse error would
cause an exception to be thrown). In addition, "processed" will only include fully parseable rows
(because even partial parse failures will cause exceptions to be thrown).

Fixes #2510.

### CODE REVIEW

File: indexing-service/src/test/java/io/druid/indexing/common/task/RealtimeIndexTaskTest.java [hunk 1]
```diff
@@ -145,6 +144,89 @@
       )
   );
 
+  private static final String FAIL_DIM = "__fail__";
```
Comment (fjy) [inline indexing-service/src/test/java/io/druid/indexing/common/task/RealtimeIndexTaskTest.java]: can we call this __unparseable__?

Comment (fjy) [inline indexing-service/src/test/java/io/druid/indexing/common/task/RealtimeIndexTaskTest.java]: oh wait, this is only in a test

**Comment by fjy** [comment]
:+1:

File: indexing-hadoop/src/main/java/io/druid/indexer/IndexGeneratorJob.java [hunk 2]
```diff
@@ -229,6 +229,7 @@ private static IncrementalIndex makeIncrementalIndex(
 
     OnheapIncrementalIndex newIndex = new OnheapIncrementalIndex(
         indexSchema,
+        true,
```
Comment (himanshug) [inline indexing-hadoop/src/main/java/io/druid/indexer/IndexGeneratorJob.java]: hadoop batch ingestion has a config `ignoreInvalidRows` which should probably be used here instead.

Comment (gianm) [inline indexing-hadoop/src/main/java/io/druid/indexer/IndexGeneratorJob.java]: sounds reasonable, updated to set reportParseExceptions = `!tuningConfig.isIgnoreInvalidRows()`

File: processing/src/main/java/io/druid/segment/incremental/OnheapIncrementalIndex.java [hunk 3]
```diff
@@ -139,6 +145,7 @@ protected DimDim makeDimDim(String dimension, Object lock)
   protected Integer addToFacts(
       AggregatorFactory[] metrics,
       boolean deserializeComplexMetrics,
+      boolean reportParseExceptions,
```
Comment (nishantmonu51) [inline processing/src/main/java/io/druid/segment/incremental/OnheapIncrementalIndex.java]: this flag is already passed in constr, do we really need to pass it again here ?

File: processing/src/main/java/io/druid/segment/incremental/IncrementalIndex.java [hunk 4]
```diff
@@ -416,7 +421,16 @@ public InputRow formatRow(InputRow row)
    */
   public int add(InputRow row) throws IndexSizeExceededException {
     TimeAndDims key = toTimeAndDims(row);
-    final int rv = addToFacts(metrics, deserializeComplexMetrics, row, numEntries, key, in, rowSupplier);
+    final int rv = addToFacts(
+        metrics,
+        deserializeComplexMetrics,
+        reportParseExceptions,
```
Comment (nishantmonu51) [inline processing/src/main/java/io/druid/segment/incremental/IncrementalIndex.java]: minor nit: It makes it a bit easy to backport and fix conflicts if the newly added parameter is the last one in method.

File: processing/src/main/java/io/druid/segment/incremental/OnheapIncrementalIndex.java (hunk 3 above)
Comment (gianm) [inline processing/src/main/java/io/druid/segment/incremental/OnheapIncrementalIndex.java]: same is true for `deserializeComplexMetrics`, was just trying to be consistent.

**Comment by pjain1** [comment]
:+1:

File: processing/src/main/java/io/druid/segment/incremental/OnheapIncrementalIndex.java (hunk 3 above)
Comment (nishantmonu51) [inline processing/src/main/java/io/druid/segment/incremental/OnheapIncrementalIndex.java]: i cant see any benefits of passing it multiple times, applies to both the flags,
I am fine cleaning them up in separate PR, can you either clean them up or file an issue to track this ?

Comment (gianm) [inline processing/src/main/java/io/druid/segment/incremental/OnheapIncrementalIndex.java]: sure, #2528

**Comment by nishantmonu51** [comment]
:+1:
