### PR TITLE
Coordinator primary segment assignment fix

### LINKED ISSUE #5531: Coordinator primary replicant assignment over assigns segments until loaded
Following up on investigation detailed in #5521 we noticed another issue, this time involving segment primary replicant assignment behavior. Changes introduced in #4757 appear to have inadvertently changed the behavior of replica assignment to now cause the coordinator to assign a primary replicant to _every_ eligible historical in the cluster until either one of the historicals have loaded the segment OR all of the historicals have this segment in their load queue, at least based on output observed in the logs.
```
2018-03-19T22:05:14,742 INFO [Coordinator-Exec--0] io.druid.server.coordinator.LoadQueuePeon - Asking server peon[/druid/loadQueue/some.historical.internal:8283] to load segment[some_segment]
...
2018-03-19T22:07:47,052 INFO [Coordinator-Exec--0] io.druid.server.coordinator.LoadQueuePeon - Asking server peon[/druid/loadQueue/other.historical.internal:8283] to load segment[some_segment]
...
2018-03-19T22:10:19,432 INFO [Coordinator-Exec--0] io.druid.server.coordinator.LoadQueuePeon - Asking server peon[/druid/loadQueue/another.historical.internal:8283] to load segment[some_segment]
...
2018-03-19T22:11:19,854 WARN [Coordinator-Exec--0] io.druid.server.coordinator.rules.LoadRule - No available [_default_tier] servers or node capacity to assign primary segment[some_segment]! Expected Replicants[1]
```
with the last message repeating until the segment has been loaded at least once. No `LoadQueuePeon` messages appear in the log output between the above log snippet.

Rather than loading the segment on all historical servers, once the segment is in the load queue of an assigned primary, it should follow the logic path as if it were already loaded on it's primary assigned server, and run the [normal replica assignment path instead](https://github.com/druid-io/druid/blob/80419752b53b1fe27cc59e6e07a0e8e89cfe5869/server/src/main/java/io/druid/server/coordinator/rules/LoadRule.java#L100).

### PR DESCRIPTION
**Pull request by clintropolis**
Fixes #5531 by taking segment loading into account when deciding how to place segments, avoiding a bug where primary assignment would assign the segment to all historicals until it is loaded.

Reverts some code removed in #4921 for tracking currently loading segments in `SegmentReplicantLookup`.

### CODE REVIEW

**Comment by jon-wei** [comment]
Fix looks good to me, would be nice if we had tests but looks like that's pretty difficult/complicated as of now

File: server/src/main/java/io/druid/server/coordinator/SegmentReplicantLookup.java [hunk 1]
```diff
@@ -33,9 +33,12 @@
  */
 public class SegmentReplicantLookup
 {
+
+
```
Comment (jihoonson) [inline server/src/main/java/io/druid/server/coordinator/SegmentReplicantLookup.java]: Unnecessary lines.

**Comment by gianm** [comment]
Saw a failure in this one:

```
testMoveSegment(io.druid.server.coordinator.CuratorDruidCoordinatorTest)  Time elapsed: 6.71 sec  <<< ERROR!
java.lang.Exception: test timed out after 5000 milliseconds
	at io.druid.server.coordinator.CuratorDruidCoordinatorTest.testMoveSegment(CuratorDruidCoordinatorTest.java:369)
```

Being optimistic, I restarted the tests. Although this test does seem potentially related to this patch.

**Comment by clintropolis** [comment]
@gianm the test was added in #5528, and it also failed in a [definitely unrelated PR where i increased the timeout](https://github.com/druid-io/druid/pull/5555/commits/3a64f1fcd327ae805e3822b5cb38740cd2e3bbe9) so hopefully it will happen less often. I don't think it's because of a race condition with the curator test server used in the test because I ran it in a loop where it successfully passed ~720 times, with something like this
```
n=1; while mvn -q -Dcheckstyle.skip=true -Dpmd.skip=true -Dtest=io.druid.server.coordinator.CuratorDruidCoordinatorTest#testMoveSegment -pl server test; do echo "success: $n"; n=$[$n + 1];:; done
```
but I suppose it's possible it's still racy somewhere. Also possible is that travis just takes a bit longer than my local debug machine took to run the tests, which is why the increased timeout in the other PR.

**Comment by gianm** [comment]
The test passed after being restarted, so let's commit the patch.
