### PR TITLE
Hadoop indexing: Fix NPE when intervals not provided

### LINKED ISSUE #4647: Hadoop indexing: NPE when intervals not provided
The "determineIntervals" functionality that gets activated when your granularitySpec doesn't provide intervals, doesn't seem to work anymore. What happens is that in DetermineCardinalityReducer, this line NPEs:

```
      Optional<Interval> intervalOptional = config.getGranularitySpec().bucketInterval(new DateTime(key.get()));
```

Because in UniformGranularitySpec, `bucketInterval` dereferences `wrappedSpec`, which is null when intervals aren't provided. This appears to have been broken since #3674 (0.10.0).

### PR DESCRIPTION
**Pull request by praveev**
@gianm pls review. Fix #4647.

### CODE REVIEW

**Comment by niketh** [comment]
Can you fix this too https://github.com/druid-io/druid/blob/master/server/src/main/java/io/druid/segment/indexing/granularity/UniformGranularitySpec.java#L100 , bucketInterval(DateTime dt) will always throw NPE when wrappedSpec is NULL

**Comment by praveev** [comment]
@niketh i knew this as well....but this wasn't related to my earlier pr which the issue described. UniformGranularitySpec bucketInterval has had this assumption that it will be invoked with wrappedSpec for a while now. Do you know why? Anyway I've added the protection for now.

**Comment by niketh** [comment]
@praveev The null c@praveev The check for `wrappedSpec` should have been added earlier, looks like it's a miss. Also, can you open/close your PR. There is a flaky test because of which the build is failing.heck should

File: indexing-hadoop/src/main/java/io/druid/indexer/DetermineHashedPartitionsJob.java [hunk 1]
```diff
@@ -324,12 +324,9 @@ protected void reduce(
             HyperLogLogCollector.makeCollector(ByteBuffer.wrap(value.getBytes(), 0, value.getLength()))
         );
       }
-      Optional<Interval> intervalOptional = config.getGranularitySpec().bucketInterval(new DateTime(key.get()));
 
-      if (!intervalOptional.isPresent()) {
-        throw new ISE("WTF?! No bucket found for timestamp: %s", key.get());
-      }
-      Interval interval = intervalOptional.get();
+      Interval interval = config.getGranularitySpec().getSegmentGranularity().bucket(new DateTime(key.get()));
```
Comment (jihoonson) [inline indexing-hadoop/src/main/java/io/druid/indexer/DetermineHashedPartitionsJob.java]: Should this handle two cases of whether ```determineIntervals``` is true or not like https://github.com/druid-io/druid/blob/master/indexing-hadoop/src/main/java/io/druid/indexer/DetermineHashedPartitionsJob.java#L257-L267?

Comment (praveev) [inline indexing-hadoop/src/main/java/io/druid/indexer/DetermineHashedPartitionsJob.java]: You can replace `config.getGranularitySpec().bucketInterval()` with `config.getGranularitySpec().getSegmentGranularity().bucket()` in this class and it passes the unit tests. The main difference is `bucketInterval` can return empty when there are no intervals but `bucket` will work for all cases. I don't know the historical context for why `bucketInterval` was added to the GranularitySpec interface.

Comment (jihoonson) [inline indexing-hadoop/src/main/java/io/druid/indexer/DetermineHashedPartitionsJob.java]: You mean ```config.getGranularitySpec().bucketInterval()``` and ```config.getGranularitySpec().getSegmentGranularity().bucket()``` are interchangeable? I'm not sure about that because ```config.getGranularitySpec().bucketInterval()``` finds a proper interval among the given bucket intervals in the granularity spec while ```config.getGranularitySpec().getSegmentGranularity().bucket()``` computes an interval from the input dateTime.

I think ```determinIntervals``` means that we should compute intervals from inputs because bucket intervals is absent in the granularity spec if it's true. Otherwise, we can find proper intervals from the given bucket intervals.

Comment (praveev) [inline indexing-hadoop/src/main/java/io/druid/indexer/DetermineHashedPartitionsJob.java]: yes. if you look closer in UniformGranularitySpec, you’ll notice that bucket intervals are actually determined by [chopping the input intervals properly according to the granularity spec](https://github.com/druid-io/druid/blob/master/server/src/main/java/io/druid/segment/indexing/granularity/UniformGranularitySpec.java#L62)
so whatever `bucket()` computes should align with the interval from `bucketInterval()` as well when it returns one b/c the goal of both is to return an interval that follows the rules of the granularity.

Comment (praveev) [inline indexing-hadoop/src/main/java/io/druid/indexer/DetermineHashedPartitionsJob.java]: yes. if you look closer in UniformGranularitySpec, you’ll notice that bucket intervals are actually determined by [chopping the input intervals properly according to the granularity spec](https://github.com/druid-io/druid/blob/master/server/src/main/java/io/druid/segment/indexing/granularity/UniformGranularitySpec.java#L62)
so whatever `bucket()` computes should align with the interval from `bucketInterval()` as well when it returns one b/c the goal of both is to return an interval that follows the rules of the granularity.

Comment (jihoonson) [inline indexing-hadoop/src/main/java/io/druid/indexer/DetermineHashedPartitionsJob.java]: It's not same because the bucket intervals can be non-consecutive in the granularity spec.
Here is a counterexample.

```java
final GranularitySpec spec = new UniformGranularitySpec(
    Granularities.DAY,
    null,
    Lists.newArrayList(
        new Interval("2012-01-08T00Z/2012-01-11T00Z"),
        new Interval("2012-01-07T00Z/2012-01-08T00Z"),
        new Interval("2012-01-03T00Z/2012-01-04T00Z"),
        new Interval("2012-01-01T00Z/2012-01-03T00Z")
    )
);

System.out.println("spec.bucketInterval(): " + spec.bucketInterval(new DateTime(2012, 1, 5, 0, 0)));
System.out.println("spec.getSegmentGranularity().bucket(): " + spec.getSegmentGranularity().bucket(new DateTime(2012, 1, 5, 0, 0)));
```

```
spec.bucketInterval(): Optional.absent()
spec.getSegmentGranularity().bucket(): 2012-01-05T00:00:00.000Z/2012-01-06T00:00:00.000Z
```

Comment (praveev) [inline indexing-hadoop/src/main/java/io/druid/indexer/DetermineHashedPartitionsJob.java]: ah right. didn't think of non-contiguous intervals. they are not replaceable.

re: adding this `if (determineIntervals)` statement in the reducer.
The mapper already [throws an exception](https://github.com/praveev/druid/blob/9a88551d6500b52cc984bc3fe9df5f6ae399387a/indexing-hadoop/src/main/java/io/druid/indexer/DetermineHashedPartitionsJob.java#L270) in case it doesn't find an interval for an inputRow timestamp. So i think it is safe to assume that the timestamp will always map to an interval in the reducer? Apparently, that's how it was [originally](https://github.com/druid-io/druid/pull/3674/files#diff-b62980eee0e8bf2eac0a6bf8466b6c74L326)  before it was change in the PR linked to the issue

Comment (jihoonson) [inline indexing-hadoop/src/main/java/io/druid/indexer/DetermineHashedPartitionsJob.java]: Hmm, the original code looks a bug to me because non-contiguous intervals should be accepted as in IndexTask (https://github.com/druid-io/druid/blob/master/indexing-service/src/main/java/io/druid/indexing/common/task/IndexTask.java#L438-L442). This usually happens when reindexing old data for specified intervals.

**Comment by leventov** [comment]
@praveev please give sensible names for PRs, and link to the PR being fixed in the description.

**Comment by jon-wei** [comment]
@praveev Can you take a look at this PR again? We're thinking of getting this into 0.11.0.

File: indexing-hadoop/src/main/java/io/druid/indexer/DetermineHashedPartitionsJob.java (hunk 1 above)
Comment (gianm) [reply indexing-hadoop/src/main/java/io/druid/indexer/DetermineHashedPartitionsJob.java]: I think @jihoonson is right -- the original code looks buggy. The new code is buggy too but in a different way. I think we fix both bugs by having an `if (determineIntervals)` branch in DetermineCardinalityReducer, where the true branch does `spec.getSegmentGranularity().bucket()` and the false branch does `spec.bucketInterval()`.

It makes sense because `spec.getSegmentGranularity().bucket()` operates without looking at the provided intervals at all, so you only want to call that when the intervals are _not_ provided. It will generate segment intervals that match the segmentGranularity exactly. When the intervals _are_ provided then `spec.bucketInterval()` respects them, so it's preferred in that case.

**Comment by gianm** [comment]
@praveev have you got time to fix the conflicts and the DetermineCardinalityReducer behavior in advance of the dev sync call tomorrow?

File: indexing-hadoop/src/main/java/io/druid/indexer/DetermineHashedPartitionsJob.java (hunk 1 above)
Comment (praveev) [reply indexing-hadoop/src/main/java/io/druid/indexer/DetermineHashedPartitionsJob.java]: @gianm i have made this change locally. i am having difficulty compiling druid locally. i'll push it up once that is resolved.

**Comment by jon-wei** [comment]
@praveev @niketh 

This is one of the few remaining open PRs blocking 0.11.0-rc1 release, do we plan to get this merged or should we move it out?

**Comment by praveev** [comment]
@jon-wei @gianm sorry for the delay. pushed the changes. pls take a look.

**Comment by jon-wei** [comment]
:+1:
