### PR TITLE
Fix handling of InterruptedException in WorkerTaskMonitor's mainLoop.

### LINKED ISSUE #2664: Transient test failure - io.druid.indexing.worker.WorkerTaskMonitorTest testRestartCleansOldStatus
https://travis-ci.org/druid-io/druid/jobs/116194415
```
Tests run: 5, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 35.373 sec <<< FAILURE! - in io.druid.indexing.worker.WorkerTaskMonitorTest
testRestartCleansOldStatus(io.druid.indexing.worker.WorkerTaskMonitorTest)  Time elapsed: 31.136 sec  <<< ERROR!
java.lang.Exception: test timed out after 30000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at io.druid.indexing.worker.WorkerTaskMonitor.stop(WorkerTaskMonitor.java:260)
	at io.druid.indexing.worker.WorkerTaskMonitorTest.testRestartCleansOldStatus(WorkerTaskMonitorTest.java:331)
testRestartCleansOldStatus(io.druid.indexing.worker.WorkerTaskMonitorTest)  Time elapsed: 31.136 sec  <<< ERROR!
java.lang.IllegalStateException: not started
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at io.druid.indexing.worker.WorkerTaskMonitor.stop(WorkerTaskMonitor.java:250)
	at io.druid.indexing.worker.WorkerTaskMonitorTest.tearDown(WorkerTaskMonitorTest.java:205)
```

### PR DESCRIPTION
**Pull request by gianm**
I believe this will fix #2664.

Should also fix a potential issue where a real middleManager would not shut down on its own when killed.

### CODE REVIEW

File: indexing-service/src/main/java/io/druid/indexing/worker/WorkerTaskMonitor.java [hunk 1]
```diff
@@ -125,10 +124,13 @@ public void run()
         log.info("Started WorkerTaskMonitor.");
         started = true;
       }
+      catch (InterruptedException e) {
+        throw e;
```
Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/worker/WorkerTaskMonitor.java]: suggest `Thread.currenThread().interrupt()` as well here

File: indexing-service/src/main/java/io/druid/indexing/worker/WorkerTaskMonitor.java [hunk 2]
```diff
@@ -391,6 +397,9 @@ public void handle()
             status.getStatusCode()
         );
       }
+      catch (InterruptedException e) {
+        throw e;
```
Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/worker/WorkerTaskMonitor.java]: Suggest `Thread.currentThread().interrupt()` as well here

File: indexing-service/src/main/java/io/druid/indexing/worker/WorkerTaskMonitor.java [hunk 3]
```diff
@@ -442,6 +451,9 @@ public void handle()
               )
           );
         }
+        catch (InterruptedException e) {
+          throw e;
```
Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/worker/WorkerTaskMonitor.java]: same thing about suggesting that the interrupt status of the thread is preserved after throw.

File: indexing-service/src/main/java/io/druid/indexing/worker/WorkerTaskMonitor.java (hunk 1 above)
Comment (gianm) [inline indexing-service/src/main/java/io/druid/indexing/worker/WorkerTaskMonitor.java]: The convention in most of the java stdlib is that the interrupt flag is cleared when InterruptedException is thrown. I don't see it buying us much to do both... it should be enough to do one or the other.

Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/worker/WorkerTaskMonitor.java]: The need of re-setting of the interrupt flag depends on what happens in the caller.

If the caller catches `Exception`, then logs and keeps going, then the behavior is potentially going to violate expectations because the *NEXT* task in the loop might also stall and need interrupting.

So the question is, do you expect an interrupt to mean "quit now" or do you expect an interrupt to mean "quit the explicit task you are doing because it is stuck, but potentially keep going"?

Comment (gianm) [inline indexing-service/src/main/java/io/druid/indexing/worker/WorkerTaskMonitor.java]: In this case interrupting should mean "quit now" -- it only occurs when the server is shutting down. Nothing should be logging InterruptedExceptions and keeping going (that was the bug here). They should always fall through and cause stuff to stop.

Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/worker/WorkerTaskMonitor.java]: Ok, I think all the interrupts in this PR are handled reasonably. This one is thrown out of lifecycle.start() without being caught.

The others seem properly thrown out of the notice handler loop.

Sorry, it just takes a little while to dig through interrupted exceptions to make sure they are handled reasonably

**Comment by drcrallen** [comment]
:+1:

**Comment by fjy** [comment]
:+1:
