### PR TITLE
fix handling of dimension having only null values

### LINKED ISSUE #1211: Problem querying null dimensions on the last minutes
Hi all,

I have detected a problem when I query the last minutes and some of the my dimensions have a null value (doesn't appear on my event). I try to explain this case with more details:

I'am going to work with 2 topN queries:

 - Query A with <b>dimension NOT null</b>
```json
{
    "queryType": "topN",
    "dataSource": "rb_flow",
    "granularity": "minute",
    "dimension": "sensor_name",
    "threshold": 1000,
    "metric": "flows",
    "aggregations":[
         {"type":"longSum", "name":"flows", "fieldName":"events"}
    ],
    "intervals":["2015-03-17T10:43:00/2015-03-17T11:30:00"]
}
```
 - Query B with <b>dimension null</b>
```json
{
    "queryType": "topN",
    "dataSource": "rb_flow",
    "granularity": "minute",
    "dimension": "dot11_protocol",
    "threshold": 1000,
    "metric": "flows",
    "aggregations":[
         {"type":"longSum", "name":"flows", "fieldName":"events"}
    ],
    "intervals":["2015-03-17T10:43:00/2015-03-17T11:30:00"]
}
```

I'm using the realtime node with this spec:

```json
{   
 "dataSchema" : {
      "dataSource" : "rb_flow",
      "parser" : {
        "type" : "string",
        "parseSpec" : {
          "type" : "jsonLowercase",
          "format" : "json",
          "timestampSpec" : {
            "column" : "timestamp",
            "format" : "ruby"
          },
          "dimensionsSpec" : {
            "dimensions": ["application_id_name", "biflow_direction", "conversation", "direction", "engine_id_name", "http_user_agent_os", "http_host", "http_social_media", "http_social_user", "http_referer_l1", "l4_proto", "ip_protocol_version", "sensor_name", "scatterplot", "src", "src_country_code", "src_net_name", "src_port", "src_as_name", "client_mac", "client_id", "client_mac_vendor", "dot11_status", "src_vlan", "src_map", "srv_port", "dst", "dst_country_code", "dst_net_name", "dst_port", "dst_as_name", "dst_vlan", "dst_map", "input_snmp", "output_snmp", "input_vrf", "output_vrf", "tos", "client_latlong", "coordinates_map", "client_campus", "client_building", "client_floor", "client_zone", "wireless_id", "client_rssi", "client_rssi_num", "client_snr", "client_snr_num", "wireless_station", "hnblocation", "hnbgeolocation", "rat", "darklist_score_name", "darklist_category", "darklist_protocol", "darklist_direction", "darklist_score", "market", "organization", "dot11_protocol", "type" ],
            "dimensionExclusions" : ["bytes", "pkts", "http_url", "flow_end_reason", "src_as", "dst_as", "first_switched" ]
          }
        }
      },
      "metricsSpec" : [
                                    {"type":"count"                                      , "name":"events"}
                                   ,{"type":"longSum"    , "fieldName":"bytes"           , "name":"sum_bytes"}
                                   ,{"type":"longSum"    , "fieldName":"pkts"            , "name":"sum_pkts"}
                                   ,{"type":"hyperUnique", "fieldName":"client_mac"      , "name":"clients"}
                                   ,{"type":"hyperUnique", "fieldName":"wireless_station", "name":"wireless_stations"}
                                   ,{"type":"longSum"    , "fieldName":"client_rssi_num" , "name":"sum_rssi"}
                      ],
      "granularitySpec" : {
        "type" : "uniform",
        "segmentGranularity" : "HOUR",
        "queryGranularity" : "MINUTE"
      }
    },
    "ioConfig" : {
      "type" : "realtime",
      "firehose": {
        "type": "kafka-0.8",
        "consumerProps": {
          "zookeeper.connect": "127.0.0.1:2181",
          "zookeeper.connection.timeout.ms" : "15000",
          "zookeeper.session.timeout.ms" : "15000",
          "zookeeper.sync.time.ms" : "5000",
          "rebalance.max.retries": "64",
          "group.id": "rb-group",
          "fetch.message.max.bytes" : "1048576",
          "auto.offset.reset": "largest",
          "auto.commit.enable": "true"
        },
        "feed": "rb_flow"
      },
      "plumber": {
        "type": "realtime"
      }
    },
    "tuningConfig": {
      "type" : "realtime",
      "maxRowsInMemory": 20000,
      "intermediatePersistPeriod": "PT20m",
      "windowPeriod": "PT30m",
      "basePersistDirectory": "/tmp/realtime",
      "shardSpec": {"type": "linear", "partitionNum": 0 },
      "rejectionPolicy": {
        "type": "serverTime"
      }
    }
  }
```

My realtime is indexing both dimension: dot11_protocol(null), sensor_name(not null), but when I do a query A, I get this result:

 - Result QueryA (<b> NOT NULL DIMENSION </b>)

```json
[ {
  "timestamp" : "2015-03-17T10:43:00.000Z",
  "result" : [ {
    "sensor_name" : "ISG",
    "flows" : 119
  } ]
}, {
  "timestamp" : "2015-03-17T10:44:00.000Z",
  "result" : [ {
    "sensor_name" : "ISG",
    "flows" : 5796
  } ]
}, {
  "timestamp" : "2015-03-17T10:45:00.000Z",
  "result" : [ {
    "sensor_name" : "ISG",
    "flows" : 5825
  } ]
}, {
  "timestamp" : "2015-03-17T10:46:00.000Z",
  "result" : [ {
    "sensor_name" : "ISG",
    "flows" : 5846
  } ]
}, {
  "timestamp" : "2015-03-17T10:47:00.000Z",
  "result" : [ {
    "sensor_name" : "ISG",
    "flows" : 5873
  } ]
}, {
  "timestamp" : "2015-03-17T10:48:00.000Z",
  "result" : [ {
    "sensor_name" : "ISG",
    "flows" : 5869
  } ]
}, {
  "timestamp" : "2015-03-17T10:49:00.000Z",
  "result" : [ {
    "sensor_name" : "ISG",
    "flows" : 5894
  } ]
}, {
  "timestamp" : "2015-03-17T10:50:00.000Z",
  "result" : [ {
    "sensor_name" : "ISG",
    "flows" : 5896
  } ]
}, {
  "timestamp" : "2015-03-17T10:51:00.000Z",
  "result" : [ {
    "sensor_name" : "ISG",
    "flows" : 5897
  } ]
}, {
  "timestamp" : "2015-03-17T10:52:00.000Z",
  "result" : [ {
    "sensor_name" : "ISG",
    "flows" : 5891
  } ]
}, {
  "timestamp" : "2015-03-17T10:53:00.000Z",
  "result" : [ {
    "sensor_name" : "ISG",
    "flows" : 5885
  } ]
}, {
  "timestamp" : "2015-03-17T10:54:00.000Z",
  "result" : [ {
    "sensor_name" : "ISG",
    "flows" : 5884
  } ]
}, {
  "timestamp" : "2015-03-17T10:55:00.000Z",
  "result" : [ {
    "sensor_name" : "ISG",
    "flows" : 5897
  } ]
}, {
  "timestamp" : "2015-03-17T10:56:00.000Z",
  "result" : [ {
    "sensor_name" : "ISG",
    "flows" : 5878
  } ]
}, {
  "timestamp" : "2015-03-17T10:57:00.000Z",
  "result" : [ {
    "sensor_name" : "ISG",
    "flows" : 5870
  } ]
}, {
  "timestamp" : "2015-03-17T10:58:00.000Z",
  "result" : [ {
    "sensor_name" : "ISG",
    "flows" : 5891
  } ]
}, {
  "timestamp" : "2015-03-17T10:59:00.000Z",
  "result" : [ {
    "sensor_name" : "ISG",
    "flows" : 5894
  } ]
}, {
  "timestamp" : "2015-03-17T11:00:00.000Z",
  "result" : [ {
    "sensor_name" : "ISG",
    "flows" : 5880
  } ]
}, {
  "timestamp" : "2015-03-17T11:01:00.000Z",
  "result" : [ {
    "sensor_name" : "ISG",
    "flows" : 5874
  } ]
}, {
  "timestamp" : "2015-03-17T11:02:00.000Z",
  "result" : [ {
    "sensor_name" : "ISG",
    "flows" : 5898
  } ]
}, {
  "timestamp" : "2015-03-17T11:03:00.000Z",
  "result" : [ {
    "sensor_name" : "ISG",
    "flows" : 5897
  } ]
}
```
 - Result QueryB (<b> NULL DIMENSION</b>)

```json
[ {
  "timestamp" : "2015-03-17T10:43:00.000Z",
  "result" : [ {
    "dot11_protocol" : null,
    "flows" : 119
  } ]
}, {
  "timestamp" : "2015-03-17T10:44:00.000Z",
  "result" : [ {
    "dot11_protocol" : null,
    "flows" : 5796
  } ]
}, {
  "timestamp" : "2015-03-17T10:45:00.000Z",
  "result" : [ {
    "dot11_protocol" : null,
    "flows" : 5825
  } ]
}, {
  "timestamp" : "2015-03-17T10:46:00.000Z",
  "result" : [ {
    "dot11_protocol" : null,
    "flows" : 5846
  } ]
}, {
  "timestamp" : "2015-03-17T10:47:00.000Z",
  "result" : [ {
    "dot11_protocol" : null,
    "flows" : 5873
  } ]
}, {
  "timestamp" : "2015-03-17T10:48:00.000Z",
  "result" : [ {
    "dot11_protocol" : null,
    "flows" : 5869
  } ]
}, {
  "timestamp" : "2015-03-17T10:49:00.000Z",
  "result" : [ {
    "dot11_protocol" : null,
    "flows" : 5894
  } ]
}, {
  "timestamp" : "2015-03-17T10:50:00.000Z",
  "result" : [ {
    "dot11_protocol" : null,
    "flows" : 5896
  } ]
}, {
  "timestamp" : "2015-03-17T10:51:00.000Z",
  "result" : [ {
    "dot11_protocol" : null,
    "flows" : 5897
  } ]
}, {
  "timestamp" : "2015-03-17T10:52:00.000Z",
  "result" : [ {
    "dot11_protocol" : null,
    "flows" : 5891
  } ]
}, {
  "timestamp" : "2015-03-17T10:53:00.000Z",
  "result" : [ {
    "dot11_protocol" : null,
    "flows" : 5885
  } ]
}, {
  "timestamp" : "2015-03-17T10:54:00.000Z",
  "result" : [ {
    "dot11_protocol" : null,
    "flows" : 5884
  } ]
}, {
  "timestamp" : "2015-03-17T10:55:00.000Z",
  "result" : [ {
    "dot11_protocol" : null,
    "flows" : 5897
  } ]
}, {
  "timestamp" : "2015-03-17T10:56:00.000Z",
  "result" : [ {
    "dot11_protocol" : null,
    "flows" : 5878
  } ]
}, {
  "timestamp" : "2015-03-17T10:57:00.000Z",
  "result" : [ {
    "dot11_protocol" : null,
    "flows" : 3550
  } ]
}, {
  "timestamp" : "2015-03-17T10:58:00.000Z",
  "result" : [ ]
}, {
  "timestamp" : "2015-03-17T10:59:00.000Z",
  "result" : [ ]
}, {
  "timestamp" : "2015-03-17T11:00:00.000Z",
  "result" : [ ]
}, {
  "timestamp" : "2015-03-17T11:01:00.000Z",
  "result" : [ ]
}, {
  "timestamp" : "2015-03-17T11:02:00.000Z",
  "result" : [ ]
}, {
  "timestamp" : "2015-03-17T11:03:00.000Z",
  "result" : [ ]
} ]
```

Now, If you compare last 6 minutes on both queries, you can see how the Query A (NOT NULL) has data, but Query B (NULL) doesn't have data ... I think the query B must return some like this, to last 6 minutes and not an empty result:

```json
{
  "timestamp" : "2015-03-17T10:57:00.000Z",
  "result" : [ {
    "dot11_protocol" : null,
    "flows" : 3550
  } ]
}
```

To reproduce it, I have been used events like this, but with the timestamp inside in the interval time query:

```json
{"client_latlong":"38.35,26.15","dst_country_code":"US","dot11_status":"ASSOCIATED","bytes":2652,"src_net_name":"0.0.0.0/0","flow_sampler_id":0,"direction":"ingress","wireless_station":"22:22:22:22:22:22","biflow_direction":"initiator","pkts":148,"dst":"90.1.44.3","type":"NetFlowv10","client_campus":"Zone Y campus","client_building":"Zone Y building","timestamp":1426590476,"client_mac":"b4:52:7e:8d:24:0f","wireless_id":"ssid_A","flow_end_reason":"idle timeout","src_net":"0.0.0.0/0","client_rssi_num":-24,"engine_id_name":"IANA-L4","src":"98.11.22.55","application_id":"0:60","sensor_ip":"98.11.22.55","application_id_name":"Zone Y","dst_net":"0.0.0.0/0","l4_proto":2,"ip_protocol_version":4,"dst_net_name":"0.0.0.0/0","sensor_name":"ISG","src_country_code":"US","client_floor":"Zone Y floor","engine_id":10,"client_mac_vendor":"SAMSUNG ELECTRO-MECHANICS", "first_switched": 1426589876}
{"client_latlong":"37.75,26.209999999999997","dst_country_code":"US","dot11_status":"ASSOCIATED","bytes":274,"src_net_name":"0.0.0.0/0","flow_sampler_id":0,"direction":"ingress","wireless_station":"33:33:33:33:33:33","biflow_direction":"initiator","pkts":373,"dst":"192.168.2.3","type":"NetFlowv10","client_campus":"Zone C campus","client_building":"Zone C building","timestamp":1426590476,"client_mac":"99:aa:bb:cc:11:00","wireless_id":"ssid_C","flow_end_reason":"idle timeout","src_net":"0.0.0.0/0","client_rssi_num":-18,"engine_id_name":"IANA-L4","src":"90.1.44.3","application_id":"7:10","sensor_ip":"192.168.2.3","application_id_name":"Zone C","dst_net":"0.0.0.0/0","l4_proto":5,"ip_protocol_version":4,"dst_net_name":"0.0.0.0/0","sensor_name":"ISG","src_country_code":"US","client_floor":"Zone C floor","engine_id":5,"client_mac_vendor":"SAMSUNG ELECTRO-MECHANICS", "first_switched": 1426589876}
{"client_latlong":"38.25,26.169999999999998","dst_country_code":"US","dot11_status":"UNKNOWN","bytes":795,"src_net_name":"0.0.0.0/0","flow_sampler_id":0,"direction":"ingress","wireless_station":"33:33:33:33:33:33","biflow_direction":"initiator","pkts":2,"dst":"192.168.2.3","type":"NetFlowv10","client_campus":"Zone Y campus","client_building":"Zone Y building","timestamp":1426590476,"client_mac":"b4:52:7e:88:ca:53","wireless_id":"ssid_A","flow_end_reason":"idle timeout","src_net":"0.0.0.0/0","client_rssi_num":-27,"engine_id_name":"IANA-L4","src":"98.11.22.55","application_id":"3:43","sensor_ip":"80.2.11.4","application_id_name":"Zone Y","dst_net":"0.0.0.0/0","l4_proto":3,"ip_protocol_version":4,"dst_net_name":"0.0.0.0/0","sensor_name":"ISG","src_country_code":"US","client_floor":"Zone Y floor","engine_id":12,"client_mac_vendor":"SAMSUNG ELECTRO-MECHANICS", "first_switched": 1426589876}
{"client_latlong":"37.629999999999995,26.849999999999998","dst_country_code":"US","dot11_status":"PROBING","bytes":633,"src_net_name":"0.0.0.0/0","flow_sampler_id":0,"direction":"ingress","wireless_station":"22:22:22:22:22:22","biflow_direction":"initiator","pkts":63,"dst":"90.1.44.3","type":"NetFlowv10","client_campus":"Zone X campus","client_building":"Zone X building","timestamp":1426590476,"client_mac":"88:32:9b:4e:71:36","wireless_id":"ssid_B","flow_end_reason":"idle timeout","src_net":"0.0.0.0/0","client_rssi_num":-58,"engine_id_name":"IANA-L4","src":"192.168.2.3","application_id":"6:9","sensor_ip":"90.1.44.3","application_id_name":"Zone X","dst_net":"0.0.0.0/0","l4_proto":4,"ip_protocol_version":4,"dst_net_name":"0.0.0.0/0","sensor_name":"ISG","src_country_code":"US","client_floor":"Zone X floor","engine_id":19,"client_mac_vendor":"SAMSUNG ELECTRO-MECHANICS", "first_switched": 1426589876}
{"client_latlong":"37.72,26.11","dst_country_code":"US","dot11_status":"UNKNOWN","bytes":2458,"src_net_name":"0.0.0.0/0","flow_sampler_id":0,"direction":"ingress","wireless_station":"22:22:22:22:22:22","biflow_direction":"initiator","pkts":134,"dst":"90.1.44.3","type":"NetFlowv10","client_campus":"Zone B campus","client_building":"Zone B building","timestamp":1426590476,"client_mac":"98:d6:f7:67:36:cf","wireless_id":"ssid_B","flow_end_reason":"idle timeout","src_net":"0.0.0.0/0","client_rssi_num":-13,"engine_id_name":"IANA-L4","src":"80.2.11.4","application_id":"6:30","sensor_ip":"90.1.44.3","application_id_name":"Zone B","dst_net":"0.0.0.0/0","l4_proto":1,"ip_protocol_version":4,"dst_net_name":"0.0.0.0/0","sensor_name":"ISG","src_country_code":"US","client_floor":"Zone B floor","engine_id":9,"client_mac_vendor":"SAMSUNG ELECTRO-MECHANICS", "first_switched": 1426589876}
{"client_latlong":"38.28,25.98","dst_country_code":"US","dot11_status":"ASSOCIATED","bytes":2142,"src_net_name":"0.0.0.0/0","flow_sampler_id":0,"direction":"ingress","wireless_station":"11:11:11:11:11:11","biflow_direction":"initiator","pkts":159,"dst":"192.168.2.3","type":"NetFlowv10","client_campus":"Zone A campus","client_building":"Zone A building","timestamp":1426590476,"client_mac":"b4:52:7e:7d:5d:8c","wireless_id":"ssid_C","flow_end_reason":"idle timeout","src_net":"0.0.0.0/0","client_rssi_num":-54,"engine_id_name":"IANA-L4","src":"98.11.22.55","application_id":"0:84","sensor_ip":"90.1.44.3","application_id_name":"Zone A","dst_net":"0.0.0.0/0","l4_proto":2,"ip_protocol_version":4,"dst_net_name":"0.0.0.0/0","sensor_name":"ISG","src_country_code":"US","client_floor":"Zone A floor","engine_id":19,"client_mac_vendor":"SAMSUNG ELECTRO-MECHANICS", "first_switched": 1426589876}
{"client_latlong":"37.69,26.509999999999998","dst_country_code":"US","dot11_status":"ASSOCIATED","bytes":742,"src_net_name":"0.0.0.0/0","flow_sampler_id":0,"direction":"ingress","wireless_station":"22:22:22:22:22:22","biflow_direction":"initiator","pkts":464,"dst":"80.2.11.4","type":"NetFlowv10","client_campus":"Zone C campus","client_building":"Zone C building","timestamp":1426590476,"client_mac":"98:d6:f7:67:36:cf","wireless_id":"ssid_A","flow_end_reason":"idle timeout","src_net":"0.0.0.0/0","client_rssi_num":-57,"engine_id_name":"IANA-L4","src":"80.2.11.4","application_id":"0:33","sensor_ip":"90.1.44.3","application_id_name":"Zone C","dst_net":"0.0.0.0/0","l4_proto":9,"ip_protocol_version":4,"dst_net_name":"0.0.0.0/0","sensor_name":"ISG","src_country_code":"US","client_floor":"Zone C floor","engine_id":1,"client_mac_vendor":"SAMSUNG ELECTRO-MECHANICS", "first_switched": 1426589876}
{"client_latlong":"37.87,26.41","dst_country_code":"US","dot11_status":"ASSOCIATED","bytes":1757,"src_net_name":"0.0.0.0/0","flow_sampler_id":0,"direction":"ingress","wireless_station":"11:11:11:11:11:11","biflow_direction":"initiator","pkts":263,"dst":"80.2.11.4","type":"NetFlowv10","client_campus":"Zone X campus","client_building":"Zone X building","timestamp":1426590476,"client_mac":"00:a3:b5:77:1a:3c","wireless_id":"ssid_A","flow_end_reason":"idle timeout","src_net":"0.0.0.0/0","client_rssi_num":-12,"engine_id_name":"IANA-L4","src":"80.2.11.4","application_id":"4:2","sensor_ip":"98.11.22.55","application_id_name":"Zone X","dst_net":"0.0.0.0/0","l4_proto":5,"ip_protocol_version":4,"dst_net_name":"0.0.0.0/0","sensor_name":"ISG","src_country_code":"US","client_floor":"Zone X floor","engine_id":18,"client_mac_vendor":"SAMSUNG ELECTRO-MECHANICS", "first_switched": 1426589876}
{"client_latlong":"37.89,26.73","dst_country_code":"US","dot11_status":"UNKNOWN","bytes":2999,"src_net_name":"0.0.0.0/0","flow_sampler_id":0,"direction":"ingress","wireless_station":"33:33:33:33:33:33","biflow_direction":"initiator","pkts":77,"dst":"80.2.11.4","type":"NetFlowv10","client_campus":"Zone X campus","client_building":"Zone X building","timestamp":1426590476,"client_mac":"98:d6:f7:67:36:cf","wireless_id":"ssid_C","flow_end_reason":"idle timeout","src_net":"0.0.0.0/0","client_rssi_num":-47,"engine_id_name":"IANA-L4","src":"98.11.22.55","application_id":"1:37","sensor_ip":"90.1.44.3","application_id_name":"Zone X","dst_net":"0.0.0.0/0","l4_proto":4,"ip_protocol_version":4,"dst_net_name":"0.0.0.0/0","sensor_name":"ISG","src_country_code":"US","client_floor":"Zone X floor","engine_id":19,"client_mac_vendor":"SAMSUNG ELECTRO-MECHANICS", "first_switched": 1426589876}
{"client_latlong":"37.91,26.009999999999998","dst_country_code":"US","dot11_status":"UNKNOWN","bytes":1480,"src_net_name":"0.0.0.0/0","flow_sampler_id":0,"direction":"ingress","wireless_station":"11:11:11:11:11:11","biflow_direction":"initiator","pkts":380,"dst":"90.1.44.3","type":"NetFlowv10","client_campus":"Zone C campus","client_building":"Zone C building","timestamp":1426590476,"client_mac":"88:11:77:aa:bb:22","wireless_id":"ssid_B","flow_end_reason":"idle timeout","src_net":"0.0.0.0/0","client_rssi_num":-24,"engine_id_name":"IANA-L4","src":"90.1.44.3","application_id":"0:21","sensor_ip":"90.1.44.3","application_id_name":"Zone C","dst_net":"0.0.0.0/0","l4_proto":4,"ip_protocol_version":4,"dst_net_name":"0.0.0.0/0","sensor_name":"ISG","src_country_code":"US","client_floor":"Zone C floor","engine_id":11,"client_mac_vendor":"SAMSUNG ELECTRO-MECHANICS", "first_switched": 1426589876}
{"client_latlong":"38.18,26.549999999999997","dst_country_code":"US","dot11_status":"UNKNOWN","bytes":2514,"src_net_name":"0.0.0.0/0","flow_sampler_id":0,"direction":"ingress","wireless_station":"22:22:22:22:22:22","biflow_direction":"initiator","pkts":369,"dst":"80.2.11.4","type":"NetFlowv10","client_campus":"Zone B campus","client_building":"Zone B building","timestamp":1426590476,"client_mac":"88:11:77:aa:bb:22","wireless_id":"ssid_A","flow_end_reason":"idle timeout","src_net":"0.0.0.0/0","client_rssi_num":-32,"engine_id_name":"IANA-L4","src":"98.11.22.55","application_id":"1:58","sensor_ip":"80.2.11.4","application_id_name":"Zone B","dst_net":"0.0.0.0/0","l4_proto":3,"ip_protocol_version":4,"dst_net_name":"0.0.0.0/0","sensor_name":"ISG","src_country_code":"US","client_floor":"Zone B floor","engine_id":8,"client_mac_vendor":"SAMSUNG ELECTRO-MECHANICS", "first_switched": 1426589876}
{"client_latlong":"37.82,26.83","dst_country_code":"US","dot11_status":"UNKNOWN","bytes":689,"src_net_name":"0.0.0.0/0","flow_sampler_id":0,"direction":"ingress","wireless_station":"11:11:11:11:11:11","biflow_direction":"initiator","pkts":213,"dst":"80.2.11.4","type":"NetFlowv10","client_campus":"Zone X campus","client_building":"Zone X building","timestamp":1426590476,"client_mac":"b4:52:7e:7d:5d:8c","wireless_id":"ssid_B","flow_end_reason":"idle timeout","src_net":"0.0.0.0/0","client_rssi_num":-38,"engine_id_name":"IANA-L4","src":"80.2.11.4","application_id":"1:46","sensor_ip":"90.1.44.3","application_id_name":"Zone X","dst_net":"0.0.0.0/0","l4_proto":7,"ip_protocol_version":4,"dst_net_name":"0.0.0.0/0","sensor_name":"ISG","src_country_code":"US","client_floor":"Zone X floor","engine_id":9,"client_mac_vendor":"SAMSUNG ELECTRO-MECHANICS", "first_switched": 1426589876}
{"client_latlong":"37.44,26.13","dst_country_code":"US","dot11_status":"ASSOCIATED","bytes":2477,"src_net_name":"0.0.0.0/0","flow_sampler_id":0,"direction":"ingress","wireless_station":"33:33:33:33:33:33","biflow_direction":"initiator","pkts":358,"dst":"80.2.11.4","type":"NetFlowv10","client_campus":"Zone A campus","client_building":"Zone A building","timestamp":1426590476,"client_mac":"99:aa:bb:cc:11:00","wireless_id":"ssid_A","flow_end_reason":"idle timeout","src_net":"0.0.0.0/0","client_rssi_num":-32,"engine_id_name":"IANA-L4","src":"90.1.44.3","application_id":"1:92","sensor_ip":"192.168.2.3","application_id_name":"Zone A","dst_net":"0.0.0.0/0","l4_proto":2,"ip_protocol_version":4,"dst_net_name":"0.0.0.0/0","sensor_name":"ISG","src_country_code":"US","client_floor":"Zone A floor","engine_id":16,"client_mac_vendor":"SAMSUNG ELECTRO-MECHANICS", "first_switched": 1426589876}
{"client_latlong":"38.32,26.74","dst_country_code":"US","dot11_status":"ASSOCIATED","bytes":1364,"src_net_name":"0.0.0.0/0","flow_sampler_id":0,"direction":"ingress","wireless_station":"33:33:33:33:33:33","biflow_direction":"initiator","pkts":61,"dst":"80.2.11.4","type":"NetFlowv10","client_campus":"Zone Y campus","client_building":"Zone Y building","timestamp":1426590476,"client_mac":"b4:52:7e:8d:24:0f","wireless_id":"ssid_B","flow_end_reason":"idle timeout","src_net":"0.0.0.0/0","client_rssi_num":-43,"engine_id_name":"IANA-L4","src":"80.2.11.4","application_id":"7:44","sensor_ip":"90.1.44.3","application_id_name":"Zone Y","dst_net":"0.0.0.0/0","l4_proto":5,"ip_protocol_version":4,"dst_net_name":"0.0.0.0/0","sensor_name":"ISG","src_country_code":"US","client_floor":"Zone Y floor","engine_id":3,"client_mac_vendor":"SAMSUNG ELECTRO-MECHANICS", "first_switched": 1426589876}
{"client_latlong":"37.75,26.81","dst_country_code":"US","dot11_status":"UNKNOWN","bytes":950,"src_net_name":"0.0.0.0/0","flow_sampler_id":0,"direction":"ingress","wireless_station":"33:33:33:33:33:33","biflow_direction":"initiator","pkts":175,"dst":"90.1.44.3","type":"NetFlowv10","client_campus":"Zone Y campus","client_building":"Zone Y building","timestamp":1426590476,"client_mac":"54:26:96:d7:62:91","wireless_id":"ssid_B","flow_end_reason":"idle timeout","src_net":"0.0.0.0/0","client_rssi_num":-25,"engine_id_name":"IANA-L4","src":"80.2.11.4","application_id":"5:81","sensor_ip":"98.11.22.55","application_id_name":"Zone Y","dst_net":"0.0.0.0/0","l4_proto":5,"ip_protocol_version":4,"dst_net_name":"0.0.0.0/0","sensor_name":"ISG","src_country_code":"US","client_floor":"Zone Y floor","engine_id":18,"client_mac_vendor":"SAMSUNG ELECTRO-MECHANICS", "first_switched": 1426589876}
{"client_latlong":"38.25,26.13","dst_country_code":"US","dot11_status":"UNKNOWN","bytes":1754,"src_net_name":"0.0.0.0/0","flow_sampler_id":0,"direction":"ingress","wireless_station":"22:22:22:22:22:22","biflow_direction":"initiator","pkts":401,"dst":"80.2.11.4","type":"NetFlowv10","client_campus":"Zone C campus","client_building":"Zone C building","timestamp":1426590476,"client_mac":"b4:52:7e:8d:23:46","wireless_id":"ssid_B","flow_end_reason":"idle timeout","src_net":"0.0.0.0/0","client_rssi_num":-13,"engine_id_name":"IANA-L4","src":"192.168.2.3","application_id":"1:55","sensor_ip":"192.168.2.3","application_id_name":"Zone C","dst_net":"0.0.0.0/0","l4_proto":5,"ip_protocol_version":4,"dst_net_name":"0.0.0.0/0","sensor_name":"ISG","src_country_code":"US","client_floor":"Zone C floor","engine_id":11,"client_mac_vendor":"SAMSUNG ELECTRO-MECHANICS", "first_switched": 1426589876}
{"client_latlong":"37.449999999999996,25.99","dst_country_code":"US","dot11_status":"ASSOCIATED","bytes":215,"src_net_name":"0.0.0.0/0","flow_sampler_id":0,"direction":"ingress","wireless_station":"22:22:22:22:22:22","biflow_direction":"initiator","pkts":371,"dst":"90.1.44.3","type":"NetFlowv10","client_campus":"Zone B campus","client_building":"Zone B building","timestamp":1426590476,"client_mac":"b4:52:7e:8d:24:0f","wireless_id":"ssid_B","flow_end_reason":"idle timeout","src_net":"0.0.0.0/0","client_rssi_num":-31,"engine_id_name":"IANA-L4","src":"98.11.22.55","application_id":"0:26","sensor_ip":"80.2.11.4","application_id_name":"Zone B","dst_net":"0.0.0.0/0","l4_proto":3,"ip_protocol_version":4,"dst_net_name":"0.0.0.0/0","sensor_name":"ISG","src_country_code":"US","client_floor":"Zone B floor","engine_id":5,"client_mac_vendor":"SAMSUNG ELECTRO-MECHANICS", "first_switched": 1426589876}
{"client_latlong":"38.17,26.81","dst_country_code":"US","dot11_status":"ASSOCIATED","bytes":907,"src_net_name":"0.0.0.0/0","flow_sampler_id":0,"direction":"ingress","wireless_station":"22:22:22:22:22:22","biflow_direction":"initiator","pkts":357,"dst":"90.1.44.3","type":"NetFlowv10","client_campus":"Zone Y campus","client_building":"Zone Y building","timestamp":1426590476,"client_mac":"98:d6:f7:67:36:cf","wireless_id":"ssid_B","flow_end_reason":"idle timeout","src_net":"0.0.0.0/0","client_rssi_num":-49,"engine_id_name":"IANA-L4","src":"80.2.11.4","application_id":"6:73","sensor_ip":"80.2.11.4","application_id_name":"Zone Y","dst_net":"0.0.0.0/0","l4_proto":7,"ip_protocol_version":4,"dst_net_name":"0.0.0.0/0","sensor_name":"ISG","src_country_code":"US","client_floor":"Zone Y floor","engine_id":1,"client_mac_vendor":"SAMSUNG ELECTRO-MECHANICS", "first_switched": 1426589876}
{"client_latlong":"37.61,26.349999999999998","dst_country_code":"US","dot11_status":"ASSOCIATED","bytes":724,"src_net_name":"0.0.0.0/0","flow_sampler_id":0,"direction":"ingress","wireless_station":"11:11:11:11:11:11","biflow_direction":"initiator","pkts":45,"dst":"90.1.44.3","type":"NetFlowv10","client_campus":"Zone A campus","client_building":"Zone A building","timestamp":1426590476,"client_mac":"b4:52:7e:8d:23:46","wireless_id":"ssid_A","flow_end_reason":"idle timeout","src_net":"0.0.0.0/0","client_rssi_num":-15,"engine_id_name":"IANA-L4","src":"98.11.22.55","application_id":"0:27","sensor_ip":"98.11.22.55","application_id_name":"Zone A","dst_net":"0.0.0.0/0","l4_proto":7,"ip_protocol_version":4,"dst_net_name":"0.0.0.0/0","sensor_name":"ISG","src_country_code":"US","client_floor":"Zone A floor","engine_id":10,"client_mac_vendor":"SAMSUNG ELECTRO-MECHANICS", "first_switched": 1426589876}
{"client_latlong":"37.55,26.099999999999998","dst_country_code":"US","dot11_status":"PROBING","bytes":2053,"src_net_name":"0.0.0.0/0","flow_sampler_id":0,"direction":"ingress","wireless_station":"11:11:11:11:11:11","biflow_direction":"initiator","pkts":318,"dst":"80.2.11.4","type":"NetFlowv10","client_campus":"Zone X campus","client_building":"Zone X building","timestamp":1426590476,"client_mac":"99:aa:bb:cc:11:00","wireless_id":"ssid_C","flow_end_reason":"idle timeout","src_net":"0.0.0.0/0","client_rssi_num":-4,"engine_id_name":"IANA-L4","src":"90.1.44.3","application_id":"9:64","sensor_ip":"90.1.44.3","application_id_name":"Zone X","dst_net":"0.0.0.0/0","l4_proto":9,"ip_protocol_version":4,"dst_net_name":"0.0.0.0/0","sensor_name":"ISG","src_country_code":"US","client_floor":"Zone X floor","engine_id":5,"client_mac_vendor":"SAMSUNG ELECTRO-MECHANICS", "first_switched": 1426589876}
```

If you need more information about the issue tell me, please

Regards,

Andres

### PR DESCRIPTION
**Pull request by nishantmonu51**
fixes #1211 

1) Problem with having partial null values in column- 
during ingestion incrementalIndex DimDim ignores null values, 
If we ingest a column having partial null values e.g - (null, "v1", null) 
the DimDim created in IncrementalIndex has cardinality 1 with value v1. 
Any topN queries on the partial null column will now ignore the rows having null value. 

this PR fixes above problem by adding null to DimDim as empty strings and assigning null value an id.
the implementation wraps existing dimdim's in a NullValueConverterDimDim which has the responsibility of converts null strings to empty strings for storage and vice-versa.   

2) Filters matched against null values / empty columns - 
     this PR also fixes valueMatchers generated in IncrementalIndexStorageAdapters when matched against null values or empty columns.

### CODE REVIEW

**Comment by cheddar** [comment]
Can we add the data from the tests that were presented in #1211?

File: processing/src/main/java/io/druid/segment/incremental/IncrementalIndexStorageAdapter.java [hunk 1]
```diff
@@ -557,11 +557,11 @@ public EntryHolderValueMatcherFactory(
     @Override
     public ValueMatcher makeValueMatcher(String dimension, String value)
     {
-      Integer dimIndexObject = index.getDimensionIndex(dimension);
-      if (dimIndexObject == null) {
+      final IncrementalIndex.DimDim dimDim = index.getDimension(dimension);
+      if (dimDim == null || dimDim.size() == 0) {
```
Comment (cheddar) [inline processing/src/main/java/io/druid/segment/incremental/IncrementalIndexStorageAdapter.java]: Can we introduce a static util function that does this?

**Comment by nishantmonu51** [comment]
have added tests from #1211 and updated the PR with fixes for handling more null value cases.

**Comment by xvrl** [comment]
I feel this is a little more than just a last minute fix, so I'm proposing we leave this to be fixed in 0.7.2

File: processing/src/main/java/io/druid/segment/IndexMaker.java [hunk 2]
```diff
@@ -610,6 +611,19 @@ public String apply(@Nullable String input)
     progress.stopSection(section);
   }
 
+  static boolean isNullColumn(Iterable<String> dimValues)
```
Comment (fjy) [inline processing/src/main/java/io/druid/segment/IndexMaker.java]: can we have this in another file? My feeling is that we will remove IndexMaker at some piont in the future

**Comment by fjy** [comment]
Had a few minor comments, but :+1: on this

File: processing/src/main/java/io/druid/segment/IndexMaker.java (hunk 2 above)
Comment (nishantmonu51) [inline processing/src/main/java/io/druid/segment/IndexMaker.java]: have moved it to IndexMerger.

**Comment by fjy** [comment]
@cheddar Do you have any thoughts on this PR? I know you've spent a lot of time thinking about nulls and empty strings :)

File: processing/src/main/java/io/druid/segment/IndexMaker.java [hunk 3]
```diff
@@ -542,7 +543,7 @@ private static void setupDimConversion(
 
       for (int i = 0; i < adapters.size(); i++) {
         Indexed<String> dimValues = adapters.get(i).getDimValueLookup(dimension);
-        if (dimValues != null) {
+        if (!IndexMerger.isNullColumn(dimValues)) {
```
Comment (xvrl) [inline processing/src/main/java/io/druid/segment/IndexMaker.java]: dimValues returned by IndexableAdapter should always return null, so there should not be any reason to check for empty string in isNullColumn

File: processing/src/main/java/io/druid/segment/incremental/IncrementalIndexStorageAdapter.java [hunk 4]
```diff
@@ -568,7 +575,7 @@ public EntryHolderValueMatcherFactory(
     }
 
     @Override
-    public ValueMatcher makeValueMatcher(String dimension, String value)
+    public ValueMatcher makeValueMatcher(String dimension,final String value)
```
Comment (xvrl) [inline processing/src/main/java/io/druid/segment/incremental/IncrementalIndexStorageAdapter.java]: missing space after `,`

File: processing/src/main/java/io/druid/segment/incremental/IncrementalIndexStorageAdapter.java [hunk 5]
```diff
@@ -576,7 +583,7 @@ public ValueMatcher makeValueMatcher(String dimension, String value)
       }
       final IncrementalIndex.DimDim dimDim = index.getDimension(dimension);
       if (!dimDim.contains(value)) {
-        if (value == null || "".equals(value)) {
+        if (Strings.isNullOrEmpty(value)) {
```
Comment (xvrl) [inline processing/src/main/java/io/druid/segment/incremental/IncrementalIndexStorageAdapter.java]: if DimDim is already doing the conversion from null to empty, is there a reason to keep checking for both?

File: processing/src/main/java/io/druid/segment/incremental/IncrementalIndex.java [hunk 6]
```diff
@@ -676,6 +683,78 @@ DimDim get(String dimension)
...
+    @Override
+    public void sort()
+    {
+      delegate.sort();
+    }
+
+    @Override
+    public boolean compareCannonicalValues(String s1, String s2)
+    {
+      return delegate.compareCannonicalValues(Strings.emptyToNull(s1), Strings.emptyToNull(s2));
```
Comment (xvrl) [inline processing/src/main/java/io/druid/segment/incremental/IncrementalIndex.java]: this will trigger NPE on OffheapIncrementalIndex

Comment (xvrl) [inline processing/src/main/java/io/druid/segment/incremental/IncrementalIndex.java]: More specifically in OffheapDimDim, since that uses s1.equals(s2)

File: processing/src/test/java/io/druid/query/topn/TopNQueryRunnerTest.java [hunk 7]
```diff
@@ -2325,4 +2330,247 @@ public void testTopNTimeExtraction()
...
+        .intervals(QueryRunnerTestHelper.firstToThird)
+        .aggregators(QueryRunnerTestHelper.commonAggregators)
+        .build();
+
+    HashMap<String, Object> context = new HashMap<String, Object>();
+    Iterator<? extends Result> result = Sequences.toList(runner.run(query, context), Lists.<Result>newArrayList())
+                                                 .iterator();
+    while (result.hasNext()) {
+      TopNResultValue value = (TopNResultValue) result.next().getValue();
+      Assert.assertFalse(value.getValue().isEmpty());
```
Comment (cheddar) [inline processing/src/test/java/io/druid/query/topn/TopNQueryRunnerTest.java]: Is there a reason we aren't testing the actual returned values?

File: processing/src/test/java/io/druid/query/topn/TopNQueryRunnerTest.java [hunk 8]
```diff
@@ -2325,4 +2330,247 @@ public void testTopNTimeExtraction()
...
+                )
+            )
+        )
+    );
+    HashMap<String, Object> context = new HashMap<String, Object>();
+    TestHelper.assertExpectedResults(expectedResults, runner.run(query, context));
+  }
+
+  @Test
+  public void notNullDimension()
```
Comment (cheddar) [inline processing/src/test/java/io/druid/query/topn/TopNQueryRunnerTest.java]: The name of this test is not really doing much to tell me what it's testing.  What is it testing?

File: processing/src/test/java/io/druid/query/topn/TopNQueryRunnerTest.java [hunk 9]
```diff
@@ -2325,4 +2330,247 @@ public void testTopNTimeExtraction()
...
+    Iterator<? extends Result> result = Sequences.toList(runner.run(query, context), Lists.<Result>newArrayList())
+                                                 .iterator();
+    while (result.hasNext()) {
+      TopNResultValue value = (TopNResultValue) result.next().getValue();
+      Assert.assertFalse(value.getValue().isEmpty());
+    }
+  }
+
+  @Test
+  public void nullDimension()
```
Comment (cheddar) [inline processing/src/test/java/io/druid/query/topn/TopNQueryRunnerTest.java]: Same here on the name.  What about null dimension are we testing?

File: processing/src/test/java/io/druid/query/topn/TopNQueryRunnerTest.java [hunk 10]
```diff
@@ -2325,4 +2330,247 @@ public void testTopNTimeExtraction()
...
+
+    while (result.hasNext()) {
+      Result queryResult = result.next();
+      TopNResultValue value = (TopNResultValue) queryResult.getValue();
+      Assert.assertFalse(queryResult.toString(), value.getValue().isEmpty());
+    }
+  }
+
+  @Test
+  public void nullDimensionWithFilter()
```
Comment (cheddar) [inline processing/src/test/java/io/druid/query/topn/TopNQueryRunnerTest.java]: More descriptive name please

File: processing/src/test/java/io/druid/query/topn/TopNQueryRunnerTest.java [hunk 11]
```diff
@@ -2325,4 +2330,247 @@ public void testTopNTimeExtraction()
...
+      boolean containsNull = false;
+      System.out.println(value);
+      for (DimensionAndMetricValueExtractor v : value.getValue()) {
+        if (v.getStringDimensionValue("partial_null_column") == null) {
+          containsNull = true;
+        }
+
+      }
+
+      // The result always contains null dimension, and sometimes doesn't appear.
```
Comment (cheddar) [inline processing/src/test/java/io/druid/query/topn/TopNQueryRunnerTest.java]: What does this comment mean?  Is it saying that the code is non-deterministic and therefore we are asserting that it always contains null?

File: processing/src/test/java/io/druid/query/topn/TopNQueryRunnerTest.java [hunk 12]
```diff
@@ -2325,4 +2330,247 @@ public void testTopNTimeExtraction()
...
+
+    HashMap<String, Object> context = new HashMap<String, Object>();
+    Iterator<? extends Result> result = Sequences.toList(runner.run(query, context), Lists.<Result>newArrayList())
+                                                 .iterator();
+
+    while (result.hasNext()) {
+      Result queryResult = result.next();
+      TopNResultValue value = (TopNResultValue) queryResult.getValue();
+
+      // The result can't be empty.
```
Comment (cheddar) [inline processing/src/test/java/io/druid/query/topn/TopNQueryRunnerTest.java]: I don't believe this comment is adding value...  Is there a special reason why this can never be empty that you would like to explain?  If not, the following line of code should be fine, no?

File: processing/src/test/java/io/druid/query/topn/TopNQueryRunnerTest.java [hunk 13]
```diff
@@ -2325,4 +2330,247 @@ public void testTopNTimeExtraction()
...
+        .threshold(1000)
+        .intervals(QueryRunnerTestHelper.firstToThird)
+        .aggregators(QueryRunnerTestHelper.commonAggregators)
+        .build();
+
+    HashMap<String, Object> context = new HashMap<String, Object>();
+    Iterator<? extends Result> result = Sequences.toList(runner.run(query, context), Lists.<Result>newArrayList())
+                                                 .iterator();
+
+    while (result.hasNext()) {
```
Comment (cheddar) [inline processing/src/test/java/io/druid/query/topn/TopNQueryRunnerTest.java]: I see basically this same while loop implemented three different ways across a couple of methods.  Extract it to a method maybe?

**Comment by cheddar** [comment]
The description on this pull request is not really enough to help me understand what is going on.  I read through the issue as well and nowhere is it explained what the problem was and how it is being fixed.

I'm going to now dive into the code and see if I can reverse out what the issues are, but please make it a habit to provide more information about what is wrong and how you are intending to fix it.

File: processing/src/main/java/io/druid/segment/incremental/IncrementalIndex.java [hunk 14]
```diff
@@ -481,7 +482,13 @@ private long getMaxTimeMillis()
   private String[] getDimVals(final DimDim dimLookup, final List<String> dimValues)
   {
     final String[] retVal = new String[dimValues.size()];
-
+    if (dimValues.size() == 0) {
+      // NULL VALUE
+      if (!dimLookup.contains(null)) {
+        dimLookup.add(null);
+      }
+      return retVal;
```
Comment (cheddar) [inline processing/src/main/java/io/druid/segment/incremental/IncrementalIndex.java]: Why are we returning an empty array instead of just returning `null`?

**Comment by cheddar** [comment]
Ok, if I'm understanding the changes correct, it would appear that we are doing work before persisting the index as well as when querying to convert "bad" input into what the rest of the system expects.  Is it possible for us to do the conversion at ingestion time instead of persist time?  

That seems like it could be more robust and require changes in less locations.

File: processing/src/main/java/io/druid/segment/IndexMaker.java (hunk 3 above)
Comment (nishantmonu51) [inline processing/src/main/java/io/druid/segment/IndexMaker.java]: with the changes in this PR, DimDim treats null value as empty string and reports it as a dimValue so that queries can access that, so a null column can now have be the one having empty string with cardinality 1.

File: processing/src/main/java/io/druid/segment/incremental/IncrementalIndexStorageAdapter.java (hunk 4 above)
Comment (nishantmonu51) [inline processing/src/main/java/io/druid/segment/incremental/IncrementalIndexStorageAdapter.java]: fixed.

File: processing/src/main/java/io/druid/segment/incremental/IncrementalIndex.java (hunk 6 above)
Comment (nishantmonu51) [inline processing/src/main/java/io/druid/segment/incremental/IncrementalIndex.java]: fixed.

File: processing/src/test/java/io/druid/query/topn/TopNQueryRunnerTest.java (hunk 7 above)
Comment (nishantmonu51) [inline processing/src/test/java/io/druid/query/topn/TopNQueryRunnerTest.java]: modified tests to verify actual values.

File: processing/src/test/java/io/druid/query/topn/TopNQueryRunnerTest.java (hunk 10 above)
Comment (nishantmonu51) [inline processing/src/test/java/io/druid/query/topn/TopNQueryRunnerTest.java]: I copied the tests as it is from provided the issue, have modified the names, remove redundant checks and added verification against actual values.

File: processing/src/test/java/io/druid/query/topn/TopNQueryRunnerTest.java (hunk 12 above)
Comment (nishantmonu51) [inline processing/src/test/java/io/druid/query/topn/TopNQueryRunnerTest.java]: fixed.

**Comment by nishantmonu51** [comment]
have updated the PR description for more details on the problem and the fix

**Comment by nishantmonu51** [comment]
Issue was that IncrementalIndex was not able to tell whether a column contains a null 
the changes make IncrementalIndex aware of null values, i.e now the DimDim assigns an id to a null value and stores it as blank string, the logic for conversion from null to empty string and vice versa is encapsulated within NullValueConverterDimDim. at persist time what we do is skip empty columns, will check any redundant work being done while persisting and clean that up.

**Comment by nishantmonu51** [comment]
@cheddar which conversion during persist you are referring to that can be done at the ingestion time ?

**Comment by nishantmonu51** [comment]
travis failing at IndexIOTest, 
case of failure - 
Index1 - 
row1 = dim0 -> ["dim00", "dim01"]
row2 = dim1  -> ["dim10"]
row3 = **dim0** -> null

Index2 - 
row1 = dim0 -> ["dim00", "dim01"]
row2 = dim1  -> ["dim10"]
row3 = **dim1** -> null 

with the changes in the PR the generated indexes are similar both having 3 rows and does not distinguish between the facts that in first case row3 has dim0 mapped to null and dim1 absent while in second case dim0 is absent and dim1 is mapped to null. 

I think its correct to treat missing and null value same and we need to fix the test. 
@cheddar, @xvrl  what are your views on this ?

**Comment by drcrallen** [comment]
As a counter-example, if you were to issue a `topN` over dim1  using a "count" agg as the sorting metric, the results should be different in each case whereby the first case returns "dim10":1 and the second case returns "dim10":1, "null":1

**Comment by nishantmonu51** [comment]
I feel the correct behaviour in both the cases for topN over dim1 should return "dim10":1, "null":2

**Comment by nishantmonu51** [comment]
@xvrl @cheddar @fjy any thoughts on the behaviour of null vs absent values for failing IndexIOTest ?

**Comment by cheddar** [comment]
@nishantmonu51 :+1:

The third row should have `null` for both `dim0` and `dim1` even if it is only specifying one of them.

**Comment by xvrl** [comment]
One way to think about those types of problems would be to map the problem back to what happens when we materialize the index. In my opinion, it makes sense for the IncrementalIndex to behave the same way that the corresponding segments converted to read-only format would. I believe that's what you are trying to do here @nishantmonu51, correct?

**Comment by nishantmonu51** [comment]
thanks xvrl, cheddar, have fixed the failing test

File: processing/src/main/java/io/druid/segment/IndexMerger.java [hunk 15]
```diff
@@ -1228,4 +1229,17 @@ public Rowboat apply(Rowboat lhs, Rowboat rhs)
...
     }
   }
+
+  static boolean isNullColumn(Iterable<String> dimValues)
+  {
+    if (dimValues == null) {
+      return true;
+    }
+    for (String val : dimValues) {
+      if (!Strings.isNullOrEmpty(val)) {
```
Comment (xvrl) [inline processing/src/main/java/io/druid/segment/IndexMerger.java]: I believe `val` here will always be either a non-empty string or `null`, but never empty string, since Indexed<String> returned by getDimValueLookup, which is either an Indexed<String> based on a NullValueConverterDimDim or or a GenericIndexed<String> will already map empty to null.

Comment (nishantmonu51) [inline processing/src/main/java/io/druid/segment/IndexMerger.java]: yeah, it is never empty, have modified the check.

**Comment by cheddar** [comment]
@nishantmonu51 My comments about "doing it before the persist" were basically saying that it looks like we are making changes so that the read side of IncrementalIndex handles things "correctly".  It seems like there is also potential for fixing it on the "write" side, i.e. when the event is initially put into the IncrementalIndex.

I haven't dug that deep into the changes to have a specific suggestion that I'm offering though, was just a thought as I read through your changes.

File: processing/src/main/java/io/druid/segment/IndexMerger.java [hunk 16]
```diff
@@ -1228,4 +1229,17 @@ public Rowboat apply(Rowboat lhs, Rowboat rhs)
...
     }
   }
+
+  static boolean isNullColumn(Iterable<String> dimValues)
+  {
+    if (dimValues == null) {
+      return true;
+    }
+    for (String val : dimValues) {
+      if (v al != null) {
```
Comment (fjy) [inline processing/src/main/java/io/druid/segment/IndexMerger.java]: does this compile?

File: processing/src/main/java/io/druid/segment/IndexMerger.java (hunk 15 above)
Comment (nishantmonu51) [inline processing/src/main/java/io/druid/segment/IndexMerger.java]: fixed.
