### PR TITLE
fix for #1447

### LINKED ISSUE #1447: If RealtimeTuningConfig set ingestOffheap to true,it will  throw IllegalArgumentException exception  in the OffheapIncrementalIndex initialisation process
Druid Version: 0.7.3
Exception  as following:
>2015-06-18T15:44:46,475 ERROR [chief-dsp_report] io.druid.segment.realtime.RealtimeManager - RuntimeException aborted realtime processing[dsp_report]: {class=io.druid.segment.realtime.RealtimeManager, exceptionType=class java.lang.IllegalArgumentException, exceptionMessage=Maximum total buffer size must be greater than aggregation buffer size}
java.lang.IllegalArgumentException: Maximum total buffer size must be greater than aggregation buffer size
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125) ~[guava-16.0.1.jar:?]
        at io.druid.segment.incremental.OffheapIncrementalIndex.<init>(OffheapIncrementalIndex.java:91) ~[druid-processing-0.7.3.jar:0.7.3]

Deep into the code,in the Sink  initialisation process,
```java
 final IncrementalIndex newIndex;
    if (config.isIngestOffheap()) {
      newIndex = new OffheapIncrementalIndex(
          indexSchema,
          // Assuming half space for aggregates
          new OffheapBufferPool(config.getBufferSize()),
          true,
          config.getBufferSize()
      );
```

bufferPool's size is the same as maxTotalBufferSize.So will throw above exception.
As is said on Comment,Assuming half space for aggregates,Like HadoopTuningConfig,we need add a field named aggregationBufferRatio,default value is 0.5.

### PR DESCRIPTION
**Pull request by nishantmonu51**
fixes #1447

### CODE REVIEW

**Comment by fjy** [comment]
:+1:

File: server/src/main/java/io/druid/segment/indexing/RealtimeTuningConfig.java [hunk 1]
```diff
@@ -96,7 +98,8 @@ public RealtimeTuningConfig(
       @JsonProperty("indexSpec") IndexSpec indexSpec,
       @JsonProperty("persistInHeap") Boolean persistInHeap,
       @JsonProperty("ingestOffheap") Boolean ingestOffheap,
-      @JsonProperty("buffersize") Integer bufferSize
+      @JsonProperty("buffersize") Integer bufferSize,
+      @JsonProperty("aggregationBufferRatio") Float aggregationBufferRatio
```
Comment (xvrl) [inline server/src/main/java/io/druid/segment/indexing/RealtimeTuningConfig.java]: we should probably add a serde test while we're at it

Comment (nishantmonu51) [inline server/src/main/java/io/druid/segment/indexing/RealtimeTuningConfig.java]: TaskSerdeTest already checks the serde for the config.

Comment (himanshug) [inline server/src/main/java/io/druid/segment/indexing/RealtimeTuningConfig.java]: optional, but we could still write a dedicated RealtimeTuningConfigTest
LGTM otherwise
