### PR TITLE
Fix failure in nested groupBy with multiple aggregators with same fie…

### LINKED ISSUE #1419: Nested groupBy query fails when outer query has multiple aggregators having same "fieldName"
Group thread:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/druid-user/L4A1iMhzOco/w_5C030krzEJ

Failing Query:
```
{
  "queryType": "groupBy",
  "dataSource":{
    "type": "query",
    "query": {
      "queryType": "groupBy",
      "dataSource": "platform",
      "granularity": "all",
      "dimensions": ["treatment_name", "subject_id", "dim_app_family"],
      "aggregations": [
        { "type": "longSum", "name": "value", "fieldName": "count" }
      ],
      "intervals": [ "2012-01-01T00:00:00.000/2020-01-03T00:00:00.000" ]
    }
  },
  "granularity": "all",
  "dimensions": ["treatment_name", "dim_app_family"],
  "aggregations": [
    { "type": "longSum", "name": "first_moment", "fieldName": "value" },
    { "type": "javascript",
      "name": "second_moment",
      "fieldNames": ["value"],
      "fnAggregate": "function(current, v) { return current + v * v; } ",
      "fnCombine": "function(partialA, partialB) { return partialA + partialB; }",
      "fnReset": "function() { return 0; }"
    }
  ],
  "intervals": [ "2012-01-01T00:00:00.000/2020-01-03T00:00:00.000" ]
}

```

Exception Stacktrace:
```
java.lang.IllegalArgumentException: [value] already defined
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:120)
	at io.druid.query.Queries.verifyAggregations(Queries.java:42)
	at io.druid.query.groupby.GroupByQuery.<init>(GroupByQuery.java:103)
	at io.druid.query.groupby.GroupByQuery$Builder.build(GroupByQuery.java:531)
	at io.druid.query.groupby.GroupByQueryQueryToolChest.mergeGroupByResults(GroupByQueryQueryToolChest.java:160)
```

### PR DESCRIPTION
**Pull request by dclim**
…ldName

Version 2 - Throws an exception if an outer query references an
aggregator that doesn't exist in the inner query, and then uses the
inner query aggregator names to form the columns for the intermediate
incremental index.

Also deleted all the getRequiredColumns() methods which are no longer
being used.

We do something wacky by adding an aggregator factory for the post
aggregators when building the intermediate incremental index, otherwise
queries on post aggregate results fail because the data isn't in the
incremental index.

Closes #1419

### CODE REVIEW

File: processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java [hunk 1]
```diff
@@ -158,12 +160,33 @@ public GroupByQueryQueryToolChest(
...
+      }
+      for (PostAggregator innerPostAggregator : subquery.getPostAggregatorSpecs()) {
+        innerFieldNames.add(innerPostAggregator.getName());
+      }
+
+      for (AggregatorFactory outerAggregator : query.getAggregatorSpecs()) {
+        for (final String fieldName : outerAggregator.requiredFields()) {
+          if (!innerFieldNames.contains(fieldName)) {
+            throw new IllegalArgumentException(
+                String.format("Subquery must have an aggregator or post aggregator with name '%s'", fieldName)
```
Comment (fjy) [inline processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java]: subquery or outer query?

File: processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java [hunk 2]
```diff
@@ -158,12 +160,33 @@ public GroupByQueryQueryToolChest(
...
+            );
+          }
+        }
       }
 
       // We need the inner incremental index to have all the columns required by the outer query
+      final List<AggregatorFactory> aggs = Lists.newArrayList(subquery.getAggregatorSpecs());
+      for (PostAggregator postAgg : subquery.getPostAggregatorSpecs()) {
+        aggs.add(new CountAggregatorFactory(postAgg.getName())); // aggregator type doesn't matter here
```
Comment (fjy) [inline processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java]: why is this?

File: processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java (hunk 1 above)
Comment (dclim) [inline processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java]: The subquery needs to have an aggregator with a name that corresponds to the fieldName in the outer query's aggregator function, otherwise when the outer query runs it'll fail.

Comment (fjy) [inline processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java]: what happens when the outer query needs to access a column that's present in the data and has nothing to do with the sub query?

**Comment by fjy** [comment]
:+1:

File: processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java (hunk 2 above)
Comment (dclim) [inline processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java]: As discussed, this just causes the results of the post aggregator from the subquery to be materialized in the incremental index so that it can be queried again by the outer query.

File: processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java (hunk 1 above)
Comment (dclim) [inline processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java]: As discussed, the outer query doesn't have visibility into the data, only the results returned from the sub query which have been materialized in the intermediate incremental index.

Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java]: why would it? once the inner query is done, it *IS* the data

File: processing/src/test/java/io/druid/query/groupby/GroupByQueryRunnerTest.java [hunk 3]
```diff
@@ -51,6 +51,7 @@
 import io.druid.query.aggregation.JavaScriptAggregatorFactory;
 import io.druid.query.aggregation.LongSumAggregatorFactory;
 import io.druid.query.aggregation.PostAggregator;
+import io.druid.query.aggregation.cardinality.CardinalityAggregatorFactory;
```
Comment (gianm) [inline processing/src/test/java/io/druid/query/groupby/GroupByQueryRunnerTest.java]: I think this import is unused?

**Comment by gianm** [comment]
:+1: looks good to me, would appreciate a second set of eyes

File: processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java [hunk 4]
```diff
@@ -158,12 +160,36 @@ public GroupByQueryQueryToolChest(
...
+        innerFieldNames.add(innerAggregator.getName());
+      }
+      for (PostAggregator innerPostAggregator : subquery.getPostAggregatorSpecs()) {
+        innerFieldNames.add(innerPostAggregator.getName());
+      }
+
+      for (AggregatorFactory outerAggregator : query.getAggregatorSpecs()) {
+        for (final String fieldName : outerAggregator.requiredFields()) {
+          if (!innerFieldNames.contains(fieldName)) {
+            throw new IllegalArgumentException(
```
Comment (xvrl) [inline processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java]: use IAE instead of String.format

File: processing/src/main/java/io/druid/query/aggregation/AggregatorFactory.java [hunk 5]
```diff
@@ -63,13 +63,6 @@
   public AggregatorFactory getCombiningFactory();
 
   /**
-   * Gets a list of all columns that this AggregatorFactory will scan
-   *
-   * @return AggregatorFactories for the columns to scan of the parent AggregatorFactory
-   */
-  public List<AggregatorFactory> getRequiredColumns();
```
Comment (xvrl) [inline processing/src/main/java/io/druid/query/aggregation/AggregatorFactory.java]: removing this method is not backwards compatible for anyone providing their own aggregations as an extensions, and may cause things to fail at runtime if getRequiredColumns is called anywhere else in that extension.

File: processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java [hunk 6]
```diff
@@ -158,12 +160,36 @@ public GroupByQueryQueryToolChest(
...
+        }
       }
 
       // We need the inner incremental index to have all the columns required by the outer query
+      final List<AggregatorFactory> aggs = Lists.newArrayList(subquery.getAggregatorSpecs());
+      for (PostAggregator postAgg : subquery.getPostAggregatorSpecs()) {
+        // This causes the post aggregators from the inner query to be copied to the incremental index so that they are
+        // available as columns for the outer query. The data isn't modified by the aggregator since it has already
+        // been fully grouped by the inner query. Somewhat of a hack to get this working with an incremental index.
+        aggs.add(new DoubleSumAggregatorFactory(postAgg.getName(), postAgg.getName()));
```
Comment (xvrl) [inline processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java]: can we explain the choice of doubleSum here? Does it still work in case the post-aggregator is a complex metric?

File: processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java (hunk 1 above)
Comment (xvrl) [inline processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java]: We should make this error message more helpful and explain *why* the subquery must have the field, e.g. say it is required because it is referenced by the outer query.

File: processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java (hunk 6 above)
Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java]: ok, I think you're right, it won't work with complex postAggregators. I didn't know they existed, but it looks like QuantilesPostAggregator is one

Comment (xvrl) [inline processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java]: can we add a test that has a FieldAccessPostAggregator `field` that references a hyperUnique aggregator `unique` in the subquery, and have the outer query use a `hyperUniqueCardinality` post-aggregator referring `field` and make sure it still works?

Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java]: I think it would work to bring back the requiredColumns and use those instead of a DoubleSumAggregatorFactory. it's kind of silly since we really just want to retain the postAggregator field from the inner query (that's what the DoubleSum would do for numeric values) but there is not really a simple way to do that with an incremental index.

maybe an AggregatorFactory that just returns what it's given first?

Comment (gianm) [inline processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java]: nevermind, the requiredColumns aren't useful because they don't exist for postaggs

**Comment by gianm** [comment]
reverted in e3bb93e8c779a06b26b208c9e08915e87ca1e61a
