### PR TITLE
Fix coordinator->overlord proxy auth failure

### LINKED ISSUE #5038: Coordinator to Overlord proxied requests always fail with "403 Forbidden"
Coordinator accepts `/druid/indexer/v1/*` requests and forwards them to overlord leader via `OverlordProxyServlet`. However, at coordinator, `PreResponseAuthorizationCheckFilter` fails the request because it does not have authorization attributes set.

### PR DESCRIPTION
**Pull request by jon-wei**
Fixes #5038 

This sets "authorization checked=true"  on the original client request for coordinator->overlord proxied requests.

### CODE REVIEW

**Comment by himanshug** [comment]
just want to confirm: will overlord receive credentials of original client that sent the request to coordinator or that of coordinator's http client (e.g. the credentials used by coordinator to talk to overlord in general ) ?

File: integration-tests/src/main/java/io/druid/testing/clients/CoordinatorResourceTestClient.java [hunk 1]
```diff
@@ -155,6 +155,23 @@ public void deleteSegmentsDataSource(String dataSource, Interval interval)
...
+          HttpMethod.GET,
+          StringUtils.format(
+              "%s/druid/indexer/v1/scaling",
+              coordinator
+          )
+      );
+      return response.getStatus();
+    }
+    catch (Exception e) {
+      throw Throwables.propagate(e);
```
Comment (drcrallen) [inline integration-tests/src/main/java/io/druid/testing/clients/CoordinatorResourceTestClient.java]: Suggest 

`throw new RE(e, "Unable to get scaling status from [%s]", coordinator)`

Comment (jon-wei) [reply integration-tests/src/main/java/io/druid/testing/clients/CoordinatorResourceTestClient.java]: Changed to the suggested message

**Comment by jon-wei** [comment]
@himanshug It gets the credentials sent by the original client

**Comment by himanshug** [comment]
:+1:

**Comment by drcrallen** [comment]
Travis IT is failing

**Comment by jon-wei** [comment]
@drcrallen IT passed, previous run failed because of the travis job time limit

**Comment by drcrallen** [comment]
Hmmm, https://github.com/druid-io/druid/pull/5029 is having timeout problems on the integration Tests also.

**Comment by drcrallen** [comment]
@jon-wei can you do the backport please?

**Comment by jon-wei** [comment]
@drcrallen made the backport: https://github.com/druid-io/druid/pull/5042
