### PR TITLE
fix #1715

### LINKED ISSUE #1715: Zombie tasks able to acquire locks after failure
We had an issue where disconnect somewhere occurred long enough for the overlord to log a task as failed, but the task was still running. After 45 mins or so the task submitted a lock acquire request and it was granted, but since the task had already been failed, it never was properly cleaned up.

These are from the overlord

```
2015-09-09T07:33:58,102 INFO [RemoteTaskRunner-Scheduled-Cleanup--0] io.druid.indexing.overlord.RemoteTaskRunner - Running scheduled cleanup for Worker[REDACTED:8080]
2015-09-09T07:33:58,106 INFO [RemoteTaskRunner-Scheduled-Cleanup--0] io.druid.indexing.overlord.RemoteTaskRunner - Failing task[index_realtime_REDACTED]
2015-09-09T07:33:58,106 INFO [RemoteTaskRunner-Scheduled-Cleanup--0] io.druid.indexing.overlord.TaskQueue - Received FAILED status for task: index_realtime_REDACTED
2015-09-09T07:33:58,109 INFO [RemoteTaskRunner-Scheduled-Cleanup--0] io.druid.indexing.overlord.RemoteTaskRunner - Can't shutdown! No worker running task index_realtime_REDACTED
2015-09-09T07:33:58,110 INFO [RemoteTaskRunner-Scheduled-Cleanup--0] io.druid.indexing.overlord.MetadataTaskStorage - Updating task index_realtime_REDACTED to status: TaskStatus{id=index_realtime_REDACTED, status=FAILED, duration=-1}
2015-09-09T07:33:58,132 INFO [RemoteTaskRunner-Scheduled-Cleanup--0] io.druid.indexing.overlord.TaskLockbox - Removing task[index_realtime_REDACTED] from TaskLock[index_realtime_REDACTED]
```

```
2015-09-09T08:15:15,428 INFO [qtpREDACTED] io.druid.indexing.common.actions.LocalTaskActionClient - Performing action for task[index_realtime_REDACTED]: LockAcquireAction{interval=2015-09-09T08:00:00.000Z/2015-09-09T09:00:00.000Z}
2015-09-09T08:15:15,428 INFO [qtpREDACTED] io.druid.indexing.overlord.TaskLockbox - Created new TaskLockPosse: TaskLockPosse{taskLock=TaskLock{groupId=index_realtime_REDACTED, dataSource=REDACTED, interval=2015-09-09T08:00:00.000Z/2015-09-09T09:00:00.000Z, version=2015-09-09T08:15:15.428Z}, taskIds=[]}
2015-09-09T08:15:15,428 INFO [qtpREDACTED] io.druid.indexing.overlord.TaskLockbox - Added task[index_realtime_REDACTED] to TaskLock[index_realtime_REDACTED]
```

Suffice to say, this is a long-running task that acquires multiple 1-hr locks during the course of its execution.

### PR DESCRIPTION
**Pull request by nishantmonu51**
fixes #1715
- TaskLockBox has a set of active tasks
- lock requests throws exception for if they are from a task not in
active task set.
- TaskQueue is responsible for updating the active task set on
tasklockbox

### CODE REVIEW

File: indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java [hunk 1]
```diff
@@ -210,12 +215,16 @@ public TaskLock lock(final Task task, final Interval interval) throws Interrupte
...
    *
    * @return lock version if lock was acquired, absent otherwise
+   * @throws IllegalStateException if the task is not a valid active task
    */
   private Optional<TaskLock> tryLock(final Task task, final Interval interval, final Optional<String> preferredVersion)
   {
     giant.lock();
 
     try {
+      if(!tasks.contains(task)){
```
Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java]: This has me a bit worried because then every task needs to implement equals and hash properly, which I'm not sure was enforced prior to this. Is there a reason it cannot be a set of the string TaskID?

Comment (nishantmonu51) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java]: makes sense, will change it to store taskId.

Comment (nishantmonu51) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java]: done.

File: indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java [hunk 2]
```diff
@@ -66,6 +66,9 @@
 
   private static final EmittingLogger log = new EmittingLogger(TaskLockbox.class);
 
+  // Stores List of Active Tasks. TaskLockbox will only grant locks to active activeTasks.
+  private final Set<String> activeTasks = Sets.newHashSet();
```
Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java]: Does this need memory protection of the big lock to access or modify? If so it is probably worth calling out here.

File: indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java [hunk 3]
```diff
@@ -170,10 +173,11 @@ public int compare(Pair<Task, TaskLock> left, Pair<Task, TaskLock> right)
   public TaskLock lock(final Task task, final Interval interval) throws InterruptedException
   {
     giant.lock();
-
     try {
+      if(!activeTasks.contains(task.getId())){
+        throw new IllegalStateException(String.format("Unable to grant lock to inactive Task [%s]", task.getId()));
```
Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java]: There was a discussion at one point on if tasks acquire locks BEFORE they start running. Does this account for such a case? or is that case actually valid?

Comment (nishantmonu51) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java]: yes, it does accounts for that, 
A task is marked as active when it gets added to the TaskQueue.

Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java]: Gotcha, missed that part thanks

File: indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java [hunk 4]
```diff
@@ -210,12 +216,16 @@ public TaskLock lock(final Task task, final Interval interval) throws Interrupte
...
    *
    * @return lock version if lock was acquired, absent otherwise
+   * @throws IllegalStateException if the task is not a valid active task
    */
   private Optional<TaskLock> tryLock(final Task task, final Interval interval, final Optional<String> preferredVersion)
   {
     giant.lock();
 
     try {
+      if(!activeTasks.contains(task.getId())){
```
Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java]: Why throw ISE instead of returning absent?

File: indexing-service/src/main/java/io/druid/indexing/overlord/TaskQueue.java [hunk 5]
```diff
@@ -499,14 +506,25 @@ private void syncFromStorage()
     try {
       if (active) {
         final List<Task> newTasks = taskStorage.getActiveTasks();
+        List<Task> addedTasks = Lists.newArrayList(Sets.difference(Sets.newHashSet(newTasks), Sets.newHashSet(tasks)));
```
Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskQueue.java]: Also probably need to do difference on taskId instead of task object here as well, unless we make sure each Task has a proper hash and equals.

File: indexing-service/src/main/java/io/druid/indexing/overlord/TaskQueue.java [hunk 6]
```diff
@@ -378,6 +384,7 @@ private void notifyStatus(final Task task, final TaskStatus taskStatus)
       for (int i = tasks.size() - 1; i >= 0; i--) {
         if (tasks.get(i).getId().equals(task.getId())) {
           removed++;
+          taskLockbox.remove(tasks.get(i));
```
Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskQueue.java]: remove return val never checked. Suggest adding in log (info maybe?) if task is attempted to remove but not removed.

File: indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java (hunk 4 above)
Comment (nishantmonu51) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java]: modified to return absent for invalid tasks.

File: indexing-service/src/main/java/io/druid/indexing/overlord/TaskQueue.java (hunk 5 above)
Comment (nishantmonu51) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskQueue.java]: done.

File: indexing-service/src/main/java/io/druid/indexing/overlord/TaskQueue.java (hunk 6 above)
Comment (nishantmonu51) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskQueue.java]: done.

File: indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java (hunk 4 above)
Comment (gianm) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java]: If it doesn't throw something then "lock" will spin forever.

File: indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java [hunk 7]
```diff
@@ -503,6 +513,26 @@ public TaskLockPosse apply(Interval interval)
     }
   }
 
+  public boolean remove(Task task)
+  {
+    giant.lock();
+    try {
+      return activeTasks.remove(task.getId());
```
Comment (gianm) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java]: I think this method should be combined with ```unlock(Task)```, they're both called at the same time (by the queue, when a task finishes).

This method should also be signalling the lockReleaseCondition, since when a task is removed then we want to ISE out of any ```lock(task)``` calls for that task.

File: indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java [hunk 8]
```diff
@@ -170,10 +174,11 @@ public int compare(Pair<Task, TaskLock> left, Pair<Task, TaskLock> right)
   public TaskLock lock(final Task task, final Interval interval) throws InterruptedException
   {
     giant.lock();
-
     try {
+      if(!activeTasks.contains(task.getId())){
```
Comment (gianm) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java]: there's no need to do this here, tryLock will take care of it. ```lock``` is supposed to be an extremely small wrapper.

File: indexing-service/src/main/java/io/druid/indexing/overlord/TaskQueue.java (hunk 5 above)
Comment (gianm) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskQueue.java]: AbstractTask defines equals/hashCode solely in terms of the id. It's meant to be a unique identifier.

File: indexing-service/src/main/java/io/druid/indexing/overlord/TaskQueue.java [hunk 9]
```diff
@@ -499,14 +506,25 @@ private void syncFromStorage()
     try {
       if (active) {
         final List<Task> newTasks = taskStorage.getActiveTasks();
+        List<Task> addedTasks = Lists.newArrayList(Sets.difference(Sets.newHashSet(newTasks), Sets.newHashSet(tasks)));
+        List<Task> removedTasks = Lists.newArrayList(Sets.difference(Sets.newHashSet(tasks), Sets.newHashSet(newTasks)));
+
+        // Clean up removed Tasks
+        for(Task task : removedTasks){
+          shutdown(task.getId());
```
Comment (gianm) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskQueue.java]: Was there a reason to add this here? tasks should be getting cleaned up in ```manage()```, this method should only be responsible for adjusting the ```tasks``` list.

Comment (gianm) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskQueue.java]: Ok I see, you took out the ```clear()```. IMO it would make sense to just do ```taskLockbox.addAll(newTasks)``` and ```tasks.addAll(newTasks)``` here. The removing of tasks from both things can still go through ```manage()```.

File: indexing-service/src/main/java/io/druid/indexing/overlord/TaskQueue.java [hunk 10]
```diff
@@ -378,6 +384,7 @@ private void notifyStatus(final Task task, final TaskStatus taskStatus)
       for (int i = tasks.size() - 1; i >= 0; i--) {
         if (tasks.get(i).getId().equals(task.getId())) {
           removed++;
+          taskLockbox.remove(tasks.get(i));
           tasks.remove(i);
```
Comment (gianm) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskQueue.java]: Should there be a ```removeTaskInternal``` here to mirror ```addTaskInternal```?

File: indexing-service/src/main/java/io/druid/indexing/overlord/TaskQueue.java (hunk 9 above)
Comment (gianm) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskQueue.java]: Hmm, on second thought what probably makes most sense is that ```syncFromStorage``` should add and remove things from both the ```taskLockbox``` and ```tasks```. But it should not call ```shutdown```.

Comment (gianm) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskQueue.java]: The idea being that we are trying to keep ```taskLockbox``` and ```tasks``` in sync, but the shutting down of things involves the runner too, and that's not something we can really try to keep in sync with the other two because it is asynchronous.

**Comment by nishantmonu51** [comment]
@gianm have taken care of your comments. please have a look again

File: indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java (hunk 4 above)
Comment (nishantmonu51) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java]: fixed.

File: indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java [hunk 11]
```diff
@@ -388,20 +395,21 @@ public void unlock(final Task task, final Interval interval)
...
-      for(final TaskLockPosse taskLockPosse : findLockPossesForTask(task)) {
-        unlock(task, taskLockPosse.getTaskLock().getInterval());
-      }
+      log.info("Removing task[%s] from activeTasks", task.getId());
+      for (final TaskLockPosse taskLockPosse : findLockPossesForTask(task)) {
+          unlock(task, taskLockPosse.getTaskLock().getInterval());
+        }
     }
     finally {
+      activeTasks.remove(task.getId());
```
Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java]: unlock should have a finally block of its own, even if this remove is in its own try{}finally{} block.

Comment (nishantmonu51) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java]: done

File: indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java [hunk 12]
```diff
@@ -210,12 +213,16 @@ public TaskLock lock(final Task task, final Interval interval) throws Interrupte
...
    * @return lock version if lock was acquired, absent otherwise
+   * @throws IllegalStateException if the task is not a valid active task
    */
   private Optional<TaskLock> tryLock(final Task task, final Interval interval, final Optional<String> preferredVersion)
   {
     giant.lock();
 
     try {
+      if(!activeTasks.contains(task.getId())){
+        throw new IllegalStateException(String.format("Unable to grant lock to inactive Task [%s]", task.getId()));
```
Comment (fjy) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java]: small comment, but why don't we use ISE here instead?

File: indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java [hunk 13]
```diff
@@ -388,20 +395,26 @@ public void unlock(final Task task, final Interval interval)
...
+        for (final TaskLockPosse taskLockPosse : findLockPossesForTask(task)) {
+          unlock(task, taskLockPosse.getTaskLock().getInterval());
+        }
+      }
+      finally {
+        activeTasks.remove(task.getId());
       }
     }
     finally {
+      activeTasks.remove(task.getId());
```
Comment (drcrallen) [inline indexing-service/src/main/java/io/druid/indexing/overlord/TaskLockbox.java]: This is still here :)

**Comment by fjy** [comment]
:+1:
