### PR TITLE
KafkaIndexTask: allow pause to break out of retry loop

### LINKED ISSUE #3192: KafkaIndexTask should respond to commands while waiting for messages to appear
KafkaIndexTask uses `RetryUtils.retry` (blocking retry) to retry `consumer.poll(POLL_TIMEOUT)` because the KafkaConsumer throws OffsetOutOfRangeException if the seeked-to offset is not present in the topic-partition. This is a legitimate case (the data might not have been written yet) but it means the task is non-responsive to commands from the supervisor when it is at the head of the topic and new messages are not forthcoming.

The retry should be done in a manner that does not block the ability to respond to supervisor commands.

### PR DESCRIPTION
**Pull request by dclim**
Fixes #3192

### CODE REVIEW

File: extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/KafkaIndexTask.java [hunk 1]
```diff
@@ -363,30 +366,41 @@ public void run()
...
           // offset is not present in the topic-partition. This can happen if we're asking a task to read from data
           // that has not been written yet (which is totally legitimate). So let's wait for it to show up.
-          final ConsumerRecords<byte[], byte[]> records = RetryUtils.retry(
-              new Callable<ConsumerRecords<byte[], byte[]>>()
-              {
-                @Override
-                public ConsumerRecords<byte[], byte[]> call() throws Exception
+          ConsumerRecords<byte[], byte[]> records = ConsumerRecords.empty();
+          try {
+            polling = true;
```
Comment (fjy) [inline extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/KafkaIndexTask.java]: doesn't this update to polling need to be locked?

Comment (fjy) [inline extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/KafkaIndexTask.java]: oh nvm, i dont believe it does

File: extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/KafkaIndexTask.java [hunk 2]
```diff
@@ -363,30 +366,41 @@ public void run()
...
+                    return input instanceof OffsetOutOfRangeException;
+                  }
+                },
+                Integer.MAX_VALUE
+            );
+            synchronized (pollingSyncLock) {
+              if (Thread.interrupted()) {
+                throw new InterruptedException();
+              }
+              polling = false;
```
Comment (fjy) [inline extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/KafkaIndexTask.java]: should we set polling to false before throwing the exception?

File: extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/KafkaIndexTask.java (hunk 1 above)
Comment (dclim) [inline extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/KafkaIndexTask.java]: Yeah volatile boolean should be sufficient.

File: extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/KafkaIndexTask.java (hunk 2 above)
Comment (dclim) [inline extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/KafkaIndexTask.java]: The logic here is that if the thread was interrupted, it could be a) because of a pause command breaking out of the retry or b) as part of the shutdown process. If it's part of the pause, `polling` will have been set to `false` by the pause method before interrupting the thread, otherwise `polling` will be `true`. If we set `polling = false` first before throwing the interrupt, then when it is caught on line 398 it will always be treated as a non-shutdown interrupt, the interrupt flag won't be re-set, and the thread won't die.

File: extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/KafkaIndexTask.java (hunk 1 above)
Comment (gianm) [inline extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/KafkaIndexTask.java]: hmm, I think could this be problematic in the case where:

- [run thread] possiblyPause runs and doesn't pause
- [http thread] /pause is called and sets pauseRequested; it doesn't set polling = false or interrupt because polling is already false
- [run thread] read loop starts and never gets interrupted

I think we can avoid this by:

- getting rid of pollingSyncLock and instead synchronizing `polling` under the existing `pauseLock`
- when acquiring the lock for update polling = true in the main thread, do another possiblyPause before actually polling.

Or, maybe cleaner overall would be to stop using RetryUtils.retry, and instead implement retries through timed `await` on a condition. Then we also won't need to mess about with interrupts at all, we can just set a flag and signal the condition to interrupt a potential retry.

Comment (dclim) [inline extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/KafkaIndexTask.java]: I actually did an await on a condition first but was on the fence about which implementation was less intrusive or how much you wanted to keep the backoff algorithm in RetryUtils (which I don't think is that important for this case). If that seems cleaner to you I'm good with swapping the implementations.

Comment (gianm) [inline extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/KafkaIndexTask.java]: Ah, yeah, I think the condition awaiting is going to be cleaner. That'd avoid the complex `polling` / interrupts stuff and probably end up a lot easier to understand.

Comment (dclim) [inline extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/KafkaIndexTask.java]: Sounds good

**Comment by gianm** [comment]
@dclim thanks, looks nicer!

👍

**Comment by fjy** [comment]
👍
