### PR TITLE
Fix FilteredAggregators at ingestion time and in groupBy v2 nested queries.

### LINKED ISSUE #3311: groupBy v2 nested queries do not accept filtered aggregators
But it would be nice.

### PR DESCRIPTION
**Pull request by gianm**
The common theme between the two is they both create "fake" DimensionSelectors
that work on top of Rows. They both do it because there isn't really any
dictionary for the underlying Rows, they're just a stream of data. The fix for
both is to allow a DimensionSelector to tell callers that it has no dictionary
by returning CARDINALITY_UNKNOWN from getValueCardinality. The callers, in
turn, can avoid using it in ways that assume it has a dictionary.

Fixes #3311.

### CODE REVIEW

File: processing/src/main/java/io/druid/segment/DimensionSelector.java [hunk 1]
```diff
@@ -42,7 +44,12 @@
    *
    * Value cardinality would be 2.
    *
-   * @return the value cardinality
+   * Cardinality may be unknown (e.g. the selector used by IncrementalIndex while reading input rows),
+   * in which case this method will return -1. If cardinality is unknown, you should assume this
+   * dimension selector has no dictionary, and avoid calling "lookupId" or "lookupName" outside of
```
Comment (drcrallen) [inline processing/src/main/java/io/druid/segment/DimensionSelector.java]: This is a dangerous change. There are lots of places that will break horribly if (prior illegal value) -1 is returned.

I would feel more comfortable making an exception that is

```java
class UnavailableCardinalityException extends UOE{
}
```

and have things which can handle missing cardinality catch the error.

Comment (drcrallen) [inline processing/src/main/java/io/druid/segment/DimensionSelector.java]: In such a case the method contract would need updated as well to ensure future implementations obey
the expected exceptions.

Comment (gianm) [inline processing/src/main/java/io/druid/segment/DimensionSelector.java]: I'm usually not in favor of exceptions for "normal" control flow like this. It feels wrong to use exceptions for anything other than exceptional conditions.

I already edited the call sites I thought were the biggest potential problems (dimensionSpecs). The other call sites are in the topN engine, where it would be really bizarre for that to get called on a selector without a dictionary. But, I can edit those call sites too just so 100% of call sites are doing the proper check.

Thoughts?

Comment (drcrallen) [inline processing/src/main/java/io/druid/segment/DimensionSelector.java]: I'm ok if 100% of call sites are touched.

Comment (drcrallen) [inline processing/src/main/java/io/druid/segment/DimensionSelector.java]: But then you also need unit tests.

**Comment by fjy** [comment]
👍

File: processing/src/main/java/io/druid/segment/DimensionSelector.java (hunk 1 above)
Comment (drcrallen) [inline processing/src/main/java/io/druid/segment/DimensionSelector.java]: If that's too much would it make sense to have another method here which checks if `getValueCardinality` is expected to be supported?

Comment (gianm) [inline processing/src/main/java/io/druid/segment/DimensionSelector.java]: It's probably not too much, let me go back and look at them though. There aren't that many call sites.

Comment (gianm) [inline processing/src/main/java/io/druid/segment/DimensionSelector.java]: @drcrallen I updated all the call sites. The groupBy ones didn't seem to really need the cardinality (they were just using it as a marker for missing rows) so I switched them to use an invalid value (`MISSING_VALUE`) instead.

The topN ones did need it, so I adjusted them to check the return value. To make that simpler I reduced the number of call sites by removing "cardinality" as a constructor param to TopNParams. It was always set to the dimension selector's getValueCardinality anyway.

**Comment by jon-wei** [comment]
👍
