### PR TITLE
stop supervisor in case of metadata failures

### LINKED ISSUE #3455: Handle kafka supervisor spec metadata insertion failures
In case kafka supervisor spec metadata insertion fails then in the response database exception is returned. However since the supervisor is started before metadata insertion the indexing tasks continues to run even though the insertion failed. I think in case of metadata failures the supervisor should just stop.

This happened when I posted a supervisor spec to overlord but the supervisor table schema in the database had `version` field however I checked recently the schema has been changed to have `created_date`. Therefore, I had to delete the supervisor table and restart the overlord to have the new table schema.

### PR DESCRIPTION
**Pull request by pjain1**
Possibly Fixes #3455

### CODE REVIEW

File: indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorManager.java [hunk 1]
```diff
@@ -181,7 +182,13 @@ private boolean createAndStartSupervisorInternal(SupervisorSpec spec, boolean pe
     supervisor.start(); // try starting the supervisor first so we don't persist a bad spec
 
     if (persistSpec) {
-      metadataSupervisorManager.insert(id, spec);
+      try {
+        metadataSupervisorManager.insert(id, spec);
+      } catch (Exception e) {
+        // Got exception while persisting the spec, stop the supervisor and propagate the exception
+        supervisor.stop(false);
```
Comment (b-slim) [inline indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorManager.java]: not sure why not doing is gracefully by having `true` instead of `false`?

Comment (pjain1) [inline indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorManager.java]: If we stop it gracefully that means tasks that many have been started by this supervisor are allowed to publish what they have read which might be really tiny data as the metadata insert happens just after the supervisor starts. 

Ideally `supervisor.start()` should be called only if metadata insert succeeds but it is not possible here.

File: indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorManager.java [hunk 2]
```diff
@@ -181,7 +182,13 @@ private boolean createAndStartSupervisorInternal(SupervisorSpec spec, boolean pe
     supervisor.start(); // try starting the supervisor first so we don't persist a bad spec
```
Comment (cheddar) [inline indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorManager.java]: I notice this comment here.  I wonder if the supervisor shouldn't have a `.verify()` call on it to make sure the spec is legit, then persist to DB then `start()`?

Or, maybe just store in the DB first, `start()` and if `start()` doesn't work, fail out and remove from the DB again?

File: indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorManager.java (hunk 1 above)
Comment (pjain1) [inline indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorManager.java]: I checked the code again and stop gracefully set to `false` means running tasks are not killed. So, `false` flag is meant to handle cases like leadership changes. Here, we would like to just kill the tasks so doing what @cheddar suggested would be correct.

**Comment by pjain1** [comment]
updated the fix to start the supervisor first and then persist the spec if it succeeds otherwise write tombstone to prevent it being from picked up again.
@dclim does this make sense ?

File: indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorManager.java [hunk 3]
```diff
@@ -177,13 +178,23 @@ private boolean createAndStartSupervisorInternal(SupervisorSpec spec, boolean pe
...
+    try {
+      supervisor = spec.createSupervisor();
+      supervisor.start();
+    }
+    catch (Exception e) {
+      // Supervisor creation or start failed write tombstone only when trying to start a new supervisor
+      if (persistSpec) {
+        metadataSupervisorManager.insert(id, new NoopSupervisorSpec());
+      }
+      Throwables.propagate(e);
```
Comment (b-slim) [inline indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorManager.java]: wondering is this needs to have a retry for some kind of transitory exception or just fail the task. I think with metadata storage we have in place some retry mechanism.

**Comment by b-slim** [comment]
fix seems legit, it will be nice if we can gracefully retry if the insert has a transient kind of issues. 👍

File: indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorManager.java [hunk 4]
```diff
@@ -177,13 +178,23 @@ private boolean createAndStartSupervisorInternal(SupervisorSpec spec, boolean pe
...
       metadataSupervisorManager.insert(id, spec);
     }
 
+    Supervisor supervisor = null;
+    try {
+      supervisor = spec.createSupervisor();
+      supervisor.start();
+    }
+    catch (Exception e) {
+      // Supervisor creation or start failed write tombstone only when trying to start a new supervisor
```
Comment (himanshug) [inline indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorManager.java]: does supervisor.start() failure guarantee that things are not left in a corrupted state and supervisor.stop(true) does not need to be called?

@dclim ?

Comment (dclim) [inline indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorManager.java]: @himanshug to be safe, we should probably make a call to consumer.close() in KafkaSupervisor.start() if the Kafka consumer was instantiated but an exception was thrown afterwards; @pjain1 do you mind adding this?

**Comment by dclim** [comment]
@pjain1 yes that seems good to me, sorry for missing your comment; logic looks good to me, maybe just ensure the Kafka consumer gets cleaned up if start() fails which is something I should've done before, thanks!

**Comment by pjain1** [comment]
@dclim added please verify

File: indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorManager.java (hunk 3 above)
Comment (pjain1) [inline indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorManager.java]: I think it is ok for now .. i don't think we have retry mechanism at least for this insert operation

File: extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/supervisor/KafkaSupervisor.java [hunk 5]
```diff
@@ -275,6 +275,7 @@ public void run()
         );
       }
       catch (Exception e) {
+        consumer.close();
```
Comment (dclim) [inline extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/supervisor/KafkaSupervisor.java]: Can you actually move the code below it:
```
      firstRunTime = DateTime.now().plus(ioConfig.getStartDelay());
      scheduledExec.scheduleAtFixedRate(
          buildRunTask(),
          ioConfig.getStartDelay().getMillis(),
          Math.max(ioConfig.getPeriod().getMillis(), MAX_RUN_FREQUENCY_MILLIS),
          TimeUnit.MILLISECONDS
      );

      started = true;
      log.info(
          "Started KafkaSupervisor[%s], first run in [%s], with spec: [%s]",
          dataSource,
          ioConfig.getStartDelay(),
          spec.toString()
      );
``` 
into the try-catch as well? And also you should probably do a (if consumer != null) {consumer.close();} to avoid an NPE

Comment (pjain1) [inline extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/supervisor/KafkaSupervisor.java]: done

**Comment by dclim** [comment]
@pjain1 sweet thanks, LGTM 👍

**Comment by pjain1** [comment]
rebased with master

**Comment by pjain1** [comment]
@dclim @b-slim @himanshug can we get this in

**Comment by b-slim** [comment]
looks like we have 2 +1

**Comment by fjy** [comment]
@pjain1 backport plz

**Comment by pjain1** [comment]
@fjy https://github.com/druid-io/druid/pull/3532
