### PR TITLE
Fix topN lexicographic sort

### LINKED ISSUE #5814: Lexicographic topN uses invalid optimization when query interval is smaller than segment granularity
Encountered an easily reproducible issue where using a `lexicographic` metrics spec on a `TopN` query produced an unexpectedly different number results than sorting by metric, `alphaNumeric`, or even `inverted` with `lexicographic`. 

Digging into the issue, it appears that specifically for `lexicographic`, [there is an optimization](https://github.com/druid-io/druid/blob/master/processing/src/main/java/io/druid/query/topn/BaseTopNAlgorithm.java#L309)   that can be taken if the query filters are not set. However, this strategy does not hold true if query interval is smaller than the segment granularity, so this must be checked or the query will produce incorrect results.

### PR DESCRIPTION
**Pull request by clintropolis**
fixes #5814

changes:
* pass `StorageAdapter` to topn algorithms to get things like if column is 'sorted' or if query interval is smaller than segment granularity, instead of using `io.druid.segment.Capabilities`
* added test for topn optimization path checking

### CODE REVIEW

**Comment by fjy** [comment]
👍

File: processing/src/main/java/io/druid/segment/StorageAdapter.java [hunk 1]
```diff
@@ -53,16 +53,16 @@
   Comparable getMinValue(String column);
   @Nullable
   Comparable getMaxValue(String column);
-  Capabilities getCapabilities();
+  boolean areDimensionValuesSorted();
```
Comment (drcrallen) [inline processing/src/main/java/io/druid/segment/StorageAdapter.java]: is this used in extensions anywhere?

File: processing/src/main/java/io/druid/query/topn/BaseTopNAlgorithm.java [hunk 2]
```diff
@@ -284,7 +291,8 @@ public void keepOnlyN(int n)
       keepOnlyN = n;
     }
 
-    protected Pair<Integer, Integer> computeStartEnd(int cardinality)
+    @VisibleForTesting
```
Comment (drcrallen) [inline processing/src/main/java/io/druid/query/topn/BaseTopNAlgorithm.java]: this isn't used in any tests, does it need the expanded scope?

Comment (clintropolis) [reply processing/src/main/java/io/druid/query/topn/BaseTopNAlgorithm.java]: Oops, forgot to add test file 😜

Comment (clintropolis) [reply processing/src/main/java/io/druid/query/topn/BaseTopNAlgorithm.java]: Oh, nevermind, it's there just diff hidden https://github.com/druid-io/druid/pull/5815/files#diff-6e686ab8ec3a73aeb64ae0583b87af0bR104

File: processing/src/main/java/io/druid/segment/StorageAdapter.java (hunk 1 above)
Comment (clintropolis) [reply processing/src/main/java/io/druid/segment/StorageAdapter.java]: Good question, I don't know the answer. Anyone?

Comment (clintropolis) [reply processing/src/main/java/io/druid/segment/StorageAdapter.java]: I can _not_ remove it if preferable, since class is marked `@PublicApi`, I wasn't paying close attention.

Comment (jihoonson) [reply processing/src/main/java/io/druid/segment/StorageAdapter.java]: This can be removed, but if so, this change can be applied to only major releases.

Comment (clintropolis) [reply processing/src/main/java/io/druid/segment/StorageAdapter.java]: Bleh, yeah. I will back out this change and split removal of this class into another PR

File: processing/src/main/java/io/druid/segment/StorageAdapter.java [hunk 3]
```diff
@@ -54,15 +54,16 @@
   @Nullable
   Comparable getMaxValue(String column);
   Capabilities getCapabilities();
+  boolean areDimensionValuesSorted();
 
   /**
-   * Returns capabilities of a particular column, if known. May be null if the column doesn't exist, or if
-   * the column does exist but the capabilities are unknown. The latter is possible with dynamically discovered
+   * Returns storageAdapter of a particular column, if known. May be null if the column doesn't exist, or if
```
Comment (jihoonson) [inline processing/src/main/java/io/druid/segment/StorageAdapter.java]: Please revert javadoc as well.

Comment (jihoonson) [reply processing/src/main/java/io/druid/segment/StorageAdapter.java]: Probably `@Deprecated`?

File: processing/src/main/java/io/druid/segment/StorageAdapter.java [hunk 4]
```diff
@@ -54,15 +54,16 @@
   @Nullable
   Comparable getMaxValue(String column);
   Capabilities getCapabilities();
+  boolean areDimensionValuesSorted();
```
Comment (jihoonson) [inline processing/src/main/java/io/druid/segment/StorageAdapter.java]: This class doesn't have enough javadoc, so let's make it better. Please add javadoc for this method.

File: processing/src/main/java/io/druid/segment/StorageAdapter.java (hunk 3 above)
Comment (clintropolis) [reply processing/src/main/java/io/druid/segment/StorageAdapter.java]: Oops, that change was overzealous intellij

File: processing/src/main/java/io/druid/segment/VirtualColumn.java [hunk 5]
```diff
@@ -74,14 +74,14 @@
 
 
   /**
-   * Returns the capabilities of this virtual column, which includes a type that corresponds to the best
```
Comment (clintropolis) [inline processing/src/main/java/io/druid/segment/VirtualColumn.java]: oops, another intellij mistake

**Comment by drcrallen** [comment]
```
Tests run: 23, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 56.342 sec <<< FAILURE! - in io.druid.indexing.overlord.RemoteTaskRunnerTest
testStatusRemoved(io.druid.indexing.overlord.RemoteTaskRunnerTest)  Time elapsed: 21.318 sec  <<< ERROR!
java.util.concurrent.TimeoutException: Timeout waiting for task.
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:269)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:96)
	at io.druid.indexing.overlord.RemoteTaskRunnerTest.testStatusRemoved(RemoteTaskRunnerTest.java:315)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

```
