### PR TITLE
Detailed error message when unable to create temp dir

### LINKED ISSUE #5576: RealtimeTuningConfig: Better error message when tmp dir does not exist
This cryptic error occurs when your `java.io.tmpdir` doesn't exist, or when we don't have write access to it. This is an old stack trace, but I believe the issue still exists.

```
java.lang.IllegalStateException: Failed to create directory within 10000 attempts (tried 1472453270713-0 to 1472453270713-9999)
	at com.google.common.io.Files.createTempDir(Files.java:600) ~[guava-16.0.1.jar:?]
	at io.druid.segment.indexing.RealtimeTuningConfig.createNewBasePersistDirectory(RealtimeTuningConfig.java:56) ~[druid-server-0.9.1.1.jar:0.9.1.1]
	at io.druid.segment.indexing.RealtimeTuningConfig.<init>(RealtimeTuningConfig.java:118) ~[druid-server-0.9.1.1.jar:0.9.1.1]
	at io.druid.indexing.common.task.IndexTask.convertTuningConfig(IndexTask.java:146) ~[druid-indexing-service-0.9.1.1.jar:0.9.1.1]
	at io.druid.indexing.common.task.IndexTask.generateSegment(IndexTask.java:376) ~[druid-indexing-service-0.9.1.1.jar:0.9.1.1]
	at io.druid.indexing.common.task.IndexTask.run(IndexTask.java:221) ~[druid-indexing-service-0.9.1.1.jar:0.9.1.1]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:436) [druid-indexing-service-0.9.1.1.jar:0.9.1.1]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:408) [druid-indexing-service-0.9.1.1.jar:0.9.1.1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

### PR DESCRIPTION
**Pull request by yuppie-flu**
Fixes #5576

### CODE REVIEW

File: server/src/main/java/io/druid/segment/indexing/RealtimeTuningConfig.java [hunk 1]
```diff
@@ -55,7 +55,14 @@
 
   private static File createNewBasePersistDirectory()
   {
-    return Files.createTempDir();
+    try {
+      return Files.createTempDir();
+    }
+    catch (IllegalStateException e) {
+      String message = "Failed to create temporary directory!" + System.lineSeparator() +
```
Comment (gianm) [inline server/src/main/java/io/druid/segment/indexing/RealtimeTuningConfig.java]: Nit: error messages with line breaks can make it tougher to grep through logs, and also can look weird, so I would leave it out.

File: server/src/main/java/io/druid/segment/indexing/RealtimeTuningConfig.java [hunk 2]
```diff
@@ -55,7 +55,14 @@
...
+              "Make sure `java.io.tmpdir` property is set to existing and writable directory.";
```
Comment (gianm) [inline server/src/main/java/io/druid/segment/indexing/RealtimeTuningConfig.java]: Grammar: "Make sure the `java.io.tmpdir` property is set to an existing and writable directory."

File: server/src/main/java/io/druid/segment/indexing/RealtimeTuningConfig.java (hunk 1 above)
Comment (gianm) [reply server/src/main/java/io/druid/segment/indexing/RealtimeTuningConfig.java]: I would also include the current `java.io.tmpdir` property here, something like, "Failed to create temporary directory in[%s]" & format that with `java.io.tmpdir`. Using `ISE` instead of `IllegalStateException` can help here (it does string formatting in the constructor).

Comment (yuppie-flu) [reply server/src/main/java/io/druid/segment/indexing/RealtimeTuningConfig.java]: Thanks, fixed

File: server/src/main/java/io/druid/segment/indexing/RealtimeTuningConfig.java (hunk 2 above)
Comment (yuppie-flu) [reply server/src/main/java/io/druid/segment/indexing/RealtimeTuningConfig.java]: fixed

**Comment by yuppie-flu** [comment]
What is going on with tests on CI? Failures look very random...
Is the only solution to restart the build?

**Comment by gianm** [comment]
We have been having some trouble with the CI infra recently - sorry about that. I restarted the two tests that didn't pass.
